import {database} from '@/db/raw';
import {questions,publicQuestion,Subject} from '@/lib/curriculum';
const subjects:Subject[]=['reading','math','logic'];
function initial(id:string){return {id,name:id==='maya'?'Maya':'Lydia',grade:id==='maya'?'grade1':'prek',stars:0,completed:0,history:[] as any[],skills:Object.fromEntries(subjects.map(s=>[s,{seen:0,first:0,level:1}])),seen:[] as string[],session:null as any};}
async function row(id:string){const db=database();await db.prepare('INSERT OR IGNORE INTO explorers (id,data,revision) VALUES (?, ?, 0)').bind(id,JSON.stringify(initial(id))).run();return await db.prepare('SELECT data,revision FROM explorers WHERE id=?').bind(id).first<{data:string;revision:number}>();}
function clean(p:any){return {...p,session:p.session?{...p.session,questions:undefined,question:p.session.index<p.session.questions.length?publicQuestion(questions.find(q=>q.id===p.session.questions[p.session.index])!):null,total:p.session.questions.length}:null};}
async function readAll(){return Promise.all(['maya','lydia'].map(async id=>clean(JSON.parse((await row(id))!.data))));}
export async function GET(){try{return Response.json({profiles:await readAll()});}catch(e){console.error(e);return Response.json({error:'We could not load your adventures. Please try again.'},{status:503});}}
export async function POST(request:Request){try{const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return Response.json({error:'Request not allowed.'},{status:403});const body:any=await request.json();if(!body||typeof body!=="object")return Response.json({error:"Invalid request."},{status:400});if(!['maya','lydia'].includes(body.profile))return Response.json({error:'Choose an explorer.'},{status:400});const old=await row(body.profile);const p=JSON.parse(old!.data);let feedback:any=null;
if(body.action==='profile'){if(typeof body.name!=='string'||body.name.trim().length<1||body.name.trim().length>24||!['prek','grade1'].includes(body.grade))return Response.json({error:'Please enter a name and learning track.'},{status:400});if(body.grade!==p.grade){p.skills=initial(p.id).skills;p.seen=[];p.session=null;}p.name=body.name.trim();p.grade=body.grade;}
else if(body.action==='start'){if(!['daily',...subjects].includes(body.subject))return Response.json({error:'Choose a world.'},{status:400});if(p.session&&p.session.index<p.session.questions.length&&(p.session.subject===body.subject||body.subject==='daily'))return Response.json({profile:clean(p)});const chosen:any[]=[];for(let i=0;i<5;i++){const s=body.subject==='daily'?subjects[i%3]:body.subject;const pool=questions.filter(q=>q.grade===p.grade&&q.subject===s&&q.level===p.skills[s].level&&!chosen.includes(q.id));const unseen=pool.filter(q=>!p.seen.includes(q.id));const candidates=unseen.length?unseen:pool;const q=candidates[(p.completed+i)%candidates.length];chosen.push(q.id);}p.session={id:crypto.randomUUID(),subject:body.subject,questions:chosen,index:0,misses:0,hinted:false,first:0,started:Date.now()};}
else if(body.action==='answer'||body.action==='hint'){const s=p.session;if(!s||s.id!==body.session||s.index>=s.questions.length||body.question!==s.questions[s.index])return Response.json({error:'This activity changed. Please return to your adventure and try again.'},{status:409});const q=questions.find(q=>q.id===s.questions[s.index])!;if(body.action==='hint'){s.hinted=true;feedback={hint:q.hint};}else{if(!q.options.includes(body.answer))return Response.json({error:'Choose one of the answers.'},{status:400});const correct=body.answer===q.answer;feedback={correct,message:correct?q.explanation:'Good thinking. Let’s try another answer.',hint:correct?null:q.hint};if(correct){const skill=p.skills[q.subject];skill.seen++;if(s.misses===0&&!s.hinted){skill.first++;s.first++;}if(!p.seen.includes(q.id))p.seen.push(q.id);s.index++;s.misses=0;s.hinted=false;if(skill.seen%5===0){const ratio=skill.first/skill.seen;if(ratio>=0.8)skill.level=Math.min(3,skill.level+1);else if(ratio<0.5)skill.level=Math.max(1,skill.level-1);}if(s.index===s.questions.length){p.completed++;p.stars+=10;p.history=[{date:new Date().toISOString(),subject:s.subject,first:s.first,total:5,grade:p.grade},...p.history].slice(0,100);}}else{s.misses++;}}}
else return Response.json({error:'Unknown action.'},{status:400});
const result=await database().prepare('UPDATE explorers SET data=?, revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(p),p.id,old!.revision).run();if(!result.meta.changes)return Response.json({error:'Progress changed in another window. Please reload.'},{status:409});return Response.json({profile:clean(p),feedback});
}catch(e){console.error(e);return Response.json({error:'Your progress could not be saved. Please try again.'},{status:503});}}
