'use client';
import {useEffect,useRef,useState,useCallback} from 'react';
import {Undo2,Redo2,Save,Volume2} from 'lucide-react';
import {artTemplates,creativeChallenges} from '@/lib/art-templates';
import {drawMark,renderArtwork} from '@/lib/art-renderer';
import {workspaceCollection,workspaceRequest} from '@/lib/workspace-client';
import type {Artwork,ArtMark,WorkspaceItem} from '@/lib/workspace-content';
import {HandwritingGuide} from './handwriting-guide';
import {readAloud} from '@/lib/speech';
import {ImmersiveStage} from '@/components/shell/ImmersiveStage';
const palette=['#253d52','#e96963','#f3b843','#6eaf87','#5d9dd3','#ad85c9','#eb95b4','#8c684b','#ffffff'];
const fresh=(mode:Artwork['mode'],template='blank',name='Explorer'):Artwork=>({title:'My little masterpiece',mode,template,guide:mode==='writing'?name:'',caption:'',marks:[]});
export function ArtworkPreview({art}:{art:Artwork}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{if(ref.current)renderArtwork(ref.current,art);},[art]);return <canvas ref={ref} width={300} height={210} className="art-preview" role="img" aria-label={art.title}/>;}
export function CreativeStudio({profileId,name,paused,parent=false,onDirtyChange}:{profileId:string;name:string;paused:boolean;parent?:boolean;onDirtyChange?:(dirty:boolean)=>void}){
  const [gallery,setGallery]=useState<WorkspaceItem<Artwork>[]>([]),[art,setArt]=useState<Artwork|null>(null),[record,setRecord]=useState<WorkspaceItem<Artwork>|null>(null),[redo,setRedo]=useState<ArtMark[]>([]),[dirty,setDirty]=useState(false);
  const [tool,setTool]=useState<ArtMark['tool']>('pencil'),[color,setColor]=useState(palette[0]),[size,setSize]=useState(8),[stamp,setStamp]=useState('⭐'),[category,setCategory]=useState('All'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true);
  const [galleryPage,setGalleryPage]=useState(0),[hasMore,setHasMore]=useState(false);
  const baseCanvas=useRef<HTMLCanvasElement|null>(null);
  const canvas=useRef<HTMLCanvasElement>(null),stroke=useRef<ArtMark|null>(null),frame=useRef<number|null>(null),cursor=useRef<[number,number]>([500,350]);
  const [dpr,setDpr]=useState(1);
  useEffect(()=>{const measure=()=>setDpr(Math.min(window.devicePixelRatio||1,3));measure();const media=window.matchMedia(`(resolution: ${window.devicePixelRatio}dppx)`);media.addEventListener('change',measure);return()=>media.removeEventListener('change',measure);},[]);
  useEffect(()=>{const controller=new AbortController();workspaceCollection<WorkspaceItem<Artwork>>(profileId,'art',controller.signal).then(items=>{setGallery(items);setHasMore(items.length===12);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[profileId]);
  useEffect(()=>{if(canvas.current&&art)renderArtwork(canvas.current,art);},[art,dpr]);
  useEffect(()=>{onDirtyChange?.(dirty);return ()=>onDirtyChange?.(false);},[dirty,onDirtyChange]);
  useEffect(()=>{const protect=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[dirty]);
  useEffect(()=>()=>{if(frame.current!==null)cancelAnimationFrame(frame.current);},[]);
  async function more(){setBusy(true);setError('');try{const items=await workspaceCollection<WorkspaceItem<Artwork>>(profileId,'art',undefined,galleryPage+1);setGallery(previous=>[...previous,...items.filter(item=>!previous.some(p=>p.id===item.id))]);setGalleryPage(p=>p+1);setHasMore(items.length===12);}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
  const addMark=useCallback((mark:ArtMark)=>{setArt(a=>a&&({...a,marks:[...a.marks,mark]}));setRedo([]);setDirty(true);setMessage('');},[]);
  function open(next:Artwork,item:WorkspaceItem<Artwork>|null=null){setArt(next);setRecord(item);setRedo([]);setDirty(false);setError('');setMessage('');}
  function point(e:React.PointerEvent<HTMLCanvasElement>):[number,number]{const r=e.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(999,(e.clientX-r.left)*1000/r.width)),Math.max(0,Math.min(699,(e.clientY-r.top)*700/r.height))];}
  function end(e:React.PointerEvent<HTMLCanvasElement>){if(stroke.current){addMark(stroke.current);stroke.current=null;}if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}
  async function save(copy=false){if(!art||busy)return;setBusy(true);setError('');try{const result=await workspaceRequest<{item:WorkspaceItem<Artwork>}>({action:'save-art',profile:profileId,id:copy?undefined:record?.id,revision:record?.revision,data:art});setRecord(result.item);setGallery(items=>[result.item,...items.filter(i=>i.id!==result.item.id)]);setDirty(false);setMessage('Saved in your gallery!');}catch(e){setError(e instanceof Error?e.message:'Try saving again.');}finally{setBusy(false);}}
  if(art)return <section className="studio-editor">{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}
    <ImmersiveStage title={art.mode==='writing'?'Writing atelier':art.mode==='coloring'?'Coloring garden':'Drawing atelier'} exitLabel="Studio" onExit={()=>{if(!dirty||window.confirm('Leave without saving these changes?')){setArt(null);setDirty(false);}}} tools={<button className="primary" disabled={busy||paused} onClick={()=>save()}><Save size={18}/>{busy?'Saving…':'Save artwork'}</button>}>
    <div className="studio-stage">
    <fieldset disabled={busy||paused} className="studio-toolbox"><legend>Make it yours</legend><div className="tool-row">{(['pencil','marker','crayon','brush','eraser','fill','stamp'] as const).map(t=><button type="button" key={t} aria-pressed={tool===t} onClick={()=>setTool(t)}>{t==='fill'?'Paint bucket':t}</button>)}</div><div className="tool-row palette">{palette.map(c=><button key={c} style={{background:c}} aria-label={`Color ${c}`} aria-pressed={color===c} onClick={()=>setColor(c)}/>)}<label>Custom color<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label>Brush size<input type="range" min={2} max={40} value={size} onChange={e=>setSize(Number(e.target.value))}/></label></div>{tool==='stamp'&&<div className="tool-row">{['⭐','❤️','🌸','🐱','🦋','🌈','🚀','🔺','🔵'].map(s=><button key={s} aria-pressed={stamp===s} onClick={()=>setStamp(s)}>{s}</button>)}</div>}<div className="tool-row"><button disabled={!art.marks.length} onClick={()=>{const last=art.marks.at(-1)!;setRedo(r=>[...r,last]);setArt({...art,marks:art.marks.slice(0,-1)});setDirty(true);}}><Undo2 size={18}/>Undo</button><button disabled={!redo.length} onClick={()=>{setArt({...art,marks:[...art.marks,redo.at(-1)!]});setRedo(redo.slice(0,-1));setDirty(true);}}><Redo2 size={18}/>Redo</button><button onClick={()=>{if(window.confirm('Clear your marks? You can Redo to bring them back one at a time.')){setRedo([...art.marks].reverse());setArt({...art,marks:[]});setDirty(true);}}}>Clear marks</button><button onClick={()=>save(true)}>Save a new copy</button></div></fieldset>
    {art.mode==='writing'&&<label className="writing-guide">Trace a letter, word, or your name<input disabled={busy||paused} value={art.guide} maxLength={50} onChange={e=>{setArt({...art,template:'blank',guide:e.target.value});setDirty(true);}}/><button className="read-button" onClick={()=>readAloud(art.guide)}><Volume2 size={18}/>Listen</button></label>}
    {art.mode==='writing'&&<details className="handwriting-options"><summary>Practice trails & stroke examples</summary><HandwritingGuide disabled={busy||paused} onChoose={key=>{if(dirty&&!window.confirm('Start a new practice page without saving these changes?'))return;open({...fresh('writing',`trace:${key}`,name),title:`My ${key} practice`,guide:''});}}/></details>}
    <canvas ref={canvas} width={Math.round(1000*dpr)} height={Math.round(700*dpr)} className="drawing-canvas" tabIndex={0} role="application" aria-label="Drawing canvas. Draw with a pointer. Keyboard: arrows move; Space makes a mark." onKeyDown={e=>{if(paused||busy)return;const moves:Record<string,[number,number]>={ArrowLeft:[-15,0],ArrowRight:[15,0],ArrowUp:[0,-15],ArrowDown:[0,15]};if(moves[e.key]){e.preventDefault();cursor.current=[Math.max(0,Math.min(999,cursor.current[0]+moves[e.key][0])),Math.max(0,Math.min(699,cursor.current[1]+moves[e.key][1]))];setMessage(`Canvas position ${cursor.current[0]}, ${cursor.current[1]}`);}else if(e.key===' '){e.preventDefault();if(art.marks.length<600)addMark({tool,color,size,stamp,points:[cursor.current]});}}}
      onPointerDown={e=>{if(paused||busy||stroke.current)return;if(art.marks.length>=600){setError('This page is full of ideas! Save it, then begin a new page.');return;}e.currentTarget.setPointerCapture(e.pointerId);const mark:ArtMark={tool,color,size,stamp,points:[point(e)]};if(tool==='fill'||tool==='stamp'){addMark(mark);return;}baseCanvas.current??=document.createElement('canvas');baseCanvas.current.width=canvas.current?.width??1000;baseCanvas.current.height=canvas.current?.height??700;baseCanvas.current.getContext('2d')?.drawImage(e.currentTarget,0,0);stroke.current=mark;}}
      onPointerMove={e=>{if(!stroke.current)return;const next=point(e);if(stroke.current.points.length<3000)stroke.current.points.push(next);if(frame.current===null)frame.current=requestAnimationFrame(()=>{frame.current=null;if(canvas.current&&stroke.current){const ctx=canvas.current.getContext('2d');if(ctx&&baseCanvas.current){ctx.setTransform(1,0,0,1,0,0);ctx.drawImage(baseCanvas.current,0,0);ctx.setTransform(canvas.current.width/1000,0,0,canvas.current.height/700,0,0);drawMark(ctx,stroke.current);ctx.setTransform(1,0,0,1,0,0);}}});}}
      onPointerUp={end} onPointerCancel={end}/>
    </div></ImmersiveStage>
    <p className="studio-tip">Your marks stay when you Undo, redo, and save. Use the paint bucket to fill a closed space. Completed artwork is yours to keep—there is no score.</p><div className="form-two"><label>Artwork name<input disabled={busy||paused} value={art.title} maxLength={70} onChange={e=>{setArt({...art,title:e.target.value});setDirty(true);}}/></label><label>Tell the story of your picture<textarea disabled={busy||paused} value={art.caption} maxLength={800} onChange={e=>{setArt({...art,caption:e.target.value});setDirty(true);}}/></label></div>
  </section>;
  return <section className="creative-studio"><div className="creative-hero"><h1>A little imagination.<br/>A world of your own.</h1><p>Draw, color, write, and tell your story.</p></div>{error&&<p className="error" role="alert">{error}</p>}
    <div className="creative-doors">{([['drawing','🎨','Drawing','Make something only you can imagine.'],['coloring','🦋','Coloring','Bring a tiny world to life.'],['writing','✏️','Writing','Letters, words, and your own stories.']] as const).map(([mode,emoji,title,description])=><button key={mode} disabled={paused} onClick={()=>mode==='coloring'?document.getElementById('coloring-library')?.scrollIntoView({behavior:'smooth'}):open(fresh(mode,'blank',name))}><span>{emoji}</span><strong>{title}</strong><small>{description}</small></button>)}</div>
    <section className="creative-challenge"><div><h2>A spark for your imagination</h2><p>{creativeChallenges[gallery.length%creativeChallenges.length]}</p></div><button className="secondary" disabled={paused} onClick={()=>open({...fresh('drawing'),caption:creativeChallenges[gallery.length%creativeChallenges.length]})}>Try this idea</button></section>
    <section id="coloring-library"><h2>The coloring bookshelf</h2><div className="game-filters" role="group" aria-label="Coloring categories">{['All',...new Set(artTemplates.filter(t=>t[0]!=='blank').map(t=>t[2]))].map(c=><button aria-pressed={category===c} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="template-grid">{artTemplates.filter(t=>t[0]!=='blank'&&(category==='All'||t[2]===category)).map(([id,title])=><button disabled={paused} key={id} onClick={()=>open({...fresh('coloring',id),title})}><ArtworkPreview art={fresh('coloring',id)}/><strong>{title}</strong></button>)}</div></section>
    <section className="studio-gallery"><h2>{name}’s gallery</h2>{loading?<p role="status">Opening your gallery…</p>:!gallery.length?<p>Your first masterpiece belongs here. Make something, then press Save artwork.</p>:<div className="template-grid">{gallery.map(item=><article key={item.id}><button disabled={paused} onClick={()=>open(item.data,item)}><ArtworkPreview art={item.data}/><strong>{item.data.title}</strong><small>{new Date(item.updatedAt).toLocaleDateString()} · Open & create</small></button>{parent&&<button className="text-button" disabled={busy} onClick={async()=>{if(!window.confirm(`Delete “${item.data.title}”? Download family records first to keep a copy.`))return;setBusy(true);try{await workspaceRequest({action:'delete-item',id:item.id,revision:item.revision,confirm:true});setGallery(items=>items.filter(i=>i.id!==item.id));}catch(e){setError(e instanceof Error?e.message:'Try again.');}finally{setBusy(false);}}}>Delete artwork</button>}</article>)}</div>}{hasMore&&<button className="secondary" disabled={busy} onClick={more}>{busy?'Opening…':'More masterpieces'}</button>}</section>
  </section>;
}
