'use client';
import {useEffect,useState} from 'react';
import {Plus,Save,Send,BookOpen,Trash2} from 'lucide-react';
import {workspaceCollection,workspaceRequest} from '@/lib/workspace-client';
import type {Quiz,WorkspaceItem,PublicAssignment} from '@/lib/workspace-content';
import type {PublicExplorer} from '@/lib/explorer-view';
const blank=()=>({prompt:'',answer:'',choices:[] as string[],hint:'',explanation:''});
export function ParentBuilder({profile,onAssigned}:{profile:PublicExplorer;onAssigned:()=>void}){
  const [sets,setSets]=useState<WorkspaceItem<Quiz>[]>([]),[title,setTitle]=useState('A little challenge'),[questions,setQuestions]=useState<Quiz['questions']>([blank()]),[editing,setEditing]=useState<WorkspaceItem<Quiz>|null>(null);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[assignments,setAssignments]=useState<PublicAssignment[]>([]);
  useEffect(()=>{const controller=new AbortController();Promise.all([workspaceCollection<WorkspaceItem<Quiz>>(profile.id,'sets',controller.signal),workspaceCollection<PublicAssignment>(profile.id,'assignments',controller.signal)]).then(([s,a])=>{setSets(s);setAssignments(a);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return ()=>controller.abort();},[profile.id]);
  async function run(task:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await task();}catch(e){setError(e instanceof Error?e.message:'Try again.');}finally{setBusy(false);}}
  function change(index:number,update:Partial<Quiz['questions'][number]>){setQuestions(rows=>rows.map((row,i)=>i===index?{...row,...update}:row));}
  function generate(form:HTMLFormElement){const f=new FormData(form),count=Number(f.get('count')),limit=Number(f.get('difficulty')),subtract=f.get('topic')==='subtraction';setEditing(null);setTitle(subtract?'Picnic subtraction':'Picnic addition');setQuestions(Array.from({length:count},(_,i)=>{const a=1+(i*3)%(limit-1),b=1+(i*7)%Math.max(1,limit-a);return {prompt:subtract?`There are ${a+b} berries. We share ${b}. How many are left?`:`We have ${a} berries and find ${b} more. How many altogether?`,answer:String(subtract?a:a+b),choices:[],hint:subtract?'Draw the berries and cross out the ones we shared.':'Use counters or make a drawing.',explanation:subtract?`${a+b} take away ${b} leaves ${a}.`:`${a} and ${b} make ${a+b}.`};}));}
  return <div className="parent-builder"><div className="section-heading"><div><span className="eyebrow">MADE BY YOU</span><h2>Parent Activity Builder</h2></div><BookOpen/></div><p>Create reusable questions, then send a personal quest to {profile.name}. Custom answers stay private until checked. These activities do not change curriculum mastery estimates.</p>
    {error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}
    <details className="builder-generator"><summary>Choose from CurioQuest’s activity library</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const result=await workspaceRequest<{draft:Quiz}>({action:'draft-set',profile:profile.id,subject:f.get('subject'),level:Number(f.get('level')),count:Number(f.get('count'))});setEditing(null);setTitle(result.draft.title);setQuestions(result.draft.questions);setMessage('Your draft is ready to review and personalize before saving.');});}}><div className="form-two"><label>Learning area<select name="subject"><option value="reading">Reading & phonics</option><option value="math">Numbers & mathematics</option><option value="logic">Patterns & reasoning</option></select></label><label>Challenge<select name="level"><option value="1">Gentle</option><option value="2">Growing</option><option value="3">Stretch</option></select></label><label>Up to this many questions<input name="count" type="number" required min={1} max={20} defaultValue={5}/></label></div><p>Uses {profile.grade==='prek'?'Pre-K':'Grade 1'} content suitable for a question-and-answer activity. Review it for your child.</p><button disabled={busy} className="secondary">Choose my draft</button></form></details>
    <details className="builder-generator"><summary>Start with a math activity</summary><form onSubmit={e=>{e.preventDefault();generate(e.currentTarget);}}><div className="form-two"><label>Activity<select name="topic"><option value="addition">Addition</option><option value="subtraction">Subtraction</option></select></label><label>Difficulty<select name="difficulty"><option value="5">Within 5</option><option value="10">Within 10</option><option value="20">Within 20</option></select></label><label>Questions<input name="count" type="number" min={1} max={20} defaultValue={5}/></label></div><button className="secondary">Create a draft</button></form></details>
    <form onSubmit={e=>{e.preventDefault();void run(async()=>{const result=await workspaceRequest<{item:WorkspaceItem<Quiz>}>({action:'save-set',id:editing?.id,revision:editing?.revision,data:{title,questions:questions.map(q=>({...q,choices:q.choices.map(c=>c.trim()).filter(Boolean)}))}});setEditing(result.item);setSets(rows=>[result.item,...rows.filter(s=>s.id!==result.item.id)]);setMessage('Activity set saved. Choose Assign below to send it to your explorer.');});}}>
      <label>Activity title<input value={title} maxLength={70} required onChange={e=>setTitle(e.target.value)}/></label>
      {questions.map((q,index)=><fieldset className="builder-question" key={index}><legend>Discovery {index+1}</legend><label>Question<textarea value={q.prompt} maxLength={350} required onChange={e=>change(index,{prompt:e.target.value})}/></label><div className="form-two"><label>Answer<input value={q.answer} maxLength={100} required onChange={e=>change(index,{answer:e.target.value})}/></label><label>Optional choices, one per line<textarea value={q.choices.join('\n')} onChange={e=>change(index,{choices:e.target.value.split('\n')})}/></label><label>Hint<input value={q.hint} maxLength={350} onChange={e=>change(index,{hint:e.target.value})}/></label><label>Explanation<input value={q.explanation} maxLength={500} onChange={e=>change(index,{explanation:e.target.value})}/></label></div><button type="button" className="text-button" disabled={questions.length===1||busy} onClick={()=>setQuestions(rows=>rows.filter((_,i)=>i!==index))}><Trash2 size={16}/>Remove question</button></fieldset>)}
      <div className="studio-actions"><button type="button" className="secondary" disabled={busy||questions.length>=20} onClick={()=>setQuestions(q=>[...q,blank()])}><Plus size={18}/>Add question</button><button className="primary" disabled={busy}><Save size={18}/>{busy?'Saving…':'Save activity set'}</button><button type="button" className="text-button" onClick={()=>{setEditing(null);setTitle('A little challenge');setQuestions([blank()]);}}>New draft</button></div>
    </form>
    <h3>Your reusable library</h3>{!sets.length&&<p>Save your first activity set above. You can assign it again whenever you like.</p>}
    <div className="parent-set-list">{sets.map(set=><section className="panel" key={set.id}><h3>{set.data.title}</h3><p>{set.data.questions.length} discoveries</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const result=await workspaceRequest<{item:PublicAssignment}>({action:'assign',profile:profile.id,setId:set.id,due:f.get('due')||null,badge:f.has('badge')});setAssignments(a=>[result.item,...a]);setMessage(`Assigned to ${profile.name}. It is waiting on their home screen.`);onAssigned();});}}><label>Optional due date<input name="due" type="date"/></label><label className="check-label"><input name="badge" type="checkbox"/>Celebrate with a completion badge</label><div className="studio-actions"><button className="primary" disabled={busy}><Send size={17}/>Assign to {profile.name}</button><button type="button" className="secondary" disabled={busy} onClick={()=>{setEditing(set);setTitle(set.data.title);setQuestions(set.data.questions);}}>Edit set</button><button type="button" className="text-button" disabled={busy} onClick={()=>{if(window.confirm('Delete this reusable set? Already assigned copies will stay.'))void run(async()=>{await workspaceRequest({action:'delete-item',id:set.id,revision:set.revision,confirm:true});setSets(rows=>rows.filter(row=>row.id!==set.id));if(editing?.id===set.id)setEditing(null);});}}>Delete set</button></div></form></section>)}</div>
    <h3>Assigned to {profile.name}</h3>{assignments.map(a=><div className="assignment-status" key={a.id}><span><strong>{a.title}</strong><small>{a.completedAt?'Complete':`${a.index}/${a.total} discoveries`}{a.due?` · Due ${a.due}`:''}</small></span><button className="secondary" disabled={busy} onClick={()=>{if(window.confirm(`Restart “${a.title}”? Its assignment answers will reset. Curriculum progress stays.`))void run(async()=>{const result=await workspaceRequest<{item:PublicAssignment}>({action:'replay-assignment',id:a.id,revision:a.revision,profile:profile.id,confirm:true});setAssignments(list=>list.map(x=>x.id===a.id?result.item:x));onAssigned();});}}>Replay</button><button className="text-button" disabled={busy} onClick={()=>{if(window.confirm(`Remove “${a.title}” from this explorer? This removes its assignment record, not curriculum progress.`))void run(async()=>{await workspaceRequest({action:"delete-item",id:a.id,revision:a.revision,confirm:true});setAssignments(rows=>rows.filter(row=>row.id!==a.id));onAssigned();});}}>Remove</button></div>)}
  </div>;
}
