'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Volume2} from 'lucide-react';
import {workspaceCollection,workspaceRequest} from '@/lib/workspace-client';
import type {PublicAssignment} from '@/lib/workspace-content';
import {readAloud} from '@/lib/speech';
import {celebrate} from '@/lib/audio';
export function ParentQuests({profileId,paused}:{profileId:string;paused:boolean}){
  const [items,setItems]=useState<PublicAssignment[]>([]),[active,setActive]=useState<PublicAssignment|null>(null),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState('');
  useEffect(()=>{const controller=new AbortController();workspaceCollection<PublicAssignment>(profileId,'assignments',controller.signal).then(setItems).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[profileId]);
  async function refresh(){setBusy(true);try{const rows=await workspaceCollection<PublicAssignment>(profileId,'assignments');setItems(rows);setActive(current=>rows.find(row=>row.id===current?.id)??null);setError('');setAnswer('');setFeedback('Your saved place is ready.');}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
  async function submit(value:string){if(!active||busy)return;setBusy(true);setError('');try{const result=await workspaceRequest<{item:PublicAssignment;feedback:string;correct:boolean}>({action:'answer-assignment',profile:profileId,id:active.id,revision:active.revision,answer:value});setActive(result.item);setItems(rows=>rows.map(row=>row.id===active.id?result.item:row));setFeedback(result.feedback);setAnswer('');if(result.correct)celebrate(!!result.item.completedAt);}catch(e){setError(e instanceof Error?e.message:'Try again.');}finally{setBusy(false);}}
  if(!items.length&&!error)return null;
  return <section className="parent-quests"><span className="eyebrow">A QUEST MADE JUST FOR YOU</span><h2>Your grown-up has an adventure for you</h2>{error&&<div className="error" role="alert">{error}<button className="secondary" disabled={busy} onClick={refresh}>Refresh my saved place</button></div>}
    {active?<div className="personal-challenge"><button className="text-button" disabled={busy} onClick={()=>{setActive(null);setFeedback('');}}><ArrowLeft size={18}/>Back to my quests</button><h3>{active.title}</h3>{active.question?<><p className="eyebrow">Discovery {active.index+1} of {active.total}</p><h2>{active.question.prompt}</h2><button className="read-button" onClick={()=>readAloud(active.question!.prompt)}><Volume2 size={18}/>Read it to me</button>{active.question.choices.length?<div className="answers">{active.question.choices.map(choice=><button disabled={busy||paused} key={choice} onClick={()=>submit(choice)}>{choice}</button>)}</div>:<form onSubmit={e=>{e.preventDefault();void submit(answer);}}><label>Your answer<input value={answer} maxLength={100} required onChange={e=>setAnswer(e.target.value)}/></label><button className="primary" disabled={busy||paused}>Try my answer<ArrowRight size={18}/></button></form>}{active.question.hint&&<button className="text-button" onClick={()=>setFeedback(active.question!.hint)}>Show a hint</button>}</>:<div className="assignment-complete"><span>{active.badge?'🏅':'🌟'}</span><h2>You finished your Parent Quest!</h2><p>Tell your grown-up about a discovery you made.</p></div>}<p role="status">{feedback}</p></div>:<div className="assignment-cards">{items.filter(a=>!a.completedAt).map(a=><button className="assignment-card" key={a.id} disabled={paused} onClick={()=>{setActive(a);setFeedback('');}}><span>🎒</span><strong>{a.title}</strong><small>{a.index?`Continue · ${a.index}/${a.total}`:`${a.total} discoveries`}{a.due?` · ${a.due}`:''}</small><ArrowRight size={20}/></button>)}{items.every(a=>a.completedAt)&&<p>All your Parent Quests are complete. Share what you learned! 🌟</p>}</div>}
  </section>;
}
