'use client';
import {useState} from 'react';
import type {PublicExplorer} from '@/lib/explorer-view';
import {arcadeGames} from '@/lib/arcade';
import {skillById} from '@/lib/skill-graph';
export function ParentControls({profile,busy,onAction}:{profile:PublicExplorer;busy:boolean;onAction:(body:Record<string,unknown>)=>Promise<unknown>}){
  const [message,setMessage]=useState('');const c=profile.controls;
  return <><details className="panel"><summary>Learning, access & sound</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const result=await onAction({action:'controls',controls:{age:f.get('age')?Number(f.get('age')):null,schoolGrade:f.get('schoolGrade'),priorities:f.getAll('priorities'),challenge:f.get('challenge'),questLength:f.get('questLength')?Number(f.get('questLength')):null,allowedDays:f.getAll('days').map(Number),bedtime:f.get('bedtime')||null,timeZone:f.get('timeZone'),faith:f.has('faith'),offline:f.has('offline'),audio:{effects:f.has('effects'),music:f.has('music'),musicVolume:Number(f.get('musicVolume')),narration:f.has('narration'),voiceVolume:Number(f.get('voiceVolume')),celebration:f.get('celebration'),sound:f.get('sound')}}});if(result)setMessage('Learning settings saved.');}}>
    <div className="form-two"><label>Age, optional<input name="age" type="number" min={3} max={12} defaultValue={c.age??''}/></label><label>School grade<select name="schoolGrade" defaultValue={c.schoolGrade}><option value="prek">Pre-K</option><option value="kindergarten">Kindergarten</option><option value="grade1">Grade 1</option><option value="grade2">Grade 2</option></select></label><label>Challenge<select name="challenge" defaultValue={c.challenge}><option value="adaptive">Follow skill evidence</option><option value="gentle">More gentle practice</option><option value="stretch">A little more challenge</option></select></label><label>Discoveries per quest<input name="questLength" type="number" min={3} max={15} placeholder="Use adventure length" defaultValue={c.questLength??''}/></label></div>
    <p className="form-note">School grade is a profile detail. The separate learning track currently offers Pre-K and Grade 1 content; older children can practice those skills without a grade restriction.</p>
    <fieldset><legend>Subject priorities</legend>{['reading','math','logic'].map(subject=><label className="check-label" key={subject}><input type="checkbox" name="priorities" value={subject} defaultChecked={c.priorities.includes(subject as 'reading')}/>{subject}</label>)}</fieldset>
    <fieldset><legend>Allowed days</legend><div className="day-options">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day,i)=><label className="check-label" key={day}><input type="checkbox" name="days" value={i} defaultChecked={c.allowedDays.includes(i)}/>{day}</label>)}</div></fieldset><div className="form-two"><label>Bedtime cutoff, optional<input name="bedtime" type="time" defaultValue={c.bedtime??''}/></label><label>Family time zone<input name="timeZone" required defaultValue={c.timeZone} placeholder="America/New_York"/></label></div>
    <label className="check-label"><input name="offline" type="checkbox" defaultChecked={c.offline}/>Offer real-world missions</label><label className="check-label"><input name="faith" type="checkbox" defaultChecked={c.faith}/>Enable Faith & Bible for this child</label>
    <fieldset><legend>Sound & celebrations</legend>{[['effects','Sound effects'],['music','Gentle background music'],['narration','Spoken instructions']].map(([key,label])=><label className="check-label" key={key}><input name={key} type="checkbox" defaultChecked={c.audio[key as 'effects']}/>{label}</label>)}<div className="form-two"><label>Music volume<input name="musicVolume" type="range" min={0} max={1} step={.05} defaultValue={c.audio.musicVolume}/></label><label>Voice volume<input name="voiceVolume" type="range" min={0} max={1} step={.05} defaultValue={c.audio.voiceVolume}/></label><label>Celebration style<select name="celebration" defaultValue={c.audio.celebration}>{['gentle','cheerful','energetic','minimal','silent'].map(v=><option key={v}>{v}</option>)}</select></label><label>Success sound<select name="sound" defaultValue={c.audio.sound}>{['bells','sparkle','cheer'].map(v=><option key={v}>{v}</option>)}</select></label></div></fieldset><button className="primary" disabled={busy}>Save learning settings</button>{message&&<p className="success" role="status">{message}</p>}
  </form></details><details className="panel reset-panel"><summary>Replay, reset & data</summary><p>Playing again is available from Game Zone. Resets below remove selected progress. Download family records first if you want a copy.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const target=f.get('target');const result=await onAction({action:target==='delete'?'delete-profile':'reset-progress',target,game:f.get('game'),skill:f.get('skill'),confirm:f.get('confirm')});if(result)setMessage('The selected change is saved.');}}><label>What would you like to reset?<select name="target"><option value="daily">Current Daily Quest (regenerate on next play)</option><option value="game">One game passport and saved missions</option><option value="story">Story chapter progress</option><option value="skill">One skill estimate</option><option value="rewards">Star balance</option><option value="all">All learning progress (artwork and assignments stay)</option><option value="delete">Delete this profile and its creations/assignments</option></select></label><label>Game, when resetting a game<select name="game">{arcadeGames.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label><label>Skill, when resetting a skill<select name="skill">{[...skillById.values()].map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Type {profile.name} to confirm<input name="confirm" autoComplete="off" required/></label><button className="secondary" disabled={busy}>Confirm selected change</button></form></details></>;
}
