'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,FlaskConical,Save,Volume2} from 'lucide-react';
import {experiments,type Experiment,type LabItem} from '@/lib/science-lab';
import {readAloud} from '@/lib/speech';
import {workspaceCollection,workspaceRequest} from '@/lib/workspace-client';
import type {WorkspaceItem} from '@/lib/workspace-content';
type Observation={experiment:string;item:string;prediction:string;reflection:string};
export function ScienceLab({profileId,paused,offline}:{profileId:string;paused:boolean;offline:boolean}){
  const [experiment,setExperiment]=useState<Experiment|null>(null),[item,setItem]=useState<LabItem|null>(null),[prediction,setPrediction]=useState(''),[tested,setTested]=useState(false),[reflection,setReflection]=useState(''),[notes,setNotes]=useState<WorkspaceItem<Observation>[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
  useEffect(()=>{const c=new AbortController();workspaceCollection<WorkspaceItem<Observation>>(profileId,'observations',c.signal).then(setNotes).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[profileId]);
  return <section className="science-lab"><div className="lab-hero"><span className="eyebrow">PIP’S DISCOVERY LAB</span><h1>What do you think<br/>will happen?</h1><p>Predict. Try. Observe. Explain.</p><span aria-hidden="true">🔬 🌱 🧲</span></div>{error&&<p className="error" role="alert">{error}</p>}
    {!experiment?<><div className="story-shelf">{experiments.map(e=><button key={e.id} disabled={paused} onClick={()=>{setExperiment(e);setItem(null);setPrediction('');setTested(false);}}><span>{e.emoji}</span><h2>{e.title}</h2><p>{e.items.length} things to investigate →</p></button>)}</div><h2 className="notebook-title">Your observation notebook</h2>{notes.length?<div className="notebook-grid">{notes.map(n=>{const e=experiments.find(x=>x.id===n.data.experiment),i=e?.items.find(x=>x.id===n.data.item);return <article className="panel" key={n.id}><span>{i?.emoji}</span><h3>{i?.name}</h3><p>I predicted: {n.data.prediction}</p><p>I observed: {i?.result}</p>{n.data.reflection&&<p>My idea: {n.data.reflection}</p>}</article>;})}</div>:<p>Save a discovery and it will appear here. A surprising result is useful evidence!</p>}</>:<section className="experiment-bench"><button className="text-button" onClick={()=>setExperiment(null)}><ArrowLeft size={18}/>All experiments</button><h2>{experiment.title}</h2><p>Choose something to investigate.</p><div className="lab-items">{experiment.items.map(i=><button disabled={busy||paused} key={i.id} aria-pressed={item?.id===i.id} onClick={()=>{setItem(i);setPrediction('');setTested(false);setReflection('');setSaved(false);}}><span>{i.emoji}</span>{i.name}</button>)}</div>
      {item&&<><h3>1. Predict</h3><p>{experiment.question}</p><div className="game-filters">{experiment.outcomes.map(outcome=><button disabled={tested||paused} aria-pressed={prediction===outcome} key={outcome} onClick={()=>setPrediction(outcome)}>{outcome}</button>)}</div><h3>2. Try</h3><div className={`experiment-stage lab-${experiment.id} ${tested?'tested':''}`}><span data-result={item.result} className={`experiment-object ${tested&&item.result==='Sink'?'sinks':''}`}>{item.emoji}</span>{experiment.id==='float'&&<div className="water-line"/>}{tested&&<strong>{item.result}</strong>}</div><button className="primary" disabled={!prediction||tested||paused} onClick={()=>setTested(true)}><FlaskConical size={20}/>Try it in our model</button>
      {tested&&<><h3>3. Observe</h3><p className="lab-observation">{item.observation}</p><p>{prediction===item.result?'Your prediction matched what happened.':'A different result helps us learn. Scientists change their ideas when they find new evidence.'}</p><button className="read-button" onClick={()=>readAloud(item.observation)}><Volume2 size={18}/>Listen</button><h3>4. Explain</h3><p>{experiment.explain}</p><label>Your idea, or tell a grown-up<textarea disabled={busy||saved||paused} value={reflection} maxLength={500} onChange={e=>setReflection(e.target.value)}/></label><button className="primary" disabled={busy||saved||paused} onClick={async()=>{setBusy(true);setError('');try{const result=await workspaceRequest<{item:WorkspaceItem<Observation>}>({action:'save-observation',profile:profileId,data:{experiment:experiment.id,item:item.id,prediction,reflection}});setNotes(n=>[result.item,...n]);setSaved(true);}catch(e){setError(e instanceof Error?e.message:'Try again.');}finally{setBusy(false);}}}><Save size={18}/>{saved?'Saved in your notebook':'Save my discovery'}</button>{offline&&<aside className="offline-lab"><h3>Try it together</h3><p>{experiment.offline}</p><small>This on-screen model simplifies the real world. Compare with careful observation.</small></aside>}</>}</>}
    </section>}
  </section>;
}
