'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Volume2,Pause,RotateCcw} from 'lucide-react';
import type {Story} from '@/lib/story-library';
import {readAloud} from '@/lib/speech';
import {celebrate} from '@/lib/audio';
import {PrayerJournal} from './prayer-journal';
type Prayer={id:string;title:string;emoji:string;lines:string[]};
type Library={stories:Story[];prayers:Prayer[];progress:{storyId:string;scene:number;completedAt:string|null}[];error?:string};
export function StoryWorld({profileId,faith,paused}:{profileId:string;faith:boolean;paused:boolean}){
  const [library,setLibrary]=useState<Library|null>(null),[selected,setSelected]=useState<Story|null>(null),[page,setPage]=useState(0),[response,setResponse]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[prayer,setPrayer]=useState<Prayer|null>(null),[line,setLine]=useState(0),[mode,setMode]=useState('together');
  useEffect(()=>{const controller=new AbortController();fetch(`/api/stories?profile=${encodeURIComponent(profileId)}`,{signal:controller.signal}).then(async r=>{const data=await r.json() as Library;if(!r.ok)throw Error(data.error);setLibrary(data);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>{controller.abort();window.speechSynthesis?.cancel();};},[profileId]);
  async function turn(next:number){if(!selected||busy)return;setBusy(true);setError('');window.speechSynthesis?.cancel();try{const r=await fetch('/api/stories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:profileId,story:selected.id,scene:next}),signal:AbortSignal.timeout(20000)});const data=await r.json() as {error?:string;progress:Library['progress'][number]};if(!r.ok)throw Error(data.error);setPage(next);setResponse('');if(next===selected.scenes.length)celebrate(true);setLibrary(l=>l&&({...l,progress:[...l.progress.filter(p=>p.storyId!==selected.id),data.progress]}));}catch(e){setError(e instanceof Error?e.message:'Try again.');}finally{setBusy(false);}}
  const scene=selected?.scenes[page];
  return <section className={`story-world ${faith?'faith-world':''}`}><div className="story-world-heading"><span className="eyebrow">{faith?'FAITH & BIBLE':'NOVA’S STORY HARBOR'}</span><h1>{faith?'Stories of love. Moments of peace.':'Little stories. Big conversations.'}</h1><p>{faith?'Read, wonder, and pray together.':'Listen, choose, and share your ideas.'}</p></div>{error&&<p className="error" role="alert">{error}</p>}
    {!library&&!error&&<p role="status">Opening the bookshelf…</p>}
    {selected?<article className="scene-book" data-scene={page}><button className="text-button" disabled={busy} onClick={()=>{setSelected(null);setResponse('');window.speechSynthesis?.cancel();}}><ArrowLeft size={18}/>Bookshelf</button><h2>{selected.title}</h2>{scene?<><div key={`${selected.id}:${page}`} className={`scene-art ${['noah','jonah','moses'].includes(selected.id)?'scene-ocean':['creation','abraham','nativity','easter'].includes(selected.id)?'scene-space':['crayons','bridge-friends','children','loaves'].includes(selected.id)?'scene-home':'scene-garden'}`} aria-hidden="true"><span>{scene.emoji}</span><i>✦</i><i>✧</i></div><span className="eyebrow">Scene {page+1} of {selected.scenes.length}</span><h3>{scene.title}</h3><p className="scene-text">{scene.text}</p><div className="story-audio"><button className="secondary" onClick={()=>readAloud(scene.text)}><Volume2 size={18}/>Read this page</button><button className="secondary" onClick={()=>window.speechSynthesis?.paused?window.speechSynthesis.resume():window.speechSynthesis?.pause()}><Pause size={17}/>Pause / resume</button></div><div className="scene-question"><h3>{scene.prompt}</h3><div>{scene.choices.map(choice=><button className="secondary" key={choice.label} disabled={paused} onClick={()=>{setResponse(choice.response);}}>{choice.label}</button>)}</div><p role="status">{response}</p></div><div className="studio-actions"><button className="secondary" disabled={!page||busy||paused} onClick={()=>turn(page-1)}><ArrowLeft size={18}/>Previous</button><button className="primary" disabled={busy||paused||!response} onClick={()=>turn(page+1)}>{page===selected.scenes.length-1?'Our story discovery':'Next scene'}<ArrowRight size={18}/></button></div></>:<div className="story-ending"><span>🌟</span><h2>A story to take with you</h2><p>{selected.lesson}</p>{selected.prayer&&<p>{selected.prayer}</p>}<button className="primary" disabled={busy||paused} onClick={()=>turn(0)}><RotateCcw size={18}/>Read again</button></div>}{selected.reference&&<small className="story-source">An original child-friendly retelling based on {selected.reference}. Read and discuss with your family.</small>}</article>:<div className="story-shelf">{library?.stories.filter(s=>faith?s.category==='faith':s.category!=='faith').map(story=>{const progress=library.progress.find(p=>p.storyId===story.id);return <button disabled={paused} key={story.id} onClick={()=>{setSelected(story);setPage(progress&&!progress.completedAt?progress.scene:0);setResponse('');}}><span>{story.emoji}</span><small>{story.category==='character'?'KINDNESS & CHARACTER':story.category==='science'?'WONDER & SCIENCE':'BIBLE STORY'}</small><h2>{story.title}</h2><p>{progress?.completedAt?'Read again':progress?.scene?'Continue your story':'Open the story'} →</p></button>;})}</div>}
    {faith&&library&&<section className="prayer-garden"><h2>A quiet moment</h2><p>Prayer can be spoken, read together, or held quietly in your heart.</p><div className="game-filters">{library.prayers.map(p=><button key={p.id} onClick={()=>{setPrayer(p);setLine(0);window.speechSynthesis?.cancel();}}>{p.emoji} {p.title}</button>)}</div>{prayer&&<div className="prayer-card"><span>{prayer.emoji}</span><h3>{prayer.title}</h3><label>How shall we pray?<select value={mode} onChange={e=>{setMode(e.target.value);window.speechSynthesis?.cancel();}}><option value="together">Read together</option><option value="narrated">Narrated prayer</option><option value="repeat">Repeat after me</option><option value="silent">Silent moment</option></select></label><p>{mode==='repeat'?prayer.lines[line]:prayer.lines.join('\n')}</p>{mode==='narrated'&&<button className="secondary" onClick={()=>readAloud(prayer.lines.join(' '))}><Volume2/>Listen</button>}{mode==='repeat'&&<div className="studio-actions"><button className="secondary" onClick={()=>readAloud(prayer.lines[line])}><Volume2/>Listen, then repeat</button><button className="secondary" onClick={()=>{setLine((line+1)%prayer.lines.length);window.speechSynthesis?.cancel();}}>Next line<ArrowRight/></button></div>}</div>}</section>}
    {faith&&library&&<PrayerJournal profileId={profileId} paused={paused}/>}
  </section>;
}
