'use client';
import {useEffect,useState} from 'react';
import {Compass,Map,Star,BookOpen,Shapes,Mountain,ArrowRight,Volume2,ChevronDown,Check,Flag,Lightbulb,X,ShieldCheck,Gift,Sparkles,Leaf,Home,ArrowLeft,LoaderCircle,Trophy,RefreshCw} from 'lucide-react';
const worlds=[{id:'reading',name:'Word Forest',skill:'Letters, sounds & stories',icon:BookOpen,color:'green',line:'Every word opens a new path.'},{id:'math',name:'Number City',skill:'Numbers, counting & math',icon:Shapes,color:'yellow',line:'Big ideas start with little numbers.'},{id:'logic',name:'Logic Mountain',skill:'Patterns, puzzles & thinking',icon:Mountain,color:'purple',line:'A little thinking. A big discovery.'}];
const worldName=(id:string)=>worlds.find(w=>w.id===id)?.name||'Daily Quest';
function speak(text:string){if(typeof window!=='undefined'&&'speechSynthesis'in window){window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.85;window.speechSynthesis.speak(u);}}
export default function HomePage(){const [profiles,setProfiles]=useState<any[]>([]),[pid,setPid]=useState('maya'),[view,setView]=useState('adventure'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[play,setPlay]=useState(false),[current,setCurrent]=useState<any>(null),[feedback,setFeedback]=useState<any>(null),[selected,setSelected]=useState(''),[gate,setGate]=useState(false),[gateValue,setGateValue]=useState(''),[parentOpen,setParentOpen]=useState(false),[saved,setSaved]=useState(false);
const p=profiles.find(x=>x.id===pid);const session=p?.session;const active=session&&session.index<session.total;const today=p?.history.filter((h:any)=>h.date.slice(0,10)===new Date().toISOString().slice(0,10)).length||0;
async function load(){setError('');try{const r=await fetch('/api/quest');const d:any=await r.json();if(!r.ok)throw Error(d.error);setProfiles(d.profiles);}catch(e:any){setError(e.message);}}
useEffect(()=>{load();},[]);
async function action(body:any){setBusy(true);setError('');try{const r=await fetch('/api/quest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,profile:pid})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setProfiles(ps=>ps.map(a=>a.id===pid?d.profile:a));return d;}catch(e:any){setError(e.message);return null;}finally{setBusy(false);}}
async function start(subject:string){if(busy||!p)return;const d=await action({action:'start',subject});if(d){setCurrent(d.profile.session.question);setFeedback(null);setSelected('');setPlay(true);return true;}return false;}
async function answer(value:string){if(busy||feedback?.correct)return;setSelected(value);const d=await action({action:'answer',session:session.id,question:current.id,answer:value});if(d)setFeedback(d.feedback);}
async function hint(){const d=await action({action:'hint',session:session.id,question:current.id});if(d)setFeedback(d.feedback);}
function next(){setFeedback(null);setSelected('');setCurrent(session.question);}
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'start_learning_quest',description:'Open a five-activity quest for the selected explorer.',inputSchema:{type:'object',properties:{world:{type:'string',enum:['daily','reading','math','logic']}},required:['world'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!['daily','reading','math','logic'].includes(input.world))throw Error('Unknown world');if(!p||busy)throw Error('Explorer not ready');const opened=await start(input.world);if(!opened)throw Error('Quest could not be opened');return {opened:true,world:input.world};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[pid,p,busy]);
const parent=()=>{if(parentOpen)setView('parent');else{setGate(true);setGateValue('');}};
return <div className="app-shell">
<aside className="sidebar" inert={play||gate}><a className="brand" href="/" aria-label="CurioQuest home"><span className="brand-icon"><Compass size={29}/></span><span>curio<span className="brand-q">quest</span><small>SMALL STEPS. BIG DISCOVERIES.</small></span></a><div className="explorer-switch"><span className="avatar">{pid==='maya'?'🦊':'🐰'}</span><label><span>YOUR EXPLORER</span><select aria-label="Choose explorer" value={pid} onChange={e=>{setPid(e.target.value);setPlay(false);setSaved(false);}}>{profiles.length?profiles.map(a=><option key={a.id} value={a.id}>{a.name} · {a.grade==='prek'?'Pre-K':'Grade 1'}</option>):<option>Loading…</option>}</select></label><ChevronDown size={16}/></div>
<nav aria-label="Main navigation"><button className={view==='adventure'?'nav-item active':'nav-item'} onClick={()=>setView('adventure')}><Compass/>My adventure</button><button className={view==='worlds'?'nav-item active':'nav-item'} onClick={()=>setView('worlds')}><Map/>My worlds</button><button className={view==='rewards'?'nav-item active':'nav-item'} onClick={()=>setView('rewards')}><Star/>Treasure chest{p?.stars>0&&<span className="nav-count">{p.stars}</span>}</button></nav>
<div className="sidebar-bottom"><div className="nova-note"><span className="fox">🦊</span><strong>A little curious?</strong><p>That’s where every great adventure begins.</p><span>— Nova, your quest guide</span></div><button className={view==='parent'?'nav-item active':'nav-item'} onClick={parent}><ShieldCheck/>Parent corner</button><small className="version">CurioQuest · First adventure edition</small></div></aside>
<div className="page-area" inert={play||gate}><header className="topbar"><div className="crumb"><Home size={16}/><span>/</span>{view==='adventure'?'My adventure':view==='worlds'?'My worlds':view==='rewards'?'Treasure chest':'Parent corner'}</div><div className="top-actions"><span className="star-pill"><Star size={17} fill="currentColor"/>{p?.stars||0} stars</span><button className="icon-button" title="Read a welcome" aria-label="Read a welcome" onClick={()=>speak(`Hello ${p?.name||'explorer'}! Ready for a little adventure? Choose your daily quest or explore a world.`)}><Volume2 size={20}/></button><span className="avatar mini">{pid==='maya'?'🦊':'🐰'}</span></div></header>
<main>{error&&<div className="error" role="alert">{error} <button onClick={load}>Try again</button></div>}
{!p?<div className="loading"><LoaderCircle className="spin"/> Opening your adventure…</div>:<>
{(view==='adventure'||view==='worlds')&&<><div className="page-heading"><div><div className="eyebrow">{view==='adventure'?'A LITTLE WONDER, EVERY DAY':'FOLLOW YOUR CURIOSITY'}</div><h1>{view==='adventure'?`Hey ${p.name}, let’s explore!`:'A world of possibilities.'}</h1><p>{view==='adventure'?'New things to learn. New things you can do.':'Pick a path. Make a discovery. Grow at your own pace.'}</p></div><div className="level-pill"><Sparkles size={19}/><span>Level {Math.floor(p.completed/3)+1}<small>{p.completed<3?'Curious Explorer':'Brave Explorer'}</small></span></div></div>
{view==='adventure'&&<section className="quest-banner"><img className="quest-art" src="/quest-island.webp" alt="A friendly fox explores a magical island with a forest, golden city, and purple mountains"/><div className="quest-copy"><span className="daily-label"><Flag size={15}/> YOUR DAILY QUEST</span><h2>The adventure<br/>starts with you.</h2><p>Follow Nova through a world of words,<br className="desktop"/> numbers, and clever little puzzles.</p><div className="quest-meta"><span>5 discoveries</span><span>About 8 minutes</span></div><button className="primary" disabled={busy} onClick={()=>start('daily')}>{active?'Continue my quest':today?'Play another quest':'Let’s go, explorer'}<ArrowRight size={19}/></button><div className="reward-caption"><Star size={14} fill="currentColor"/> Earn 10 stars for finishing your quest</div></div><span className="art-caption">YOUR NEXT DISCOVERY IS JUST AROUND THE BEND</span></section>}
<div className="content-grid"><div><div className="section-heading"><h2>{view==='worlds'?'Your learning worlds':'Where will you go today?'}</h2>{view==='adventure'&&<button className="text-button" onClick={()=>setView('worlds')}>All worlds <ArrowRight size={16}/></button>}</div><div className="worlds-grid">{worlds.map(w=><button key={w.id} disabled={busy} className={`world-card ${w.color}`} onClick={()=>start(w.id)}><div className="world-top"><span className="world-symbol"><w.icon size={35} strokeWidth={1.6}/></span><span className="world-tag">{w.id==='reading'?'READ':w.id==='math'?'COUNT':'THINK'}</span></div><h3>{w.name}</h3><p>{w.skill}</p><div className="world-progress"><span>Trail {p.skills[w.id].level} of 3</span><ArrowRight size={18}/></div><div className="progress-track"><span style={{width:`${p.skills[w.id].seen?Math.min(100,p.skills[w.id].seen/15*100):0}%`}}/></div></button>)}</div>
<section className="journey"><div className="section-heading"><h2>Your explorer journey</h2><span>{p.completed} quests complete</span></div><div className="journey-path">{[{label:'Get curious',n:0,icon:Compass},{label:'Keep exploring',n:3,icon:Leaf},{label:'Think bigger',n:6,icon:Lightbulb},{label:'Shine bright',n:9,icon:Star}].map((s,i)=><div className={`journey-stop ${p.completed>=s.n?'reached':''}`} key={s.label}><span><s.icon size={23}/></span><strong>{s.label}</strong><small>{i===0?'Your journey begins':`${s.n} quests`}</small></div>)}</div></section>
{view==='worlds'&&<div className="future-worlds"><strong>More worlds are on the horizon</strong><p>Discovery Lab, Maker Island, Heart Harbor, and Team Quests are part of the next chapter.</p></div>}</div>
<aside className="right-column"><section className="today-card"><div className="section-heading"><h3>A little progress</h3><span className="sun-icon">☀</span></div><p>Small steps add up.</p><div className="daily-progress"><span className="ring"><Check size={24}/></span><div><strong>{today>0?'You explored today!':'A fresh start'}</strong><span>{today>0?`${today} quest${today===1?'':'s'} completed`:'Your first discovery awaits'}</span></div></div><div className="today-footer"><span><Star size={17}/>{p.stars} stars earned</span><span><Flag size={17}/>{p.completed} quests</span></div></section><section className="nova-card"><div className="nova-card-title"><span>🦊</span><div><strong>A note from Nova</strong><small>YOUR FRIENDLY GUIDE</small></div></div><p>“You don’t have to know the answer yet. Let’s figure it out together!”</p><button className="text-button" onClick={()=>speak('You don’t have to know the answer yet. Let’s figure it out together!')}><Volume2 size={17}/> Listen to Nova</button></section><div className="gentle-note"><Leaf size={17}/><span>No rush. No races.<br/>Just your kind of adventure.</span></div></aside></div></>}
{view==='rewards'&&<><div className="eyebrow">LOOK HOW FAR YOU’VE COME</div><h1>Your treasure chest</h1><p className="lead">Every discovery is something to be proud of.</p><div className="reward-total"><Star size={48} fill="#f4bd46"/><div><strong>{p.stars}</strong><span>stars collected</span></div></div><div className="badge-grid">{[{name:'First discovery',n:1,icon:Compass},{name:'Trail finder',n:3,icon:Map},{name:'Brave thinker',n:6,icon:Lightbulb},{name:'Wonder seeker',n:9,icon:Trophy}].map(b=><div key={b.name} className={`badge-card ${p.completed>=b.n?'earned':''}`}><b.icon size={48}/><h3>{b.name}</h3><p>{p.completed>=b.n?'You earned this!':`${b.n} completed quests`}</p></div>)}</div><button className="primary" onClick={()=>setView('adventure')}>Back to my adventure <ArrowRight size={18}/></button></>}
{view==='parent'&&parentOpen&&<><div className="eyebrow">SUPPORT THEIR NEXT SMALL STEP</div><h1>Parent corner</h1><p className="lead">A clear view of {p.name}’s practice, without pressure.</p><div className="parent-grid"><section className="panel"><h2>Explorer profile</h2><form key={p.id} onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const d=await action({action:'profile',name:fd.get('name'),grade:fd.get('grade')});if(d)setSaved(true);}}><label>Explorer name<input name="name" defaultValue={p.name} required maxLength={24}/></label><label>Learning track<select name="grade" defaultValue={p.grade}><option value="prek">Pre-K · First discoveries</option><option value="grade1">Grade 1 · Growing explorers</option></select></label><p className="form-note">Changing tracks restarts the learning trails. Earned stars and quest history stay.</p><button className="primary" disabled={busy}>Save profile <Check size={17}/></button>{saved&&<p role="status" className="success">Profile saved.</p>}</form></section><section className="panel"><h2>Learning snapshot</h2>{worlds.map(w=>{const s=p.skills[w.id];return <div key={w.id} className="skill-row"><w.icon size={21}/><div><strong>{w.name}</strong><small>{s.seen} activities practiced · Trail {s.level}</small></div><b>{s.seen?Math.round(s.first/s.seen*100)+'%':'—'}</b></div>})}<p className="form-note">Percentages show correct answers on the first try without hints. These are practice signals, not mastery scores or an assessment.</p></section><section className="panel"><h2>Recent adventures</h2>{p.history.length?p.history.slice(0,6).map((h:any,i:number)=><div className="history-row" key={i}><span><strong>{worldName(h.subject)}</strong><small>{new Date(h.date).toLocaleDateString()} · {h.grade==='prek'?'Pre-K':'Grade 1'}</small></span><span>{h.first}/5 independently</span></div>):<p>Your child’s completed quests will appear here.</p>}</section><section className="panel"><h2>Make room for wonder</h2><p>After a short quest, ask: “What did you discover?” Try counting toys together or finding a word that starts with today’s sound.</p><h3>About this first edition</h3><p>108 activities across two tracks. Nova uses written hints and your browser’s read-aloud voice. There is no open-ended AI chat, advertising, or leaderboard.</p><p className="form-note">This is your private family workspace. The grown-up question is a child-friendly gate, not a security password. Keep the site private while it stores child profiles.</p></section></div></>}
</>}
<footer><span className="footer-brand"><Compass size={15}/> A little curiosity goes a long way.</span><span>Learn. Think. Build. Explore.</span></footer></main></div>
{gate&&<div className="overlay"><section className="gate panel" role="dialog" aria-modal="true" aria-label="Grown-up check"><button className="close" aria-label="Close" onClick={()=>setGate(false)}><X/></button><ShieldCheck size={35}/><h2>A moment for grown-ups</h2><p>Ask a grown-up to answer: what is 12 × 3?</p><form onSubmit={e=>{e.preventDefault();if(gateValue==='36'){setParentOpen(true);setGate(false);setView('parent');}else setGateValue('');}}><input autoFocus aria-label="Grown-up answer" inputMode="numeric" value={gateValue} onChange={e=>setGateValue(e.target.value)} required placeholder="Your answer"/><button className="primary">Open parent corner <ArrowRight size={17}/></button></form></section></div>}
{play&&p&&<div className="play-overlay" role="dialog" aria-modal="true" aria-label="Learning quest"><header className="play-header"><button className="text-button" onClick={()=>{setPlay(false);window.speechSynthesis?.cancel();}}><ArrowLeft size={20}/> Back to adventure</button><span className="play-world">{worldName(session.subject)}</span><span className="star-pill"><Star size={16}/> {p.stars} stars</span></header>{error&&<div className="error" role="alert">{error}</div>}{current?<div className="activity"><div className="activity-progress"><span>Discovery {Math.min(session.index+(feedback?.correct?0:1),5)} of 5</span><div>{[0,1,2,3,4].map(i=><span key={i} className={i<session.index?'done':''}/>)}</div></div><div className="activity-category">{worldName(current.subject)} · {p.grade==='prek'?'Pre-K':'Grade 1'}</div><h1>{current.prompt}</h1><button className="read-button" onClick={()=>speak(current.prompt+'. '+(current.visual||'')+'. Your choices are: '+current.options.join(', '))}><Volume2 size={20}/> Read it to me</button>{current.visual&&<div className="activity-visual">{current.visual}</div>}<div className="answers">{current.options.map((o:string)=><button key={o} disabled={busy||feedback?.correct} className={selected===o?(feedback?.correct?'correct':'chosen'):''} onClick={()=>answer(o)}>{o}{selected===o&&feedback?.correct&&<Check size={24}/>}</button>)}</div><div className={`feedback ${feedback?.correct?'positive':''}`} aria-live="polite"><span className="fox">🦊</span><div><strong>{feedback?.correct?'You figured it out!':'Nova is here to help'}</strong><p>{feedback?.message||feedback?.hint||'Take your time. You can try, think, and try again.'}</p>{feedback?.hint&&feedback.message&&<p>{feedback.hint}</p>}</div></div><div className="activity-actions">{feedback?.correct?<button className="primary" onClick={next}>{session.index===session.total?'Finish my quest':'Next discovery'}<ArrowRight size={20}/></button>:<button className="text-button" disabled={busy} onClick={hint}><Lightbulb size={19}/> Give me a hint</button>}</div></div>:<div className="completion"><span className="celebration"><Trophy size={65}/></span><div className="eyebrow">LOOK WHAT YOU DID</div><h1>Quest complete, {p.name}!</h1><p>You read, thought, and kept exploring.<br/>That’s how your brain grows.</p><span className="big-reward"><Star fill="currentColor"/> +10 stars</span><p className="break-note">Now is a lovely time to stretch or share a discovery with a grown-up.</p><button className="primary" onClick={()=>setPlay(false)}>Back to my adventure <ArrowRight size={19}/></button></div>}</div>}
</div>;
}
