export type Subject='reading'|'math'|'logic';
export type Question={id:string;subject:Subject;grade:string;level:number;prompt:string;visual?:string;options:string[];answer:string;hint:string;explanation:string};
export const questions:Question[]=[];
function add(grade:string,subject:Subject,level:number,prompt:string,answer:string,wrong:string[],hint:string,explanation:string,visual?:string){const id=`${grade}-${subject}-${questions.filter(q=>q.grade===grade&&q.subject===subject).length}`;const options=[answer,...wrong];const rotate=questions.length%options.length;questions.push({id,grade,subject,level,prompt,answer,options:[...options.slice(rotate),...options.slice(0,rotate)],hint,explanation,visual});}
const sounds=[['sun','s','m','t'],['moon','m','s','p'],['fish','f','b','s'],['dog','d','c','m'],['ball','b','f','t'],['top','t','s','m']];
sounds.forEach(([word,a,b,c])=>add('prek','reading',1,`Which letter starts the word “${word}”?`,a,[b,c],`Say “${word}” slowly. Listen to the first sound.`,`“${word}” starts with ${a}.`,word));
const rhymes=[['cat','hat','sun','dog'],['log','dog','fish','bed'],['sun','fun','cat','pig'],['hen','pen','top','cup'],['bug','rug','dog','fan'],['hop','top','sun','bed']];
rhymes.forEach(([w,a,b,c])=>add('prek','reading',2,`Which word rhymes with “${w}”?`,a,[b,c],`Rhyming words have the same ending sound. Say each word aloud.`,`“${w}” and “${a}” share the same ending sound.`,w));
[['A','a','b','d'],['M','m','n','w'],['S','s','c','z'],['B','b','d','p'],['T','t','f','l'],['R','r','n','h']].forEach(([w,a,b,c])=>add('prek','reading',3,`Find the lowercase partner for ${w}.`,a,[b,c],`A letter can have an uppercase and a lowercase shape.`,`Uppercase ${w} and lowercase ${a} are the same letter.`,w));
[['c • a • t','cat','cap','can'],['s • u • n','sun','sit','sad'],['d • o • g','dog','dig','dot'],['p • i • g','pig','pin','pan'],['h • e • n','hen','hat','hop'],['b • u • s','bus','bat','bin']].forEach(([v,a,b,c])=>add('grade1','reading',1,'Blend the sounds. What is the word?',a,[b,c],'Say each sound, then slide the sounds together.',`The sounds blend together to make “${a}”.`,v));
[['Which word begins with the /sh/ sound?','ship','chip','sip'],['Which word ends with /ch/?','much','mush','mud'],['Which word has the long a sound?','cake','cat','cap'],['Which word has the long i sound?','bike','big','bit'],['Which word has the long o sound?','home','hot','hop'],['Which word begins with /th/?','thin','tin','fin']].forEach(([p,a,b,c])=>add('grade1','reading',2,p,a,[b,c],'Read each word aloud and listen for the sound.',`“${a}” has the sound we are looking for.`));
[['Mia put a seed in soil. She watered it. A sprout grew. What grew?','A sprout','A rock','A cup'],['The dog ran to the pond to get a drink. Why did the dog go to the pond?','It was thirsty','It was sleepy','It was cold'],['Sam wore boots and took an umbrella. What was the weather probably like?','Rainy','Snowy and sunny','Very hot'],['First, Ben washed an apple. Then he cut it. Last, he ate it. What did Ben do first?','Washed the apple','Ate the apple','Cut the apple'],['Lea saw her friend drop some books. She helped pick them up. How was Lea being?','Helpful','Unkind','Angry'],['The bird gathered twigs and made a nest. What were the twigs for?','Building a nest','Making a meal','Washing its wings']].forEach(([p,a,b,c])=>add('grade1','reading',3,p,a,[b,c],'Listen to the story again. Look for a clue that supports your answer.',`The story gives us a clue: ${a.toLowerCase()}.`));
for(let i=0;i<18;i++){const level=Math.floor(i/6)+1;const n=i%6+1;if(level===1)add('prek','math',level,'How many stars can you count?',String(n),[String(n+1),String(n+2)],'Touch each star once as you count.',`There are ${n} stars. The last number you say tells how many.`,'★ '.repeat(n));else if(level===2)add('prek','math',level,`Which number is bigger: ${n} or ${n+2}?`,String(n+2),[String(n),String(n+1)],'Count up. A number you say later is bigger.',`${n+2} is more than ${n}.`,`${n}   •   ${n+2}`);else add('prek','math',level,`You have ${n} blocks and get 1 more. How many now?`,String(n+1),[String(n),String(n+2)],`Start at ${n} and count one more.`,`${n} and 1 more make ${n+1}.`,`${n} + 1 = ?`);
const a=level===1?n:level===2?n+6:n+10;const b=level===1?2:level===2?3:1;const answer=level===2?a-b:level===3?10+n:a+b;const prompt=level===1?`Nova has ${a} gems and finds ${b} more. How many gems now?`:level===2?`There are ${a} birds. ${b} fly away. How many stay?`:`Which number has 1 ten and ${n} ones?`;add('grade1','math',level,prompt,String(answer),[String(answer+1),String(answer-1)],level===2?`Start at ${a}. Count back ${b}.`:level===3?'One ten is 10. Add the ones.':`Start at ${a}, then count ${b} more.`,level===2?`${a} − ${b} = ${answer}.`:level===3?`10 + ${n} = ${answer}.`:`${a} + ${b} = ${answer}.`,level===3?`1 ten + ${n} ones`: `${a} ${level===2?'−':'+'} ${b} = ?`);}
const patterns=[['●','▲'],['★','●'],['■','★'],['▲','■'],['♥','●'],['◆','▲']];
for(let i=0;i<18;i++){const level=Math.floor(i/6)+1;const [a,b]=patterns[i%6];add('prek','logic',level,'What comes next in the pattern?',level===2?b:a,[level===2?a:b,'◆◆'],level===1?'The two shapes take turns.':level===2?'The pattern is two of the first shape, then one of the second.':'Find the group of three that repeats.',`The repeating group is ${level===1?a+' '+b:level===2?a+' '+a+' '+b:a+' '+b+' '+b}.`,level===1?`${a} ${b} ${a} ${b} ?`:level===2?`${a} ${a} ${b} ${a} ${a} ?`:`${a} ${b} ${b} ${a} ${b} ${b} ?`);
if(level===1){const n=i+1;add('grade1','logic',level,'What number comes next?',String(n+6),[String(n+5),String(n+7)],'Count how much the number grows each time.','Add 2 each time to continue the pattern.',`${n}, ${n+2}, ${n+4}, ?`);}else if(level===2){const n=i-3;add('grade1','logic',level,`Nova is ${n} steps from home. Nova walks 2 steps toward home. How many steps are left?`,String(Math.max(0,n-2)),[String(n+2),String(n+1)],'Walking toward home makes the distance smaller.',n<2?'Nova reaches home after one step. There are no steps left.':`Taking away 2 steps leaves ${n-2}.`,`${n} steps → home`);}else{const entries=[['Put on socks → put on shoes → ?','Go for a walk','Take off socks','Wash your hair'],['A box holds only red blocks. Which block belongs?','Red block','Blue block','Green block'],['All birds in this puzzle have wings. Pip is a bird. What does Pip have?','Wings','Wheels','Leaves'],['You need a tall tower that stays up. What should you build first?','A wide base','A tiny top','A leaning wall'],['Ava is before Ben. Ben is before Cam. Who is first?','Ava','Cam','Ben'],['You have a red cup and a blue cup. The gem is not in the red cup. Where is it?','Blue cup','Red cup','Both cups']];const [p,ans,w1,w2]=entries[i-12];add('grade1','logic',level,p,ans,[w1,w2],'Use only the clues in the question. Rule out choices that do not fit.',`“${ans}” fits the clues in the puzzle.`);}}
export function publicQuestion(q:Question){const {answer,explanation,...safe}=q;return safe;}
