'use client';
import {useState} from 'react';
import {ArrowRight,Volume2} from 'lucide-react';
import {DoorMark} from '@/components/kid/Placeholder';
import type {RunMode,ExperienceView} from '@/lib/experience/types';
import {useExperience,ExperienceError} from './use-experience';
import {NovaCharacter,useNova} from '@/components/characters/NovaCharacter';
import {InteractiveMediaPlayer} from './InteractiveMediaPlayer';
import {SpaceCollector} from './SpaceCollector';
import {Treehouse} from './Treehouse';
import {ItemArt} from './ItemArt';
import {LetterCatch} from '@/components/reading/LetterCatch';
import {BlendTrain} from '@/components/reading/BlendTrain';
import {DecodableReader} from '@/components/reading/DecodableReader';
import {readAloud} from '@/lib/speech';
import {celebrate} from '@/lib/audio';
const names={episode:'Help Nova',blend:'Sound Bridge',collector:'Space Collector',story:'Tiny story',reward:'Discovery',treehouse:'My Treehouse',offline:'Out in the world'};
function SoundWarmup({data,busy,onAnswer}:{data:ExperienceView;busy:boolean;onAnswer:(answer:string)=>void}){
 const [taught,setTaught]=useState(false);const letter=data.letter!;
 return <div className="experience-warmup"><p>These sounds will help us on the map adventure.</p><LetterCatch activity={data.warmup!} skill={{...letter,letter:letter.letter as 'm',id:'sound_'+letter.letter,name:letter.letter,domain:'letter-sound',sequence:0,prerequisites:[]}} needsTeaching={!taught} busy={busy} onTeach={()=>setTaught(true)} onAnswer={onAnswer}/></div>;
}
function SoundSequence({choices,busy,onAnswer}:{choices:string[];busy:boolean;onAnswer:(s:string)=>void}){
 const [selected,setSelected]=useState<string[]>([]);
 return <div className="sequence-cue"><div className="sequence-slots" aria-live="polite">{[0,1,2].map(i=><span key={i}>{selected[i]??'·'}</span>)}</div><div className="letter-tiles">{choices.map(letter=><button key={letter} disabled={busy||selected.includes(letter)} onClick={()=>setSelected(s=>[...s,letter])}>{letter}</button>)}</div><button className="secondary" disabled={busy||!selected.length} onClick={()=>setSelected([])}>Try my sequence again</button><button className="primary" disabled={busy||selected.length!==3} onClick={()=>onAnswer(selected.join(''))}>Connect the sounds</button></div>;
}
export function DailyAdventure({profileId,mode='daily',onExit,onReading,onWorld,onStars}:{profileId:string;mode?:RunMode;onExit:()=>void;onReading:()=>void;onWorld:()=>void;onStars:(stars:number)=>void}){
 const {data,busy,error,act,refresh,pending}=useExperience(profileId,mode),nova=useNova('wave');
 async function action(name:string,extra:Record<string,unknown>={}){const next=await act(name,extra);if(next){onStars(next.stars);if(next.correct!==undefined){nova.play(next.correct?'celebrate':'encourage');if(next.correct)celebrate(false);}else if(name==='help')nova.play('point');else if(name==='place')nova.play('dance');}return next;}
 const run=data?.run,step=data?.step,media=data?.media.find(m=>m.id==='missing-map');
 return <section className="daily-adventure"><header className="adventure-toolbar"><button className="kid-activity-door" disabled={busy} aria-label="Save and take a break" onClick={onExit}><DoorMark/></button><span>{mode==='daily'?'Your trail':mode==='episode'?'The theatre':'Space collector'}</span><button className="text-button" onClick={onReading}>Reading Adventure</button></header><ExperienceError error={error} busy={busy} refresh={refresh} retry={pending?()=>{const {action:name,...extra}=pending;void action(String(name),extra);}:undefined}/>
 {!data?<p role="status">Nova is getting your trail ready…</p>:!run?<div className="adventure-welcome"><NovaCharacter state={nova.state} size="large"/><h1>A missing map. A world to discover.</h1><p>{mode==='daily'?'Help Nova, connect sounds, explore space, and bring a discovery home. About 8–12 minutes, with breaks whenever you need.':'A short playful mission. We’ll meet any sounds you need first.'}</p><button className="primary" disabled={busy} onClick={()=>action('start')}>Start my trail<ArrowRight size={20}/></button></div>:run.completedAt?<div className="adventure-complete"><NovaCharacter state="dance" size="large"/><h1>You changed your world.</h1><p>Your discoveries and your saved place are safe. Tell a grown-up something you noticed.</p><div className="completion-artifacts">{data.items.filter(i=>data.inventory.some(x=>x.item_id===i.id)).map(item=><div key={item.id}><ItemArt art={item.art}/><strong>{item.name}</strong></div>)}</div><div className="studio-actions"><button className="primary" onClick={onWorld}>Visit My World</button><button className="secondary" disabled={busy} onClick={()=>action('start')}>Explore again</button><button className="text-button" onClick={onExit}>Back to home</button></div></div>:<>
 <ol className="adventure-trail" aria-label="Adventure steps">{run.steps.map((s,i)=><li key={s} aria-current={i===run.index?'step':undefined} className={i<run.index?'complete':i===run.index?'current':''}><span>{i<run.index?'✓':i+1}</span><small>{names[s]}</small></li>)}</ol>
 {data.warmup?<SoundWarmup key={run.id+run.warmupIndex} data={data} busy={busy} onAnswer={response=>action('answer',{response})}/>:step==='episode'&&media?<InteractiveMediaPlayer key={run.id} media={media} scene={run.scene} time={run.time} cue={data.cue} busy={busy||!!error} onTick={time=>{void action('tick',{time});}} onNext={()=>{void action('next-scene');}}>{data.cue&&<><h3>{data.cue.prompt}</h3><button className="text-button" onClick={()=>readAloud(data.cue!.prompt)}><Volume2 size={18}/>Hear my mission</button>{data.cue.kind==='sequence'?<SoundSequence key={data.cue.id} choices={data.cue.choices} busy={busy} onAnswer={response=>action('answer',{response})}/>:data.cue.kind==='blend'&&data.word?<BlendTrain key={data.cue.id} word={data.word} activity={{id:data.cue.id,kind:'blend-train',skillId:data.cue.skillId,target:'map',choices:data.cue.choices,reason:'practice',taught:true}} busy={busy} onAnswer={response=>action('answer',{response})}/>:<div className="reading-word-choices">{data.cue.choices.map(answer=><button key={answer} disabled={busy} onClick={()=>action('answer',{response:answer})}>{answer}</button>)}</div>}</>}</InteractiveMediaPlayer>:step==='blend'&&data.word&&data.activity?<div className="adventure-activity"><BlendTrain word={data.word} activity={data.activity} busy={busy} onAnswer={response=>action('answer',{response})}/></div>:step==='collector'&&data.collector?<SpaceCollector key={run.id+run.round} round={data.collector} busy={busy} onAnswer={response=>action('answer',{response})} onHelp={()=>action('help')} help={run.help>0}/>:step==='story'&&data.story?<div className="adventure-activity"><DecodableReader story={data.story} page={run.page} busy={busy} onPage={()=>action('story-page')} onAnswer={response=>action('answer',{response})} onHelp={()=>action('help')}/></div>:step==='reward'?<div className="artifact-reveal"><NovaCharacter state="celebrate"/><ItemArt art="map"/><h2>Your Explorer Map</h2><p>You connected sounds, found words, and helped Nova. Let’s give your map a home.</p><button className="primary" disabled={busy} onClick={()=>action('claim')}>Take it to my treehouse<ArrowRight size={20}/></button></div>:step==='treehouse'?<Treehouse data={data} busy={busy} onPlace={(slot,item)=>{void action('place',{slot,item});}}/>:step==='offline'?<div className="offline-finish"><NovaCharacter state="wave"/><h2>Where can you hear the sound in moon?</h2><p>With your grown-up, find something that begins with /m/. Say its name together. Your Moon Lamp and Star Globe are already in your bag.</p><button className="primary" disabled={busy} onClick={()=>action('offline')}>Tell my grown-up I found something</button><button className="secondary" onClick={onWorld}>Visit my treehouse</button></div>:null}
 {data.feedback&&<div className="nova-feedback" role="status"><NovaCharacter state={nova.state} size="small"/><p>{data.feedback}</p></div>}
 {['episode','blend','collector','story'].includes(step??'')&&<div className="experience-help"><button className="secondary" disabled={busy||run.help>=4} onClick={()=>action('help')}>Nova, a little help</button><span>No rush. Your progress saves as you explore.</span></div>}
 </>}
 </section>;
}
