'use client';
import {useRef,useState} from 'react';
import {Rocket,ArrowLeft,ArrowRight} from 'lucide-react';
import {AudioButton} from '@/components/reading/AudioButton';
import type {CollectorRound} from '@/lib/experience/types';
export function SpaceCollector({round,busy,onAnswer,onHelp,help}:{round:Omit<CollectorRound,'target'>;busy:boolean;onAnswer:(answer:string)=>void;onHelp:()=>void;help:boolean}){
 const [lane,setLane]=useState(0),craft=useRef<HTMLDivElement>(null);
 const steer=(n:number)=>setLane(value=>(value+n+round.choices.length)%round.choices.length);
 return <section className="space-collector"><header><span className="eyebrow">SPACE COLLECTOR</span><h2>A little ship. A big discovery.</h2><p>{round.instruction}</p><AudioButton text={round.audioText} label="Hear my target"/><button className="text-button" disabled={busy} onClick={onHelp}>Show the target together</button>{help&&<p className="space-target">{round.audioText}</p>}</header><div className="collector-space" role="group" aria-label="Space lanes"><span className="collector-planet" aria-hidden="true"/><div className="collector-cards">{round.choices.map((choice,i)=><button className={i===lane?'selected':''} key={choice.id} disabled={busy} aria-label={`Steer to ${choice.label}`} aria-pressed={i===lane} onClick={()=>setLane(i)}><span>{choice.label}</span><small>STEER HERE</small></button>)}</div><div ref={craft} className="collector-craft" tabIndex={0} role="group" aria-label="Explorer craft. Left and right arrows steer. Enter collects." onKeyDown={e=>{if(busy)return;if(e.key==='ArrowLeft'){e.preventDefault();steer(-1);}if(e.key==='ArrowRight'){e.preventDefault();steer(1);}if(e.key==='Enter'||e.key===' '){e.preventDefault();onAnswer(round.choices[lane].id);}}}><Rocket style={{left:`${(lane+.5)*100/round.choices.length}%`}} size={55}/></div></div><div className="collector-controls"><button className="secondary" aria-label="Steer left" disabled={busy} onClick={()=>{steer(-1);craft.current?.focus({preventScroll:true});}}><ArrowLeft/></button><button className="primary" disabled={busy} onClick={()=>onAnswer(round.choices[lane].id)}>Collect {round.choices[lane].label}</button><button className="secondary" aria-label="Steer right" disabled={busy} onClick={()=>{steer(1);craft.current?.focus({preventScroll:true});}}><ArrowRight/></button><p>No timer. No lost lives. Listen, steer, and collect.</p></div></section>;
}
