'use client';
import {useState} from 'react';
import {Play,Heart} from 'lucide-react';
import {useExperience,ExperienceError} from './use-experience';
import {ItemArt} from './ItemArt';
import {CurioCharacter} from '@/components/characters/CurioCharacter';
export function Theater({profileId,onPlay}:{profileId:string;onPlay:()=>void}){
 const {data,busy,error,act,refresh}=useExperience(profileId),[filter,setFilter]=useState('all');
 const available=data?.media.filter(m=>m.active&&(filter==='all'||filter==='favorites'&&data.state.favoriteMedia.includes(m.id)||filter==='watched'&&data.state.watched.includes(m.id)))??[];
 return <section className="curio-theater"><ExperienceError error={error} refresh={refresh} busy={busy}/><header className="theater-marquee"><CurioCharacter state="wave"/><div><h1>Stories you can step into.</h1><p>Watch a little. Wonder a little. Help Nova change the story.</p></div></header><div className="world-tabs" role="group" aria-label="Theater filter">{[['all','For you'],['favorites','Favorites'],['watched','Watched']].map(([value,label])=><button key={value} aria-pressed={filter===value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{label}</button>)}</div>{!data?<p role="status">Raising the curtain…</p>:<><div className="theater-posters">{available.map(media=><article key={media.id} className="adventure-poster"><div className="poster-illustration"><CurioCharacter state="point"/><ItemArt art={media.thumbnail}/><span className="poster-letter">m a p</span></div><div><h2>{media.title}</h2><p>A lost map. Three glowing letters. One curious explorer—you.</p><div className="studio-actions"><button className="primary" onClick={onPlay}><Play size={20}/>{data.state.watched.includes(media.id)?'Play again':'Step into the story'}</button><button className="secondary" disabled={busy} aria-label="Favorite Nova and the Missing Map" aria-pressed={data.state.favoriteMedia.includes(media.id)} onClick={()=>act('favorite',{media:media.id})}><Heart fill={data.state.favoriteMedia.includes(media.id)?'currentColor':'none'}/></button></div></div></article>)}</div>{!available.length&&<p className="empty-inventory">No stories on this shelf yet. Choose “For you” to find Nova’s first adventure.</p>}<details className="story-workshop"><summary>Inside our story workshop</summary><p>These original stories have catalog records and reward plans, but are not playable episodes yet.</p><div>{data.media.filter(m=>!m.active).map(media=><article key={media.id}><ItemArt art={media.thumbnail}/><strong>{media.title}</strong><small>In development · {media.domain}</small></article>)}</div></details></>}
 </section>;
}
