'use client';
import {useState} from 'react';
import type {ExperienceView} from '@/lib/experience/types';
import {ItemArt} from './ItemArt';
import {NovaCharacter} from '@/components/characters/NovaCharacter';
export function Treehouse({data,busy,onPlace}:{data:ExperienceView;busy:boolean;onPlace:(slot:string,item:string|null)=>void}){
 const [selected,setSelected]=useState(''),[message,setMessage]=useState('');const earned=data.items.filter(item=>data.inventory.some(i=>i.item_id===item.id));
 return <section className="treehouse"><header><span className="eyebrow">MY TREEHOUSE</span><h2>A home for your discoveries.</h2><p>Choose an item, then choose a spot. Move it whenever you like.</p></header><div className="treehouse-room"><div className="treehouse-window"><span>☀</span></div><div className="treehouse-beam"/><div className="treehouse-floor"/><div className="treehouse-desk"/><div className="treehouse-shelf"/><div className="treehouse-nova"><NovaCharacter size="small" state={selected?'point':'idle'}/></div>{['wall','shelf','desk'].map(slot=>{const item=data.items.find(i=>i.id===data.placements.find(p=>p.slot===slot)?.item_id);return <div className={`room-spot spot-${slot}`} key={slot}><button className={selected?'ready':''} disabled={busy||!selected} aria-label={`Place selected item on ${slot}`} onClick={()=>{onPlace(slot,selected);setMessage(`Saving your ${data.items.find(i=>i.id===selected)?.name} on the ${slot}.`);}}>{item?<ItemArt art={item.art}/>:<span className="empty-spot">＋</span>}<small>{slot}</small></button>{item&&<button className="remove-item" disabled={busy} aria-label={`Return ${item.name} to inventory`} onClick={()=>onPlace(slot,null)}>Return to bag</button>}</div>;})}</div><p role="status">{data.feedback||message||'Three cozy spots. Every item belongs to you.'}</p><div className="inventory-heading"><h3>My discovery bag</h3><span>{earned.length} artifacts</span></div>{earned.length?<div className="world-inventory">{earned.map(item=><button aria-pressed={selected===item.id} className={selected===item.id?'selected':''} key={item.id} onClick={()=>{setSelected(item.id);setMessage(`Now choose a spot for your ${item.name}.`);}}><ItemArt art={item.art}/><strong>{item.name}</strong><small>{data.placements.some(p=>p.item_id===item.id)?'In your room':'Ready to place'}</small></button>)}</div>:<p className="empty-inventory">Your first artifact is waiting in Nova and the Missing Map. You never need to buy or grind for items.</p>}<details className="artifact-guide"><summary>Where discoveries come from</summary>{data.items.map(item=><p key={item.id}><strong>{item.name}</strong> · {item.unlock}</p>)}</details></section>;
}
