'use client';
import {useState} from 'react';
import {CurioCharacter} from '@/components/characters/CurioCharacter';
import {useExperience,ExperienceError} from './use-experience';
import {Treehouse} from './Treehouse';
import {readAloud} from '@/lib/speech';
export function WorldMap({profileId,name,onAdventure,onNavigate,onStars}:{profileId:string;name:string;onAdventure:()=>void;onNavigate:(view:string)=>void;onStars:(stars:number)=>void}){
 const {data,busy,error,act,refresh}=useExperience(profileId),[zone,setZone]=useState<'plaza'|'treehouse'|'grove'>('plaza'),[fact,setFact]=useState('');
 return <section className="my-world"><ExperienceError error={error} refresh={refresh} busy={busy}/><header className="experience-title"><h1>{name}’s little world</h1><p>Learn something. Make something. Watch your world grow.</p></header><nav className="world-tabs" aria-label="World areas">{(['plaza','treehouse','grove'] as const).map(z=><button className={zone===z?'active':''} aria-pressed={zone===z} onClick={()=>setZone(z)} key={z}>{z==='plaza'?'Central Plaza':z==='treehouse'?'My Treehouse':'Creature Grove'}</button>)}</nav>{!data?<p role="status">Opening your world…</p>:zone==='treehouse'?<Treehouse data={data} busy={busy} onPlace={(slot,item)=>{void act('place',{slot,item}).then(next=>{if(next)onStars(next.stars);});}}/>:zone==='grove'?<section className="creature-grove"><CurioCharacter state={fact?'explain':'wave'}/><h2>A quiet place to notice.</h2><p>Meet our visiting garden snail. No feeding timers or lost rewards.</p><button className="grove-creature" onClick={()=>{setFact('A snail carries its shell. Its soft body needs moisture, so watch it gently and leave it in its habitat.');readAloud('A snail carries its shell. Look gently and leave it in its habitat.');}} aria-label="Observe the garden snail"><span aria-hidden="true">🐌</span>Observe our visitor</button>{fact&&<p className="caption-layer">{fact}</p>}<button className="secondary" onClick={()=>onNavigate('science')}>Explore habitats in Discovery Lab</button></section>:<div className="world-plaza"><div className="plaza-cloud"/><CurioCharacter state="wave" size="large"/><h2>Where will curiosity take you?</h2><div className="plaza-portals"><button onClick={()=>setZone('treehouse')}><span className="portal-house" aria-hidden="true">⌂</span><strong>My Treehouse</strong><small>{data.inventory.length} discoveries in your bag</small></button><button onClick={onAdventure}><span aria-hidden="true">✦</span><strong>Today’s Adventure</strong><small>Follow a trail with Nova</small></button><button onClick={()=>setZone('grove')}><span aria-hidden="true">❧</span><strong>Creature Grove</strong><small>Observe a tiny neighbor</small></button></div></div>}</section>;
}
