import "server-only";
import type { DiscoveryLesson, DiscoveryTask, DiscoveryVersion } from "./types";

const choose = (prompt: string, choices: string[], answer: number, hint: string, explanation: string): DiscoveryTask => ({ kind: "choose", prompt, choices, answer: [answer], hint, explanation });
const sequence = (prompt: string, choices: string[], answer: number[], hint: string, explanation: string): DiscoveryTask => ({ kind: "sequence", prompt, choices, answer, hint, explanation });
const build = (prompt: string, answer: number, max: number, hint: string, explanation: string): DiscoveryTask => ({ kind: "build", prompt, choices: [], answer: [answer], max, unit: "counter", hint, explanation });
const version = (skillId: string, idea: string, example: string, notice: string, task: DiscoveryTask, talk: string, away: string): DiscoveryVersion => ({ skillId, idea, example, notice, task, talk, away });

/** Original, bounded mini-lessons. Answers remain in the server bundle. */
export const discoveryLessons: DiscoveryLesson[] = [
  {
    id: "story-trail", domain: "reading", title: "A story in order", subtitle: "Every little adventure has a beginning.", minutes: 4,
    vocabulary: { word: "sequence", meaning: "The order in which things happen." }, sourceIds: ["wwc-reading", "wwc-learning"], next: { label: "Visit the Reading Grove", href: "/read" },
    versions: {
      explorer: version("LIT.PK.COMP.RECALL_01", "Listen for what happens first and next.", "Pip puts on boots. Then Pip jumps in a puddle.", "What did Pip put on?", sequence("Put Pip's story in order.", ["Jump in the puddle", "Put on boots"], [1, 0], "The boots keep Pip's feet dry.", "Pip puts on boots before jumping in the puddle."), "Tell the story using first and then.", "With a grown-up, tell two things you did this morning, in order."),
      investigator: version("LIT.G1.COMP.SEQUENCE_01", "A story has events in an order. Words such as first, then and finally can help.", "Wren finds a seed. She plants it. Later, a shoot appears.", "What changes between the beginning and the end?", sequence("Build Wren's story.", ["A shoot appears", "Wren finds a seed", "Wren plants the seed"], [1, 2, 0], "She must find the seed before she plants it.", "Finding comes before planting. The shoot grows later."), "What would be confusing if we told the ending first?", "Draw three pictures of something you made. Tell someone the steps."),
      scientist: version("LIT.G1.COMP.CAUSE_01", "Order tells us when. Cause tells us why. Look for the event that made another happen.", "Rain soaks the path. Nova steps on the wet mud and slips. She chooses a dry path.", "Which event explains the slip?", sequence("Rebuild the chain of events.", ["Nova chooses a dry path", "Rain soaks the path", "Nova slips on wet mud"], [1, 2, 0], "Start with what made the ground slippery.", "Rain made the mud wet. The slip led Nova to choose a different path."), "Could Nova choose the dry path without slipping first? Explain.", "Retell a story you know. Explain why one event happened, using because."),
    },
  },
  {
    id: "word-detective", domain: "reading", title: "Word detective", subtitle: "Use a clue to unlock a new word.", minutes: 4,
    vocabulary: { word: "clue", meaning: "Something that helps you work out an idea." }, sourceIds: ["wwc-reading"], next: { label: "Find a story", href: "/stories" },
    versions: {
      explorer: version("LIT.PK.ORAL.WORD_01", "An action can help us understand a word.", "Nova whispers so the sleeping bird will not wake up.", "Try saying hello very quietly.", choose("What does whisper mean?", ["Speak quietly", "Shout loudly"], 0, "The bird is sleeping.", "To whisper is to speak very quietly."), "When might a whisper be helpful?", "Take turns whispering a kind message to a grown-up."),
      investigator: version("LIT.PK.ORAL.WORD_01", "The words around a new word can give a clue to its meaning.", "The enormous pumpkin was too big for Pip to carry alone.", "Which part tells you about its size?", choose("What does enormous mean here?", ["Very small", "Very big", "Very noisy"], 1, "Pip cannot carry it alone because of its size.", "Enormous means very big. Too big to carry gives us the clue."), "Make a sentence about an enormous object.", "Find something tiny and something enormous in a book. Explain each word."),
      scientist: version("LIT.G1.COMP.INFER_01", "An inference joins a clue with something you already know.", "Wren folded her dripping umbrella and left muddy boots by the door.", "What do wet umbrellas and muddy boots suggest?", choose("What most likely happened outside?", ["It rained", "It was very dry", "It snowed indoors"], 0, "Use both the dripping umbrella and the muddy boots.", "Rain explains both clues. The story does not say it directly, so this is an inference."), "Could a sprinkler explain one clue? Why are two clues stronger?", "Pause during a shared story. Say what you think will happen and name your clue."),
    },
  },
  {
    id: "picnic-count", domain: "math", title: "Pack a picnic", subtitle: "Make a collection, one at a time.", minutes: 3,
    vocabulary: { word: "total", meaning: "How many there are altogether." }, sourceIds: ["wwc-math"], next: { label: "Play with numbers", href: "/play" },
    versions: {
      explorer: version("MATH.PK.NUM.CARDINAL_01", "Touch each object once as you count. The last number tells how many.", "One plate, two plates, three plates. That is three plates altogether.", "Count three fingers, touching each one once.", build("Pack 3 counters for our picnic.", 3, 6, "Count each counter once. Stop at three.", "You made a set of three. Moving the counters would not change how many there are."), "Would spreading them out make more?", "Give one spoon to each of three toy guests. Count the spoons again."),
      investigator: version("MATH.G1.ADD.WITHIN10_01", "Joining two groups makes a new total.", "Two apples and three apples make five apples. We count every apple once.", "Show the two groups on your fingers.", build("We pack 4 apples, then 2 more. Build the total.", 6, 10, "Start with four counters. Add two more.", "Four and two make six: 4 + 2 = 6."), "Can you make the same total with two different groups?", "Draw six picnic snacks. Circle two groups and tell an addition story."),
      scientist: version("MATH.G1.ADD.WITHIN20_01", "Make a ten to help add. Split a group without changing its total.", "For 8 + 5, move 2 from the 5 to make 10. There are 3 left: 10 + 3 = 13.", "Why does moving two not change the total?", build("Build the total for 9 + 5.", 14, 20, "Move one from five to nine. Ten and four are left.", "Nine needs one to make ten. The other four make fourteen."), "Explain another way to work out 9 + 5.", "Use fourteen drawn dots. Show how 9 + 5 and 10 + 4 have the same total."),
    },
  },
  {
    id: "fair-share", domain: "math", title: "A fair share", subtitle: "Give every friend the same amount.", minutes: 4,
    vocabulary: { word: "equal", meaning: "The same amount." }, sourceIds: ["wwc-math"], next: { label: "Build with shapes", href: "/build" },
    versions: {
      explorer: version("MATH.PK.COMP.EQUAL_01", "Equal groups have the same number, even if they look different.", "Nova has two blocks. Pip has two blocks. They have equal groups.", "Show two fingers on each hand.", build("Nova has 2 counters. Make an equal group for Pip.", 2, 5, "Pip needs the same number as Nova.", "Both groups have two, so they are equal."), "What happens if Pip gets one more?", "Give two blocks to each of two toys. Pair their blocks to check."),
      investigator: version("MATH.PK.COMP.EQUAL_01", "You can share fairly by giving each friend one object at a time.", "Four berries shared between two friends gives two to each.", "Imagine giving one berry to each friend, then doing it again.", build("Share 6 berries between 2 friends. Build ONE friend's share.", 3, 6, "Give one to each friend until all six are shared.", "Each friend gets three. Three and three make all six berries."), "How can you check that none are left over?", "Share eight blocks between two toys. Check that both get the same number."),
      scientist: version("MATH.PK.COMP.EQUAL_01", "Equal sharing means every group has the same number and every object is used.", "Twelve counters shared among three friends gives four each: 4 + 4 + 4 = 12.", "How is sharing among three different from sharing between two?", build("Share 12 counters among 4 friends. Build ONE share.", 3, 12, "Deal one counter to each of four friends, then repeat.", "Each gets three. Four groups of three use all twelve counters."), "Would each share be bigger or smaller with only two friends? Why?", "Draw twelve dots. Circle four equal groups, then three equal groups."),
    },
  },
  {
    id: "seed-secret", domain: "science", title: "The seed's secret", subtitle: "Notice how a small beginning grows.", minutes: 5,
    vocabulary: { word: "seedling", meaning: "A young plant that has grown from a seed." }, sourceIds: ["ngss-plants", "wwc-learning"], next: { label: "Investigate in Wonder Lab", href: "/science" },
    versions: {
      explorer: version("SCI.PK.LIFE.NEEDS_01", "A seed can grow into a plant. A growing green plant needs water and light.", "A bean seed takes in water. A root comes out. Later, leaves open above the ground.", "Look for a root and a leaf on a plant with a grown-up.", choose("What helps a growing green plant?", ["Water and light", "Paint and stickers"], 0, "Think about what a plant needs, not what decorates its pot.", "Water and light help a green plant grow. Plants also need air, nutrients and suitable conditions."), "How could we notice that a plant has grown?", "With a grown-up, draw a plant today and again in a few days. Look for changes."),
      investigator: version("SCI.G1.LIFE.LIFECYCLE_01", "A plant changes in stages. A seedling is a young plant, not a different kind of plant.", "A bean begins as a seed, sprouts a root, grows leaves, then becomes a larger plant.", "Which part usually appears before the first leaves?", sequence("Put the growth stages in order.", ["Young plant with leaves", "Bean seed", "Root begins to grow"], [1, 2, 0], "Start before any root or leaf has appeared.", "The seed comes first, then a root begins to grow, then the young plant has leaves."), "Why should we observe over days rather than seconds?", "With a grown-up, observe a sprouting bean. Draw what you actually see each day."),
      scientist: version("SCI.G1.SCI.FAIRTEST_01", "A fair comparison changes one factor and keeps the others as similar as possible.", "To compare light, use the same kind of seedlings, similar pots, and the same water. Change only their light conditions.", "Why would using different amounts of water confuse the result?", choose("To test how light affects seedlings, what should differ?", ["Light only", "Light and water", "Seed type and pot size"], 0, "If two factors change, which one caused the difference?", "Changing only light makes the comparison easier to interpret. Use several similar plants and observe over time."), "What would you measure, and how often?", "Plan a plant comparison with a grown-up. Write what changes, what stays similar, and what you will observe."),
    },
  },
  {
    id: "shadow-play", domain: "science", title: "Catch a shadow", subtitle: "Follow the light. Find the shadow.", minutes: 4,
    vocabulary: { word: "opaque", meaning: "Not letting light pass through." }, sourceIds: ["ngss-light", "wwc-learning"], next: { label: "Explore light in Wonder Lab", href: "/science" },
    versions: {
      explorer: version("SCI.G1.PHYS.LIGHT_01", "A shadow appears where an object blocks light.", "Put a toy between a torch and a wall. The toy blocks some light and a shadow appears on the wall.", "Which part does not receive the torch's light?", choose("What makes the toy's shadow?", ["The toy blocks light", "The toy makes black paint"], 0, "Imagine the light trying to reach the wall.", "The toy blocks some light from reaching the wall. That darker place is its shadow."), "Can a shadow pick up a toy? Why not?", "With a grown-up, make a hand shadow using a torch. Keep light away from eyes."),
      investigator: version("SCI.G1.PHYS.LIGHT_01", "Some materials let light through. Opaque materials block it.", "Clear glass lets much light through. Cardboard blocks light and makes a dark shadow.", "Would you see clearly through cardboard?", choose("Which would make a dark shadow?", ["Clear window glass", "A sheet of cardboard", "Empty air"], 1, "Choose the material that blocks the light.", "Cardboard is opaque. It blocks light and makes a dark shadow."), "How could you compare two materials using the same torch?", "With a grown-up, compare paper and cardboard in a torch beam. Describe what you see."),
      scientist: version("SCI.G1.PHYS.LIGHT_01", "With the light and wall fixed, moving an object changes its shadow's size.", "Closer to a small torch, an object blocks a wider part of the spreading light. Its shadow on the wall grows.", "Which two things must stay still to test the object's position?", choose("Move a toy closer to the torch, with the wall fixed. Its shadow usually becomes…", ["Smaller", "Larger", "A different colour"], 1, "Light spreads out from the torch. Think about how much the toy blocks.", "The toy blocks a wider part of the spreading beam, so its shadow on the fixed wall becomes larger."), "How would you test this prediction fairly?", "With a grown-up, mark three toy positions between a torch and wall. Compare shadow sizes without moving the torch."),
    },
  },
  {
    id: "pattern-band", domain: "logic", title: "The pattern band", subtitle: "Find the little bit that repeats.", minutes: 3,
    vocabulary: { word: "repeat", meaning: "To do the same thing again." }, sourceIds: ["wwc-math", "harvard-play"], next: { label: "Make patterns in Build Yard", href: "/build" },
    versions: {
      explorer: version("LOGIC.PK.PATTERN.AB_01", "A repeating pattern has a little part that happens again and again.", "Clap, tap. Clap, tap. The repeating part is clap, tap.", "Try that pattern with a grown-up.", sequence("Clap, tap. Now build the next repeating part.", ["Tap", "Clap"], [1, 0], "The part begins with a clap.", "Clap then tap repeats the same two-action unit."), "What would come after one more clap?", "Make a two-action pattern with a grown-up. Let them copy it."),
      investigator: version("LOGIC.PK.PATTERN.AAB_01", "The repeating unit can have more than two parts.", "Clap, clap, tap. Clap, clap, tap. Each unit has three actions.", "Say the whole repeating unit, not just the last action.", sequence("Build one unit: clap, clap, tap.", ["Tap", "Second clap", "First clap"], [2, 1, 0], "There are two claps before each tap.", "Two claps followed by one tap make the unit. Repeat the entire unit to continue."), "How would your pattern sound if you changed the tap to a stomp?", "Make a repeating pattern using three safe movements. Ask someone to continue it."),
      scientist: version("LOGIC.G1.PATTERN.NUMBER_01", "Some number patterns use the same change each time.", "2, 4, 6, 8 adds two each time. The rule describes every step, not just one.", "Say what changes from 4 to 6 and from 6 to 8.", sequence("Continue 3, 5, 7 with the next three numbers.", ["13", "9", "11"], [1, 2, 0], "Keep adding two, beginning at seven.", "Seven plus two is nine, then eleven, then thirteen."), "Does the rule add two also work for 3, 5 and 7?", "Invent an add-two number trail. Leave a missing number for someone to find."),
    },
  },
  {
    id: "robot-plan", domain: "logic", title: "Think like a robot", subtitle: "Small steps. A clever plan.", minutes: 4,
    vocabulary: { word: "instruction", meaning: "A step that tells someone what to do." }, sourceIds: ["ngss", "harvard-play"], next: { label: "Program in Robot Garage", href: "/build" },
    versions: {
      explorer: version("LOGIC.PK.SEQUENCE.ROUTINE_01", "Some steps must happen before others.", "Open a box before putting a toy inside.", "What happens if the lid is still shut?", sequence("Help Pip put a toy in a closed box.", ["Put the toy inside", "Open the box"], [1, 0], "Pip cannot put the toy through a shut lid.", "Open the box first. Then there is a way to put the toy inside."), "Tell Pip how to take the toy out again.", "Give a grown-up two steps for putting a book in a bag."),
      investigator: version("LOGIC.PK.CODE.SEQUENCE_01", "A robot follows the instructions in the order you give them.", "To leave a closed room: open the door, walk through, then close the door behind you.", "Could the robot close the door before walking through?", sequence("Program Pip to leave the room.", ["Close the door behind you", "Open the door", "Walk through the doorway"], [1, 2, 0], "First make a space for Pip to walk through.", "Open, walk through, close. The order makes the plan work."), "Which instruction needs to be more precise for a real robot?", "Play robot with a grown-up. Give short, safe instructions and see what needs clarifying."),
      scientist: version("LOGIC.G1.CODE.DEBUG_01", "Debugging means finding and fixing a step that makes a plan go wrong.", "Pip's plan says: put a book in a closed bag, open the bag, zip it. The first step cannot work yet.", "What must happen before a book can go inside?", sequence("Fix the plan for packing the book.", ["Zip the bag", "Put the book inside", "Open the bag"], [2, 1, 0], "Find the first step whose starting conditions are not ready.", "Open the bag, put the book inside, then zip it. Testing the steps revealed the bug."), "How would you test the plan without skipping a step?", "Write or draw a three-step plan. Swap two steps and ask someone to debug it."),
    },
  },
  {
    id: "little-map", domain: "world", title: "Make a little map", subtitle: "A small picture of a bigger place.", minutes: 4,
    vocabulary: { word: "symbol", meaning: "A mark or picture that stands for something." }, sourceIds: ["wwc-learning"], next: { label: "Build in Map Maker", href: "/build" },
    versions: {
      explorer: version("WORLD.PK.PLACE.HOME_01", "A map can show places using little pictures.", "A book picture can mark the library. A tree picture can mark the park.", "What picture might stand for your home?", choose("Where could a book symbol lead us?", ["The library", "A swimming pool"], 0, "Where do people borrow books?", "A book symbol can stand for a library. The map's key tells us what each symbol means."), "Could a tree picture mean something else on another map?", "Draw a picture map of one room with a grown-up. Make a key for two symbols."),
      investigator: version("WORLD.PK.MAP.LANDWATER_01", "An island is land with water all around it. A lake is water with land around it.", "Imagine a little patch of land in the middle of a blue sea. That patch is an island.", "For an island, what must be all around the land?", choose("Which description is an island?", ["Water surrounded by land", "Land surrounded by water", "A road between houses"], 1, "Pay attention to which part is in the middle.", "An island is land surrounded by water. A lake reverses that relationship."), "How would you draw a lake and an island differently?", "Draw one island and one lake. Explain what surrounds each one."),
      scientist: version("WORLD.G1.MAP.DIRECTION_01", "A compass rose tells us directions. On a map with north at the top, east is right and west is left.", "If the library is east of the park, it is to the right of the park on this north-up map.", "Which way would you go to return from the library to the park?", choose("On a north-up map, a pond is west of your tent. Which way is it?", ["Right", "Above", "Left"], 2, "North is up, east is right. West is the opposite of east.", "West is left on this north-up map. Turning the paper does not change geographic directions."), "Why do we need to look for north before using the sides of the page?", "Draw a map with a north arrow. Place a tree east of a house and a pond west of it."),
    },
  },
  {
    id: "helpful-tools", domain: "world", title: "A tool for the job", subtitle: "Good ideas start with a problem.", minutes: 4,
    vocabulary: { word: "design", meaning: "A plan for how something will work." }, sourceIds: ["ngss"], next: { label: "Try an engineering build", href: "/build" },
    versions: {
      explorer: version("WORLD.PK.COMM.HELPERS_01", "People use tools to help with different jobs.", "A gardener uses a watering can to carry water to plants.", "How does the handle help the gardener?", choose("Which helps a gardener water a plant?", ["A cushion", "A watering can"], 1, "Choose something that can hold and pour water.", "A watering can holds water and helps pour it near a plant."), "Could a cup do the job too?", "With a grown-up, find a safe tool. Explain what job it helps with."),
      investigator: version("WORLD.G1.INVENT.TOOLS_01", "Choose a tool by the job it needs to do, not just by its colour or size.", "A spoon's bowl can hold liquid. A fork has gaps, so most liquid runs through.", "What part of the spoon helps it hold soup?", choose("Which is better for moving soup into your mouth?", ["A fork", "A ruler", "A spoon"], 2, "Look for a shape that holds liquid.", "A spoon has a bowl that holds some liquid. Its shape fits this job."), "What job would a fork do better than a spoon?", "Compare two safe kitchen tools with a grown-up. Explain why their shapes differ."),
      scientist: version("LOGIC.G1.ENGINEER.STABILITY_01", "Engineers define a problem, make a design, and test whether it works.", "A paper bridge must span a gap and hold a toy. Testing tells us where to improve it.", "What would count as a successful bridge?", sequence("Put the design process in a useful order.", ["Test the bridge with the toy", "Decide what the bridge must do", "Build a bridge"], [1, 2, 0], "Know the job before you build. A test needs something to test.", "Define the job, build, then test. You can use the result to improve and test again."), "If it bends, what one change could you try next?", "With a grown-up, bridge two books using paper. Test with a light toy, then change one part."),
    },
  },
  {
    id: "feelings-clues", domain: "wellbeing", title: "Feelings have clues", subtitle: "Notice. Wonder. Ask kindly.", minutes: 4,
    vocabulary: { word: "feeling", meaning: "An emotion, such as happiness, sadness or worry." }, sourceIds: ["harvard-play"], next: { label: "Share a story together", href: "/stories" },
    versions: {
      explorer: version("WELL.PK.EMOTION.NAME_01", "People can feel different things. We can ask how they feel.", "Wren says, 'I feel sad because my tower fell.' Nova listens.", "What feeling did Wren name?", choose("How does Wren say she feels?", ["Sad", "Happy"], 0, "Listen to Wren's own words about her feeling.", "Wren says she feels sad. We can listen and offer company without asking her to smile."), "What helps you when a plan does not work?", "With a trusted grown-up, name a feeling from today. You can choose not to share."),
      investigator: version("WELL.G1.EMPATHY.PERSPECTIVE_01", "A face is a clue, not proof. Listening helps us understand another person.", "Pip is quiet after a busy game. Pip might be tired, worried, or simply wanting quiet.", "Can we know exactly how Pip feels just by looking?", choose("How could Nova find out what Pip needs?", ["Guess and insist", "Ask Pip kindly", "Tell Pip to hurry"], 1, "Let Pip tell you rather than choosing a feeling for Pip.", "Asking kindly lets Pip explain. People can look similar while feeling different things."), "What could you say if Pip does not want to talk?", "Practise asking, 'Would you like help, company, or some space?' with a grown-up."),
      scientist: version("WELL.G1.EMPATHY.PERSPECTIVE_01", "Two people can experience the same event differently. We need their perspective.", "Nova loves a noisy parade. Wren covers her ears and wants to move away.", "Does enjoying the parade mean Nova knows how Wren feels?", choose("What could Nova do?", ["Insist Wren stay", "Say the noise is fine for everyone", "Ask whether Wren wants a quieter place"], 2, "Wren's experience may differ from Nova's.", "Asking respects Wren's experience. They can seek a quieter place with their grown-up."), "Can both friends' feelings make sense at the same time?", "During a story, imagine two characters' viewpoints. Explain what each might need."),
    },
  },
  {
    id: "team-turns", domain: "wellbeing", title: "Better together", subtitle: "Make a plan that includes a friend.", minutes: 4,
    vocabulary: { word: "cooperate", meaning: "To work together toward a shared goal." }, sourceIds: ["harvard-play"], next: { label: "Visit Team Camp", href: "/team" },
    versions: {
      explorer: version("WELL.PK.SOCIAL.SHARE_01", "Taking turns gives each person time to play.", "Nova rolls a ball to Pip. Pip rolls it back. Both get a turn.", "Who rolls the ball after Nova?", sequence("Build two turns, starting with Nova.", ["Pip rolls", "Nova rolls"], [1, 0], "Nova goes first, then Pip.", "Nova rolls, then Pip rolls. Each person has a turn."), "How can we show that we are ready for someone else's turn?", "Roll a ball back and forth with a grown-up. Say whose turn comes next."),
      investigator: version("WELL.PK.SOCIAL.SHARE_01", "A shared plan helps when two people want the same thing.", "Nova and Pip both want a brush. They agree Nova will finish one shape, then pass it to Pip.", "How do both friends know when the turn changes?", choose("Which plan includes both friends?", ["Hide the brush", "Keep it forever", "Agree when to pass it"], 2, "A useful plan tells both people when they get a turn.", "Agreeing when to pass the brush gives both friends a clear turn."), "What could you do if the plan stops feeling fair?", "Make a shared drawing. Agree together when to pass a crayon."),
      scientist: version("WELL.G1.CHOICE.RESPONSIBLE_01", "Cooperation can mean different jobs that help one shared goal.", "For a paper town, Nova folds houses while Pip draws roads. They agree where the houses will go.", "Why do they need to talk before joining the pieces?", sequence("Plan a shared building project.", ["Build your agreed parts", "Agree on a goal and jobs", "Check together and adjust"], [1, 0, 2], "First agree what you are making and who will do what.", "Agree, build, then check together. Revising the plan is part of cooperation."), "How can everyone have a voice when the group disagrees?", "Build something with another person. Choose jobs together, then discuss one improvement."),
    },
  },
];
