import "server-only";
import type { DiscoveryLesson, DiscoveryVersion } from "./types";

// Each row is an authored lesson, not generated difficulty text. Answer keys stay server-side.
function v(skillId: string, idea: string, example: string, notice: string, prompt: string, choices: string[], answer: number, hint: string, explanation: string, talk: string, away: string): DiscoveryVersion {
  return { skillId, idea, example, notice, task: { kind: "choose", prompt, choices, answer: [answer], hint, explanation }, talk, away };
}

export const expandedDiscoveries: DiscoveryLesson[] = [
  {
    id: "sound-garden", domain: "reading", title: "The sound garden", subtitle: "Listen for little pieces inside words.", minutes: 4,
    vocabulary: { word: "syllable", meaning: "A beat in a spoken word." }, sourceIds: ["wwc-reading"], next: { label: "Visit the Reading Grove", href: "/read" },
    versions: {
      explorer: v("LIT.PK.PA.RHYME_01", "Rhyming words have endings that sound alike.", "Say cat and hat. Listen to the matching ending.", "Say the words slowly with someone.", "Which rhymes with sun?", ["Fun", "Dog"], 0, "Listen to the end of sun and fun.", "Sun and fun end with the same sound.", "Can you invent a silly rhyming word?", "With a grown-up, find two rhyming words in a song you know."),
      investigator: v("LIT.PK.PA.SYLLABLE_01", "Clap once for each syllable you hear in a word.", "Rabbit has two beats: rab-bit. Elephant has three: el-e-phant.", "Try clapping your own name slowly.", "How many beats are in banana?", ["Two", "Three", "Four"], 1, "Say ba-na-na and clap each part.", "Ba-na-na has three syllables. We count spoken beats, not letters.", "Does a longer written word always have more beats?", "Clap the names of three things in your room. Group them by their number of syllables."),
      scientist: v("LIT.G1.PH.LONG_VOWEL_01", "A final silent e can change the sound of an earlier vowel.", "Compare cap and cape. In cape, a says its letter name and the final e is silent.", "What changes when you say both words?", "Which pair shows the same change?", ["Hop and hope", "Sun and sand", "Cat and cut", "Tree and truck"], 0, "Look for a final e added to the same word.", "Hop becomes hope. The o changes from a short sound to its letter-name sound.", "Why is listening helpful as well as looking at letters?", "Write kit and kite, then tap and tape. Read each pair and explain what changes."),
    },
  },
  {
    id: "story-workshop", domain: "reading", title: "A tiny tale workshop", subtitle: "Give a character a problem to solve.", minutes: 5,
    vocabulary: { word: "character", meaning: "A person, animal or imaginary being in a story." }, sourceIds: ["wwc-reading", "wwc-learning"], next: { label: "Make a story", href: "/stories" },
    versions: {
      explorer: v("LIT.PK.COMP.RECALL_01", "Listen for who a story is about.", "A duck loses her red hat. She finds it under a leaf.", "Who was looking for something?", "Who lost a hat?", ["A duck", "A bear"], 0, "Listen again to the first sentence.", "The duck is the character who lost her hat.", "What voice would your duck have?", "Choose a toy. Tell a grown-up one thing that happens to it."),
      investigator: v("LIT.G1.COMP.CAUSE_01", "A useful story ending solves the character's problem.", "A fox cannot reach a kite in a low branch. An adult brings a long pole and helps it down.", "How does the ending connect to the problem?", "Mina's drawing blows under a bench. Which ending solves this?", ["Mina eats lunch", "Mina reaches under and retrieves it", "Mina sees a cloud"], 1, "The problem is the missing drawing.", "Retrieving the drawing solves the problem. The other events do not explain what happened to it.", "Can you invent another possible solution?", "Draw three boxes: a character, a problem, and a helpful ending. Tell your tiny tale."),
      scientist: v("LIT.G1.COMP.TRAIT_01", "A character's choices give evidence about what they are like.", "Even after his tower falls twice, Ari changes the base and tries again. His actions show persistence.", "Which action tells more than a description would?", "Jo gives a lost visitor her own map. Which trait has the strongest evidence?", ["Sleepy", "Forgetful", "Helpful", "Hungry"], 2, "Think about how Jo's choice affects the visitor.", "Giving a useful map helps the visitor. That action supports helpful; the story gives no evidence for the other traits.", "Could the same character make an unhelpful choice later?", "Write or tell a short scene showing kindness without using the word kind. Ask someone to find your evidence."),
    },
  },
  {
    id: "shape-studio", domain: "math", title: "Shapes in disguise", subtitle: "Turn a shape. What stays the same?", minutes: 4,
    vocabulary: { word: "side", meaning: "A straight edge of a flat shape." }, sourceIds: ["wwc-math"], next: { label: "Make a shape picture", href: "/create" },
    versions: {
      explorer: v("MATH.PK.GEO.SHAPE_01", "A triangle has three straight sides.", "A triangle can look like a little roof. Trace its three sides with a finger.", "Can you find the three corners too?", "Which has three straight sides?", ["Triangle", "Circle"], 0, "A circle curves all the way around.", "A triangle has three straight sides and three corners.", "What could you make with a triangle roof?", "With a grown-up, draw a triangle house roof and a round sun."),
      investigator: v("MATH.G1.GEO.ATTRIBUTES_01", "Turning a shape does not change its number of sides or corners.", "A square standing on a corner is still a square. It keeps four equal sides and four square corners.", "Turn a paper square and watch its corners.", "A triangle turns upside down. What is it now?", ["A circle", "Still a triangle", "A square"], 1, "Count the sides after it turns.", "It is still a triangle because it still has three straight sides.", "What would have to change to make a different shape?", "Draw the same triangle pointing in three directions. Count the sides each time."),
      scientist: v("MATH.G1.GEO.ATTRIBUTES_01", "Shape families can overlap. A rectangle has four square corners; a square is a special rectangle with four equal sides.", "A long rectangle and a square both have four right angles. Only the square must have all four sides equal.", "Which rule do both shapes follow?", "Which statement must be true of every square?", ["It has only two equal sides", "It has no right angles", "It is also a rectangle", "It must stand on a flat side"], 2, "Check the four-right-angle rule for rectangles.", "Every square satisfies the rectangle rule. Turning it does not change that.", "Why is every rectangle not a square? Give an example.", "Draw a rectangle that is not a square. Label which sides match and explain your choice."),
    },
  },
  {
    id: "measure-market", domain: "math", title: "The measuring market", subtitle: "Compare lengths and choose a fair unit.", minutes: 4,
    vocabulary: { word: "unit", meaning: "An agreed amount used to measure something." }, sourceIds: ["wwc-math"], next: { label: "Try a number game", href: "/play" },
    versions: {
      explorer: v("MATH.G1.MEASURE.COMPARE_01", "Line up one end of two objects to compare their lengths.", "Two ribbons begin at the same line. The blue ribbon reaches farther, so it is longer.", "Why should the ribbons start together?", "Which ribbon is longer?", ["The one that reaches farther", "The one that is brighter"], 0, "Look at where they end, not their color.", "With the starts lined up, the one reaching farther has greater length.", "Find something shorter than your hand.", "Place two crayons side by side with their ends lined up. Tell someone which is longer."),
      investigator: v("MATH.G1.MEASURE.COMPARE_01", "Measure length with equal units placed end to end, without gaps or overlaps.", "A toy path is exactly six identical blocks long. Six is the measurement and block is the unit.", "What would a gap between blocks do?", "Which way gives a fair measurement?", ["Leave spaces between blocks", "Use equal blocks touching end to end", "Mix big and tiny blocks"], 1, "Every unit should cover the same length.", "Equal touching blocks cover the whole length once, without missing or counting any part twice.", "Why might measuring with your hands differ from a grown-up's hands?", "Measure a book with identical paper squares. Write the number and the unit."),
      scientist: v("MATH.G1.MEASURE.AREA_01", "Area counts equal squares covering a surface. Length measures along one direction.", "A rectangle with two rows of four unit squares has an area of eight square units.", "Point to a row, then count how many rows there are.", "A mat has 3 rows of 4 unit squares. What is its area?", ["7 square units", "12 square units", "3 square units", "4 square units"], 1, "Count four squares three times.", "4 + 4 + 4 = 12. All twelve unit squares cover the mat.", "Can a different rectangle have the same area?", "On squared paper, draw two different rectangles with area twelve square units. Compare their side lengths."),
    },
  },
  {
    id: "push-pull", domain: "science", title: "The motion workshop", subtitle: "Predict, change something, and look again.", minutes: 5,
    vocabulary: { word: "force", meaning: "A push or pull that can change an object's motion." }, sourceIds: ["ngss", "wwc-learning"], next: { label: "Explore Wonder Lab", href: "/science" },
    versions: {
      explorer: v("SCI.G1.PHYS.FORCE_01", "A push moves something away from you. A pull brings it toward you.", "You push a toy car away. You pull a toy wagon toward you.", "Show a gentle push with your hands.", "Move a toy away from you. Is that a push or a pull?", ["Push", "Pull"], 0, "Away is the clue.", "You push the toy away. A pull would bring it toward you.", "Where do you use a pull at home?", "With a grown-up, move a toy gently with a push, then a pull. Describe each movement."),
      investigator: v("SCI.G1.PHYS.FORCE_01", "A push can start motion, speed it up or change its direction.", "A rolling ball meets your hand. A gentle sideways push changes where it rolls.", "Can something move slowly and still change direction?", "A ball rolls left. A sideways push makes it roll forward. What changed?", ["Its color", "Its direction", "Its material"], 1, "Follow where the ball goes before and after.", "The push changed the direction of motion, not the ball's color or material.", "How could you slow a rolling ball?", "Roll a soft ball on the floor with a grown-up. Stop it gently and describe what your hand did."),
      scientist: v("SCI.G1.SCI.FAIRTEST_01", "To compare surfaces fairly, keep the car and starting ramp the same. Change only the surface.", "One car rolls from a marked height onto smooth card, then onto a towel. Measure how far it travels each time.", "What needs to stay the same for a useful comparison?", "Which test best compares the two surfaces?", ["Change the car and the ramp", "Use a different start each time", "Use the same car and start height", "Give one run an extra push"], 2, "Change only the thing you are investigating.", "The same car and start height help isolate the effect of the surface. Repeated runs make the evidence stronger.", "Why might one run on each surface be insufficient?", "With a grown-up and a low ramp, repeat each surface test three times. Record distances and compare the results."),
    },
  },
  {
    id: "habitat-homes", domain: "science", title: "A home that fits", subtitle: "Match living things to what they need.", minutes: 5,
    vocabulary: { word: "habitat", meaning: "The place where a living thing gets what it needs." }, sourceIds: ["ngss-plants", "wwc-learning"], next: { label: "Explore My Worlds", href: "/worlds" },
    versions: {
      explorer: v("SCI.PK.LIFE.HABITAT_01", "Animals need suitable places to live.", "A fish lives in water. A pond gives a pond fish space to swim and places to find food.", "How does a fish move around its home?", "Where can a pond fish live?", ["In pond water", "On a dry shelf"], 0, "A fish needs water around its body.", "Pond water is a suitable habitat for a pond fish. A dry shelf cannot meet its needs.", "What animals might you see near a pond?", "Look at an animal picture with a grown-up. Point out something in its home that helps it live."),
      investigator: v("SCI.PK.LIFE.HABITAT_01", "A habitat provides food, water, shelter and space. Different animals need different conditions.", "A garden bird can find seeds, drinking water and shelter in a hedge.", "Which needs does the hedge help meet?", "Which garden change would help a bird find shelter?", ["Remove every bush", "Keep a suitable leafy hedge", "Cover the soil with plastic"], 1, "Look for somewhere to hide and rest.", "A suitable hedge can provide cover and shelter. Birds also need food, water and space.", "Why might a garden help some animals but not others?", "Observe an outdoor space with a grown-up without disturbing animals. Sketch possible food and shelter."),
      scientist: v("SCI.PK.LIFE.HABITAT_01", "Changing one part of a habitat can affect several living things connected to it.", "Flowers feed insects. Some birds eat those insects. Removing flowers may reduce one food supply for both.", "Trace the connection from flower to insect to bird.", "If many flowers are removed, which prediction has a clear reason?", ["Every bird will disappear immediately", "Some insects may have less food", "All insects will become larger", "Birds will stop needing water"], 1, "Choose a possible effect supported by the food connection.", "Some insects may have less food. The evidence does not justify saying every animal will disappear.", "What other information would you collect before making a stronger prediction?", "Draw a three-part food connection from a habitat you know. Explain how one change might affect it."),
    },
  },
  {
    id: "sorting-station", domain: "logic", title: "The sorting station", subtitle: "One collection. More than one rule.", minutes: 4,
    vocabulary: { word: "attribute", meaning: "A feature, such as color, shape or size." }, sourceIds: ["wwc-math", "harvard-play"], next: { label: "Build a new idea", href: "/build" },
    versions: {
      explorer: v("LOGIC.PK.SORT.ATTRIBUTE_01", "A sorting rule tells us which things belong together.", "Put red blocks together, even if they have different shapes.", "Look for the feature that stays the same.", "Our group is red things. What belongs?", ["A red circle", "A blue circle"], 0, "We are sorting by color.", "The red circle follows the red-things rule. Shape does not matter for this rule.", "Could you sort the same blocks another way?", "Sort a few large toys by color with a grown-up. Then try a new rule."),
      investigator: v("LOGIC.G1.CLASSIFY.RULE_01", "The same collection can be sorted in different ways.", "A red square and a blue square go together by shape, but separate by color.", "What changed: the objects or the rule?", "Red and blue squares are together; circles are separate. What is the rule?", ["Same color", "Same shape", "Same name length"], 1, "Both colors appear in the square group.", "The objects are grouped by shape. Their colors can differ.", "How would the groups change if color became the rule?", "Draw six colored shapes. Sort by shape, then by color, explaining each decision."),
      scientist: v("LOGIC.G1.DEDUCE.IFTHEN_01", "A rule using and requires both conditions to be true.", "For red AND round, a red circle belongs. A red square satisfies only one condition.", "Which example meets both conditions?", "The rule is blue AND triangular. Which belongs?", ["A blue square", "A red triangle", "A blue triangle", "A yellow circle"], 2, "Check color and shape separately.", "Only the blue triangle meets both requirements. One matching feature is not enough.", "How would the group change if the rule used or instead of and?", "Draw a collection. Make a two-feature rule and ask someone to explain which objects qualify."),
    },
  },
  {
    id: "bridge-builders", domain: "logic", title: "Bridge builders", subtitle: "Try an idea, notice a wobble, improve it.", minutes: 5,
    vocabulary: { word: "support", meaning: "Something that holds another thing up." }, sourceIds: ["ngss", "harvard-play"], next: { label: "Visit Build Yard", href: "/build" },
    versions: {
      explorer: v("LOGIC.PK.SEQUENCE.ROUTINE_01", "A simple bridge needs something to hold up its ends.", "Two blocks support a paper strip, one block under each end.", "Point to the places holding the paper up.", "What should go under the ends?", ["Supporting blocks", "A picture of a cloud"], 0, "The ends need something solid below them.", "The blocks support the paper so it can span a small gap.", "What might happen if you move one support away?", "With a grown-up, lay a card across two blocks on the floor. Look underneath to find the supports."),
      investigator: v("LOGIC.G1.ENGINEER.STABILITY_01", "A wider base can help a tower stay steady.", "A tall block tower with a narrow base wobbles. Rebuilding it with a wider base can make it more stable.", "Look at what touches the ground.", "How could you improve a wobbly tower?", ["Make the base narrower", "Try a wider base", "Hide it behind a book"], 1, "Think about how the tower is supported.", "A wider base can improve stability. Test it gently to see whether your change helps.", "Does wider always mean stronger? What would you test?", "Build two low towers on the floor with different bases. Give each the same gentle tap and observe."),
      scientist: v("LOGIC.G1.ENGINEER.STABILITY_01", "Engineers improve a design using evidence from tests with a clear goal.", "A paper bridge holds two blocks before bending. Fold the paper edges, keep the gap the same, and test again.", "What result would count as an improvement?", "Which comparison gives useful evidence about the folds?", ["Change the paper and gap together", "Judge only by color", "Keep paper and gap alike; compare loads", "Test only the folded design"], 2, "Compare both designs under matching conditions.", "Keeping the material and span alike helps test whether the folds affect how much load the bridge holds.", "What tradeoff might there be between using less material and carrying more load?", "With a grown-up, test flat and folded paper across a small gap. Add identical light blocks one at a time and record the load."),
    },
  },
  {
    id: "map-missions", domain: "world", title: "A mapmaker's mission", subtitle: "Use symbols, directions and routes.", minutes: 4,
    vocabulary: { word: "key", meaning: "The guide that explains a map's symbols." }, sourceIds: ["wwc-learning"], next: { label: "Travel through My Worlds", href: "/worlds" },
    versions: {
      explorer: v("WORLD.PK.MAP.LANDWATER_01", "Maps use marks and colors to stand for real places.", "On our pretend map, blue stands for water and green stands for land.", "Use our map's color rule to find water.", "Which color means water on our map?", ["Blue", "Green"], 0, "Our map key says blue means water.", "Blue represents water on this map. A key tells us what each symbol means.", "What picture could stand for your home?", "Draw a pretend map with a grown-up. Choose a symbol for a house and explain it."),
      investigator: v("WORLD.G1.MAP.DIRECTION_01", "A compass arrow helps us read directions on a map.", "When north points to the top, east is right, south is down and west is left.", "Find opposite directions with your hands.", "North points up. The park is right of school. Which direction is it?", ["West", "East", "South"], 1, "Use the direction rule in the example.", "Right is east on this north-up map. Check the compass before assuming a map's direction.", "What direction takes you back from the park to school?", "Draw a north-up map of an imaginary town. Put one landmark east and another west of school."),
      scientist: v("WORLD.G1.MAP.ROUTE_01", "A shortest route must also follow the map's rules and avoid blocked paths.", "Two routes reach the library. The three-step route is blocked; the five-step route is open. The open route works.", "Why is counting steps alone not enough?", "A 4-step route crosses a closed bridge. A 6-step route stays open. Which should you plan?", ["The closed route because it is shorter", "The open 6-step route", "Either; closures never matter", "Stop using the map key"], 1, "A valid route must be possible to travel.", "The six-step route reaches the destination without using the closed bridge. Constraints matter as well as distance.", "If the bridge reopened, how would you reconsider your plan?", "Draw a grid town and block one square. Find two valid routes between landmarks, then compare their lengths."),
    },
  },
  {
    id: "then-and-now", domain: "world", title: "Then, now, next", subtitle: "Discover how tools change everyday life.", minutes: 4,
    vocabulary: { word: "invent", meaning: "To create a new tool, process or idea." }, sourceIds: ["wwc-learning", "ngss"], next: { label: "Meet helpful tools", href: "/worlds" },
    versions: {
      explorer: v("WORLD.PK.COMM.HELPERS_01", "People use tools to help with a job.", "A gardener uses a watering can to carry and pour water for plants.", "How does the can help the gardener?", "Which tool helps water a plant?", ["A watering can", "A pillow"], 0, "Look for something that holds and pours water.", "A watering can helps move water to a plant.", "What tool do you use when you draw?", "With a grown-up, find a safe everyday tool and explain what job it helps with."),
      investigator: v("WORLD.G1.TIME.THEN_NOW_01", "Tools can change while the job people want to do stays similar.", "People have used handwritten letters and electronic messages to share news with someone far away.", "What is the same about both ways of communicating?", "What job can both a letter and an electronic message do?", ["Cook a meal", "Share news with someone far away", "Water a garden"], 1, "Think about why someone sends either message.", "Both carry information to someone else, though the tools and delivery can differ.", "When might a handwritten letter feel special?", "Ask a grown-up about a tool they used as a child. Draw it beside a tool used for that job today."),
      scientist: v("WORLD.G1.INVENT.TOOLS_01", "A useful invention solves a need, but different tools have different tradeoffs.", "A bicycle carries a person efficiently and needs no fuel from a pump, but has less room for heavy loads than a truck.", "Which tool is best depends on the job.", "A team must carry a very heavy load a long distance. What should it consider first?", ["Only the prettiest color", "Only the newest design", "Load capacity and the route", "The shortest name"], 2, "Match a tool's capabilities to the task.", "Capacity and route help determine whether a transport tool can do this job. Appearance alone cannot tell us.", "What other factors might matter, such as energy or access?", "Design a tool for carrying books. Label a useful feature and one limitation you would improve."),
    },
  },
  {
    id: "friendship-fixes", domain: "wellbeing", title: "Friendship fix-it", subtitle: "Listen, make room, and try a kind solution.", minutes: 4,
    vocabulary: { word: "perspective", meaning: "Someone's way of seeing or experiencing a situation." }, sourceIds: ["harvard-play", "wwc-learning"], next: { label: "Try a team quest", href: "/team" },
    versions: {
      explorer: v("WELL.PK.SOCIAL.SHARE_01", "Taking turns lets friends use the same toy.", "Pip rolls the toy car, then gives Nova a turn.", "What could you say when you want a turn?", "A friend is using the car. What is a kind thing to say?", ["May I have a turn next?", "I will grab it now!"], 0, "Use words to ask for a turn.", "Asking for a turn helps friends play together. A grown-up can help when waiting is hard.", "How can you tell your friend their turn is ready?", "Take turns making a toy move with a grown-up. Practise saying your turn and my turn."),
      investigator: v("WELL.G1.EMPATHY.PERSPECTIVE_01", "People can feel differently about the same event. Asking helps us understand.", "A loud game feels exciting to Jo but uncomfortable to Sam. Both experiences matter.", "What could Jo ask instead of guessing?", "Sam covers their ears during a game. What could you do?", ["Make the game louder", "Ask if they would like a quieter game", "Tell them everyone feels the same"], 1, "Notice the clue and check what Sam needs.", "A gentle question makes room for Sam's experience. You cannot know exactly how someone feels from one clue alone.", "How could the group keep playing while including Sam?", "Ask someone which kind of game they enjoy. Listen for one preference different from yours."),
      scientist: v("WELL.G1.CHOICE.RESPONSIBLE_01", "A fair solution listens to everyone's needs and can be revised if it does not work.", "Two friends need the same marker. They agree on short turns, then check whether both had time to finish.", "What makes the check-in useful?", "Two teammates disagree about their plan. What is a constructive next step?", ["Let the loudest person decide", "Ignore one teammate", "Hear both reasons and agree on a trial", "Hide the materials"], 2, "Look for a choice that includes both people.", "Listening to both reasons and trying an agreed plan gives the team a way forward without dismissing anyone.", "How could you tell whether the trial worked fairly?", "Plan a shared activity with someone. Name each person's need, agree on a plan, and check in afterward."),
    },
  },
  {
    id: "mistake-magic", domain: "wellbeing", title: "The not-yet notebook", subtitle: "Turn a mistake into a useful next step.", minutes: 4,
    vocabulary: { word: "strategy", meaning: "A way you choose to approach a task." }, sourceIds: ["harvard-play", "wwc-learning"], next: { label: "Visit your keepsakes", href: "/rewards" },
    versions: {
      explorer: v("WELL.PK.EMOTION.NAME_01", "A tricky task can feel frustrating. You can ask for help.", "A puzzle piece will not fit. Nova stops and asks a grown-up to look with her.", "Show what asking for help might sound like.", "Your puzzle feels too tricky. What can you do?", ["Ask someone to help", "Say nobody may ever try"], 0, "You do not have to solve it alone.", "Asking for help is one way to care for yourself while learning.", "Who can you ask when something feels hard?", "Try a small puzzle with a grown-up. Practise saying please help me with this part."),
      investigator: v("WELL.G1.REGULATE.CALM_01", "A pause can give you room to choose what to try next.", "Pip feels frustrated by a tower. Pip pauses, then rebuilds the base with help.", "Which part helped Pip make a new choice?", "What is a useful next step after a mistake?", ["Try a pause and look for another way", "Assume you can never learn", "Hide every question"], 0, "You can pause, ask for help or change your approach.", "Pausing and trying another way can help. You can also choose to return to the task later.", "Which part could you ask someone to show you?", "Tell someone about a tricky moment. Name one thing that helped, even if the task is not finished."),
      scientist: v("WELL.G1.CHOICE.RESPONSIBLE_01", "Useful reflection identifies what happened and a specific change to test.", "I guessed the route and hit a dead end. Next time I will check the map before choosing a turn.", "Which part of that reflection describes an action?", "Which reflection gives a clear strategy for a second try?", ["I am bad at this forever", "I will somehow be perfect", "I skipped a step; I will check each instruction", "Mistakes tell us nothing"], 2, "Choose a change you can actually carry out.", "Checking each instruction responds to the skipped step. It gives you a specific strategy to test.", "How would you know whether the new strategy helped?", "Make a two-column note: what I tried and what I will change. Revisit a small challenge and compare the attempts."),
    },
  },
];
