/** Research informs the design; these sources do not establish efficacy of this app. */
export const discoverySources = [
  { id: "ngss-light", title: "Light and materials · 1-PS4-3", organization: "Next Generation Science Standards", url: "https://www.nextgenscience.org/dci-arrangement/1-ps4-waves-and-their-applications-technologies-information-transfer", use: "Investigate how different materials transmit or block a beam of light. An opaque object blocks light and can create a shadow." },
  { id: "ngss-plants", title: "Plants, sunlight and water · 2-LS2-1", organization: "Next Generation Science Standards", url: "https://www.nextgenscience.org/search-standards?keys=plants", use: "Investigate the roles of water and sunlight in plant growth. The seed activity distinguishes sprouting from the needs of a growing green plant." },
  { id: "wwc-math", title: "Teaching Math to Young Children", organization: "Institute of Education Sciences · What Works Clearinghouse", url: "https://ies.ed.gov/ncee/wwc/PracticeGuide/18", use: "Build from concrete quantities toward symbols, follow developmental progressions, and connect maths to everyday situations." },
  { id: "wwc-reading", title: "Foundational Skills to Support Reading for Understanding", organization: "Institute of Education Sciences · What Works Clearinghouse", url: "https://ies.ed.gov/ncee/WWC/PracticeGuide/21/Published", use: "Support language and vocabulary alongside explicit sound–letter work and connected reading. These story activities complement the existing phonics pathway." },
  { id: "wwc-learning", title: "Organizing Instruction and Study to Improve Student Learning", organization: "Institute of Education Sciences · What Works Clearinghouse", url: "https://ies.ed.gov/ncee/wwc/PracticeGuide/1", use: "Connect examples to practice, ask for explanations, and revisit ideas over time. Much of this guide addresses school-age learners; preschool adaptations are design choices, not validated interventions." },
  { id: "ngss", title: "K–2 Engineering Design", organization: "Next Generation Science Standards", url: "https://www.nextgenscience.org/pe/k-2-ets1-1-engineering-design", use: "Ask questions, observe a problem, and consider how a tool or design can solve it. This is a standards reference, not an efficacy study." },
  { id: "harvard-play", title: "Enhancing and Practicing Executive Function Skills", organization: "Harvard Center on the Developing Child", url: "https://developingchild.harvard.edu/resources/handouts-tools/activities-guide-enhancing-and-practicing-executive-function-skills/", use: "Use shared play to practise remembering rules, taking turns, and flexible thinking. An app response is not a measure of a child's emotional wellbeing." },
] as const;
