-- CurioQuest hero clip library (Phase 2): 5 new character videos.
-- bea/riff/atlas celebrations complete the cast's cheer set; nova-try-again
-- models survivable mistakes on the compare teaching move; curio-goodbye
-- closes the session warmly.
-- Served from public/media/clips/ in dev; set NEXT_PUBLIC_CLIP_CDN to the
-- curriculum-media storage prefix in production and update videoUrl.
begin;
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('62e2502b-e57a-4071-a660-36aee4b81a6c','bea-celebrate','Bea''s honey dance','clip','{"id":"bea-celebrate","title":"Bea''s honey dance","category":"Hero clips","domain":"celebration","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/bea-celebrate.mp4","captionUrl":null,"thumbnail":"bea","caption":"Buzz buzz — you grew that idea all by yourself!","cue":"Buzz and wiggle with Bea!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('13c2f15c-b10e-480e-95f0-d72019e1c8a0','riff-celebrate','Riff''s victory riff','clip','{"id":"riff-celebrate","title":"Riff''s victory riff","category":"Hero clips","domain":"celebration","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/riff-celebrate.mp4","captionUrl":null,"thumbnail":"riff","caption":"That''s music to my ears! You nailed it!","cue":"Clap the rhythm with Riff!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('f008c822-daaa-4237-a1f3-b9a2caef2fe7','atlas-celebrate','Atlas''s big cheer','clip','{"id":"atlas-celebrate","title":"Atlas''s big cheer","category":"Hero clips","domain":"celebration","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/atlas-celebrate.mp4","captionUrl":null,"thumbnail":"atlas","caption":"You remembered! What a wonderful explorer you are.","cue":"Stomp gently with Atlas!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('655e5140-69e2-4bd0-ad78-cf9a1d848a61','nova-try-again','Nova tries again','clip','{"id":"nova-try-again","title":"Nova tries again","category":"Hero clips","domain":"encouragement","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/nova-try-again.mp4","captionUrl":null,"thumbnail":"nova","caption":"Oops — that one tricked me too! Let''s try again together.","cue":"Try again with Nova!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('b608203a-a1e2-4cd4-9472-4b1eb7788335','curio-goodbye','Curio says goodbye','clip','{"id":"curio-goodbye","title":"Curio says goodbye","category":"Hero clips","domain":"farewell","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/curio-goodbye.mp4","captionUrl":null,"thumbnail":"curio","caption":"What an adventure! I''ll be right here when you come back.","cue":"Wave goodbye to Curio!","scenes":[]}'::jsonb,true);
commit;
