-- CurioQuest hero clip library (Phase 1): 25 character videos.
-- Served from public/media/clips/ in dev; set NEXT_PUBLIC_CLIP_CDN to the
-- curriculum-media storage prefix in production and update videoUrl.
begin;
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('c0897ed6-15e0-49ab-89c6-6d02ed62a2c1','curio-welcome','Curio welcomes you','clip','{"id":"curio-welcome","title":"Curio welcomes you","category":"Hero clips","domain":"welcome","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/curio-welcome.mp4","captionUrl":null,"thumbnail":"curio","caption":"Hello, explorer! I''m Curio. Ready for an adventure?","cue":"Wave back at Curio!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('77e01ca9-21a8-4047-9d6d-14b1dec1df69','nova-intro','Nova''s mystery','clip','{"id":"nova-intro","title":"Nova''s mystery","category":"Hero clips","domain":"welcome","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/nova-intro.mp4","captionUrl":null,"thumbnail":"nova","caption":"Come on — there''s a mystery in the forest, and I need your help.","cue":"Follow Nova into the story.","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('79a735ad-fcc4-4d66-a92a-76781461bf9e','luna-intro','Luna''s reading time','clip','{"id":"luna-intro","title":"Luna''s reading time","category":"Hero clips","domain":"welcome","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/luna-intro.mp4","captionUrl":null,"thumbnail":"luna","caption":"Let''s read together. I''ll help you with every letter.","cue":"Say the letters with Luna.","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('3340dfaf-f2f2-4f0f-9b12-b9f414833c98','milo-intro','Milo''s number lab','clip','{"id":"milo-intro","title":"Milo''s number lab","category":"Hero clips","domain":"welcome","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/milo-intro.mp4","captionUrl":null,"thumbnail":"milo","caption":"One, two, three! Counting is my favorite game.","cue":"Count along with Milo.","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('2387f6a3-cd14-450e-b796-e2e4b29ae501','bea-intro','Bea''s garden','clip','{"id":"bea-intro","title":"Bea''s garden","category":"Hero clips","domain":"welcome","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/bea-intro.mp4","captionUrl":null,"thumbnail":"bea","caption":"Look what I found growing! Nature is full of surprises.","cue":"Tell Bea what you notice.","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('d51208c3-e081-4633-b1ab-97c34816ccec','tuno-intro','Meet Tuno','clip','{"id":"tuno-intro","title":"Meet Tuno","category":"Hero clips","domain":"welcome","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/tuno-intro.mp4","captionUrl":null,"thumbnail":"tuno","caption":"Hello. I''m Tuno. When big feelings come, we''ll slow down together.","cue":"Say hello to Tuno.","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('a483bff8-4ec3-4605-8dbe-6c575f2093e5','tuno-breathing','Breathe with Tuno','clip','{"id":"tuno-breathing","title":"Breathe with Tuno","category":"Hero clips","domain":"wellbeing","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/tuno-breathing.mp4","captionUrl":null,"thumbnail":"tuno","caption":"Slow and steady. Breathe in with me… and out. There''s no hurry.","cue":"Breathe in… and out, with Tuno.","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('061d4bc5-2164-41cd-90e7-fdf8ce41c961','riff-intro','Riff''s rhythm','clip','{"id":"riff-intro","title":"Riff''s rhythm","category":"Hero clips","domain":"welcome","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/riff-intro.mp4","captionUrl":null,"thumbnail":"riff","caption":"Clap, clap! Can you copy my rhythm?","cue":"Clap it back to Riff!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('8af70406-4cb1-4e6c-aadf-0477b8d40f3b','atlas-intro','Atlas''s big world','clip','{"id":"atlas-intro","title":"Atlas''s big world","category":"Hero clips","domain":"welcome","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/atlas-intro.mp4","captionUrl":null,"thumbnail":"atlas","caption":"The world is so big and wonderful. Where shall we go today?","cue":"Point to a place on the globe.","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('a18ac495-f9a0-46e5-9ea3-988d82a6bdb8','cast-finale','The whole crew celebrates','clip','{"id":"cast-finale","title":"The whole crew celebrates","category":"Hero clips","domain":"celebration","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/cast-finale.mp4","captionUrl":null,"thumbnail":"curio","caption":"We did it — all of us, together! You were amazing.","cue":"Dance with the whole crew!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('05a8de72-7aa0-493c-b3f5-58f98b967998','curio-celebrate','Curio cheers for you','clip','{"id":"curio-celebrate","title":"Curio cheers for you","category":"Hero clips","domain":"celebration","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/curio-celebrate.mp4","captionUrl":null,"thumbnail":"curio","caption":"You did it! I''m so proud of you, explorer!","cue":"Cheer with Curio!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('85727d90-b0b7-4908-b48c-94518e1eaf60','nova-highfive','High five, Nova!','clip','{"id":"nova-highfive","title":"High five, Nova!","category":"Hero clips","domain":"celebration","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/nova-highfive.mp4","captionUrl":null,"thumbnail":"nova","caption":"High five! We make a great team!","cue":"Give Nova a high five!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('f012b18d-8ee9-45af-9e01-51ca67c0caf9','luna-praise','Luna is proud','clip','{"id":"luna-praise","title":"Luna is proud","category":"Hero clips","domain":"celebration","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/luna-praise.mp4","captionUrl":null,"thumbnail":"luna","caption":"You read it! Every letter, all by yourself.","cue":"Take a bow with Luna.","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('7c538f8a-560b-4a2b-8f61-b4bdfa7bc622','milo-dance','Milo''s happy dance','clip','{"id":"milo-dance","title":"Milo''s happy dance","category":"Hero clips","domain":"celebration","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/milo-dance.mp4","captionUrl":null,"thumbnail":"milo","caption":"Beep boop — I mean, amazing counting!","cue":"Dance like a robot with Milo!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('b9dae257-f28f-4f8a-a777-72d9167d6ac3','tuno-proud','Tuno''s quiet cheer','clip','{"id":"tuno-proud","title":"Tuno''s quiet cheer","category":"Hero clips","domain":"celebration","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/tuno-proud.mp4","captionUrl":null,"thumbnail":"tuno","caption":"Slow and steady wins. I''m proud of you.","cue":"Take a calm breath with Tuno.","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('9379a966-2c3c-47cb-a5bf-fcd09ace247d','luna-letter-trace','Trace a letter with Luna','clip','{"id":"luna-letter-trace","title":"Trace a letter with Luna","category":"Hero clips","domain":"learning","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/luna-letter-trace.mp4","captionUrl":null,"thumbnail":"luna","caption":"Watch my wing — down, down, across. Now you trace it in the air!","cue":"Trace the letter in the air.","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('ed3f5328-24b3-4523-82f9-311a3a6c8352','milo-counting','Count with Milo','clip','{"id":"milo-counting","title":"Count with Milo","category":"Hero clips","domain":"learning","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/milo-counting.mp4","captionUrl":null,"thumbnail":"milo","caption":"One apple, two apples, three! How many do you see?","cue":"Count the apples with Milo.","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('7df7fdb8-3344-4ec7-8ce9-20fd08c96da1','bea-growth','How a seed grows','clip','{"id":"bea-growth","title":"How a seed grows","category":"Hero clips","domain":"learning","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/bea-growth.mp4","captionUrl":null,"thumbnail":"bea","caption":"First a sprout, then leaves, then a flower! What changed?","cue":"Tell Bea what changed.","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('e78da477-8740-4e62-a443-b610c6654615','riff-copy-rhythm','Copy Riff''s rhythm','clip','{"id":"riff-copy-rhythm","title":"Copy Riff''s rhythm","category":"Hero clips","domain":"learning","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/riff-copy-rhythm.mp4","captionUrl":null,"thumbnail":"riff","caption":"Stomp, clap, clap! Now you try — copy my rhythm!","cue":"Copy the rhythm back!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('d49d9d30-6b6a-4362-b4bc-8aa843d7ad5c','atlas-continents','Three places on the globe','clip','{"id":"atlas-continents","title":"Three places on the globe","category":"Hero clips","domain":"learning","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/atlas-continents.mp4","captionUrl":null,"thumbnail":"atlas","caption":"Three glowing places! Which one would you visit first?","cue":"Point to the place you like.","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('5e300458-5e34-4eaa-b926-2b0c1913a8a8','nova-entry','Nova enters the learning world','clip','{"id":"nova-entry","title":"Nova enters the learning world","category":"Hero clips","domain":"worlds","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/nova-entry.mp4","captionUrl":null,"thumbnail":"nova","caption":"Come on — the learning world is waiting!","cue":"Follow Nova in!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('ecc3bd9c-0dd1-4e35-bd63-1744b473996d','portal-forest','Through the forest portal','clip','{"id":"portal-forest","title":"Through the forest portal","category":"Hero clips","domain":"worlds","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/portal-forest.mp4","captionUrl":null,"thumbnail":"curio","caption":"Through the branches — into the forest of stories!","cue":"Step through the portal!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('699322e9-d946-4290-b55f-ab8918aa3bde','portal-ocean','Dive into the ocean world','clip','{"id":"portal-ocean","title":"Dive into the ocean world","category":"Hero clips","domain":"worlds","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/portal-ocean.mp4","captionUrl":null,"thumbnail":"bea","caption":"The waves are parting! Let''s see what''s underneath!","cue":"Dive in!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('d8cd6c08-e0c3-42a4-8c55-a8f449d7fcc5','portal-space','Rocket to the space world','clip','{"id":"portal-space","title":"Rocket to the space world","category":"Hero clips","domain":"worlds","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/portal-space.mp4","captionUrl":null,"thumbnail":"milo","caption":"Three, two, one — blast off to the planets!","cue":"Count down with Milo!","scenes":[]}'::jsonb,true);
insert into public.media_assets(id,slug,title,media_type,metadata,published) values('7d97c3ec-26d7-406f-bee4-01b770e64577','meadow-hub','Home meadow','clip','{"id":"meadow-hub","title":"Home meadow","category":"Hero clips","domain":"worlds","skills":[],"ageMin":4,"ageMax":7,"duration":10,"active":true,"videoUrl":"/media/clips/meadow-hub.mp4","captionUrl":null,"thumbnail":"curio","caption":"Welcome home to the meadow. Where shall we explore today?","cue":"Choose a portal!","scenes":[]}'::jsonb,true);
commit;
