import type { ByTier, ColouringPage, Piece, PieceShape, StudioTier } from "./types";

/**
 * The colouring book.
 *
 * Twenty-four pages, every one a list of named, fillable parts rather than an outline.
 * That is the whole difference between this and what it replaces: the old pages were
 * `ctx.stroke()` calls, so "colouring in" meant dragging a brush and trying not to go
 * over the line, which is a fine motor exercise rather than a colouring book. Here a
 * child taps the cat's ear and the ear fills, named out loud, instantly.
 *
 * Three authoring rules:
 *
 * **Every part is a word.** `name` is read aloud and is the region's accessible name, so
 * a page is also a vocabulary walk: ear, whisker, paw, tail, petal, stem, chimney, sail,
 * fin, wing. A part called "shape 4" would be a wasted opportunity and unusable by a
 * child who is listening rather than looking.
 *
 * **The starting tones are a picture, not an answer.** A page opens tinted so it reads as
 * a cat rather than as a wireframe, and the first tap overwrites. Nothing anywhere scores
 * a child against them; a purple cat is a correct cat.
 *
 * **Order is paint order.** Pieces are drawn in array order, so the background goes
 * first and the eyes go last. `detail: true` marks a part that is drawn on top and never
 * filled — a pupil, a whisker, a mouth — and a tap on one fills whatever is underneath,
 * which is what a child aiming at a face actually means.
 */

/** Terse constructor, because a page is thirty of these and readability is the list. */
function pc(
  id: string,
  shape: PieceShape,
  x: number,
  y: number,
  w: number,
  h: number,
  tone: string,
  name: string,
  extra: Partial<Piece> = {},
): Piece {
  return { id, shape, x, y, w, h, tone, name, ...extra };
}

/** A detail line: drawn on top, never filled. */
const dt = (extra: Partial<Piece> = {}): Partial<Piece> => ({ detail: true, ...extra });

const t3 = <T,>(explorer: T, investigator: T, scientist: T): ByTier<T> => ({
  explorer, investigator, scientist,
});

const ALL: StudioTier[] = ["explorer", "investigator", "scientist"];
const OLDER: StudioTier[] = ["investigator", "scientist"];

/** A pair of eyes with pupils, used by every face on the shelf. */
function face(cx: number, cy: number, spread: number, size: number): Piece[] {
  return [
    pc("eye-left", "eye", cx - spread, cy, size, size * 1.2, "paper", "an eye"),
    pc("eye-right", "eye", cx + spread, cy, size, size * 1.2, "paper", "the other eye"),
    pc("pupil-left", "pupil", cx - spread, cy + size * 0.1, size * 0.45, size * 0.45, "ink", "an eye", dt()),
    pc("pupil-right", "pupil", cx + spread, cy + size * 0.1, size * 0.45, size * 0.45, "ink", "an eye", dt()),
  ];
}

export const colouringPages: ColouringPage[] = [
  /* ====================================================================== animals */
  {
    id: "cat",
    title: "A curious cat",
    childTitle: t3("A cat", "A curious cat", "A cat, sitting"),
    theme: "animals",
    tiers: ALL,
    invitation: t3("Give the cat a colour.", "What colour is your cat?", "Choose a coat, then decide what the whiskers are made of."),
    pieces: [
      pc("tail", "tailCurl", 150, 148, 70, 60, "honey", "the tail"),
      pc("body", "pear", 100, 136, 84, 92, "sunflower", "the body"),
      pc("paw-left", "paw", 80, 180, 30, 20, "honey", "a front paw"),
      pc("paw-right", "paw", 120, 180, 30, 20, "honey", "the other front paw"),
      pc("ear-left", "ear", 74, 62, 32, 36, "honey", "an ear", { rot: -14 }),
      pc("ear-right", "ear", 126, 62, 32, 36, "honey", "the other ear", { rot: 14, flip: true }),
      pc("head", "circle", 100, 80, 76, 70, "sunflower", "the head"),
      ...face(100, 74, 17, 15),
      pc("nose", "nose", 100, 92, 14, 11, "blush", "the nose"),
      pc("mouth", "mouth", 100, 100, 22, 10, "ink", "the mouth", dt()),
      pc("whisker-left", "whisker", 66, 94, 30, 14, "ink", "the whiskers", dt()),
      pc("whisker-right", "whisker", 134, 94, 30, 14, "ink", "the other whiskers", dt({ flip: true })),
      pc("chest", "oval", 100, 146, 40, 46, "apricot", "the chest"),
    ],
  },
  {
    id: "rabbit",
    title: "A long-eared rabbit",
    childTitle: t3("A rabbit", "A long-eared rabbit", "A rabbit, ears up"),
    theme: "animals",
    tiers: ALL,
    invitation: t3("Colour the big ears.", "Those ears are for listening. Colour them in.", "Ears that long are for hearing a fox a field away."),
    pieces: [
      pc("ear-left", "oval", 84, 42, 24, 62, "stone", "a long ear", { rot: -12 }),
      pc("ear-right", "oval", 116, 42, 24, 62, "stone", "the other long ear", { rot: 12 }),
      pc("ear-inner-left", "oval", 84, 44, 12, 46, "blush", "inside an ear", { rot: -12 }),
      pc("ear-inner-right", "oval", 116, 44, 12, 46, "blush", "inside the other ear", { rot: 12 }),
      pc("body", "egg", 100, 142, 82, 86, "stone", "the body"),
      pc("foot-left", "oval", 72, 188, 40, 20, "stone", "a big back foot"),
      pc("foot-right", "oval", 128, 188, 40, 20, "stone", "the other back foot"),
      pc("tail", "circle", 142, 158, 30, 30, "paper", "the fluffy tail"),
      pc("head", "circle", 100, 96, 66, 60, "stone", "the head"),
      ...face(100, 90, 15, 13),
      pc("nose", "nose", 100, 106, 13, 10, "rose", "the nose"),
      pc("mouth", "mouth", 100, 113, 18, 9, "ink", "the mouth", dt()),
      pc("tummy", "oval", 100, 152, 40, 44, "paper", "the tummy"),
    ],
  },
  {
    id: "bird",
    title: "A little songbird",
    childTitle: t3("A bird", "A little songbird", "A songbird on a branch"),
    theme: "animals",
    tiers: ALL,
    invitation: t3("Colour the wing.", "Give this bird some bright feathers.", "Birds that sing loudest are often the plainest. Yours need not be."),
    pieces: [
      pc("branch", "stripe", 100, 176, 150, 12, "bark", "the branch", { rot: -3 }),
      pc("tail", "leaf", 150, 118, 54, 26, "sea", "the tail feathers", { rot: 22 }),
      pc("body", "egg", 96, 120, 76, 84, "sky", "the body"),
      pc("wing", "wing", 104, 124, 50, 44, "sea", "the wing"),
      pc("leg-left", "stripe", 88, 166, 5, 24, "honey", "a leg"),
      pc("leg-right", "stripe", 108, 166, 5, 24, "honey", "the other leg"),
      pc("head", "circle", 84, 82, 52, 50, "sky", "the head"),
      pc("beak", "beak", 56, 88, 26, 18, "honey", "the beak"),
      pc("eye", "eye", 82, 78, 13, 14, "paper", "the eye"),
      pc("pupil", "pupil", 82, 79, 6, 6, "ink", "the eye", dt()),
      pc("crest", "petal", 84, 54, 16, 22, "coral", "the little crest"),
    ],
  },
  {
    id: "turtle",
    title: "A garden turtle",
    childTitle: t3("A turtle", "A garden turtle", "A turtle, walking"),
    theme: "animals",
    tiers: ALL,
    invitation: t3("Colour each shell piece.", "The shell is made of pieces. Colour each one.", "A turtle's shell is bone, grown in plates. Each plate can be its own colour."),
    pieces: [
      pc("leg-front", "oval", 56, 150, 30, 20, "moss", "a front leg", { rot: -18 }),
      pc("leg-back", "oval", 146, 150, 30, 20, "moss", "a back leg", { rot: 18 }),
      pc("tail", "triangle", 166, 132, 20, 14, "moss", "the little tail", { rot: 90 }),
      pc("head", "oval", 42, 118, 38, 30, "moss", "the head"),
      pc("eye", "eye", 34, 113, 11, 12, "paper", "the eye"),
      pc("pupil", "pupil", 33, 114, 5, 5, "ink", "the eye", dt()),
      pc("shell", "shell", 108, 122, 118, 82, "leaf", "the shell"),
      pc("plate-1", "diamond", 108, 104, 30, 26, "moss", "a shell piece"),
      pc("plate-2", "diamond", 76, 128, 28, 24, "forest", "another shell piece"),
      pc("plate-3", "diamond", 140, 128, 28, 24, "forest", "another shell piece"),
      pc("plate-4", "diamond", 108, 146, 30, 24, "moss", "the last shell piece"),
      pc("grass", "grass", 100, 182, 170, 24, "meadow", "the grass"),
    ],
  },
  {
    id: "dinosaur",
    title: "A friendly dinosaur",
    childTitle: t3("A dinosaur", "A friendly dinosaur", "A long-necked dinosaur"),
    theme: "animals",
    tiers: ALL,
    invitation: t3("Colour the spikes.", "Nobody knows what colour they were. You decide.", "Fossils keep shape and lose colour, so every dinosaur you have ever seen was somebody's choice."),
    pieces: [
      pc("tail", "triangle", 48, 130, 62, 36, "moss", "the tail", { rot: -96 }),
      pc("body", "oval", 100, 130, 108, 70, "leaf", "the body"),
      pc("leg-front", "rounded", 78, 168, 22, 40, "moss", "a front leg"),
      pc("leg-back", "rounded", 126, 168, 22, 40, "moss", "a back leg"),
      pc("neck", "stripe", 146, 96, 22, 68, "leaf", "the long neck", { rot: 22 }),
      pc("head", "oval", 162, 62, 46, 30, "leaf", "the head"),
      pc("eye", "eye", 170, 56, 11, 12, "paper", "the eye"),
      pc("pupil", "pupil", 171, 57, 5, 5, "ink", "the eye", dt()),
      pc("spike-1", "spike", 66, 100, 18, 22, "honey", "a back spike"),
      pc("spike-2", "spike", 94, 92, 20, 26, "honey", "another spike"),
      pc("spike-3", "spike", 122, 96, 18, 22, "honey", "the last spike"),
      pc("ground", "grass", 100, 190, 180, 20, "meadow", "the ground"),
    ],
  },

  /* ======================================================================= nature */
  {
    id: "butterfly",
    title: "Butterfly wings",
    childTitle: t3("A butterfly", "Butterfly wings", "A butterfly, wings open"),
    theme: "nature",
    tiers: ALL,
    invitation: t3("Colour both wings.", "Butterfly wings match. Yours can too — or not.", "Most butterflies are symmetrical. Matching the two sides is harder than it looks."),
    pieces: [
      pc("wing-top-left", "petal", 62, 78, 62, 72, "grape", "the top left wing", { rot: -28 }),
      pc("wing-top-right", "petal", 138, 78, 62, 72, "grape", "the top right wing", { rot: 28, flip: true }),
      pc("wing-low-left", "petal", 70, 140, 50, 58, "lavender", "the bottom left wing", { rot: -156 }),
      pc("wing-low-right", "petal", 130, 140, 50, 58, "lavender", "the bottom right wing", { rot: 156, flip: true }),
      pc("spot-left-a", "circle", 60, 72, 20, 20, "sunflower", "a spot"),
      pc("spot-right-a", "circle", 140, 72, 20, 20, "sunflower", "the matching spot"),
      pc("spot-left-b", "circle", 70, 144, 14, 14, "coral", "a little spot"),
      pc("spot-right-b", "circle", 130, 144, 14, 14, "coral", "the matching little spot"),
      pc("body", "oval", 100, 110, 16, 90, "cocoa", "the body"),
      pc("head", "circle", 100, 62, 20, 20, "cocoa", "the head"),
      pc("feeler-left", "whisker", 90, 44, 20, 20, "ink", "a feeler", dt({ rot: -28 })),
      pc("feeler-right", "whisker", 110, 44, 20, 20, "ink", "the other feeler", dt({ rot: 28, flip: true })),
    ],
  },
  {
    id: "flower",
    title: "A flower in the sun",
    childTitle: t3("A flower", "A flower in the sun", "A flower, leaves and all"),
    theme: "nature",
    tiers: ALL,
    invitation: t3("Colour each petal.", "Six petals. They can all be different.", "Petals are modified leaves — which is why a rose and an apple blossom are relatives."),
    pieces: [
      pc("sky", "rounded", 100, 100, 200, 200, "ice", "the sky behind"),
      pc("stem", "stem", 100, 150, 10, 96, "moss", "the stem"),
      pc("leaf-left", "leaf", 72, 146, 44, 26, "leaf", "a leaf", { rot: -18 }),
      pc("leaf-right", "leaf", 128, 162, 44, 26, "leaf", "the other leaf", { rot: 18, flip: true }),
      ...Array.from({ length: 6 }, (_, index) =>
        pc(
          `petal-${index}`,
          "petal",
          100 + Math.round(Math.cos((index * Math.PI) / 3 - Math.PI / 2) * 32),
          78 + Math.round(Math.sin((index * Math.PI) / 3 - Math.PI / 2) * 32),
          34,
          40,
          index % 2 ? "rose" : "coral",
          `petal number ${index + 1}`,
          { rot: (index * 60) % 360 },
        ),
      ),
      pc("middle", "circle", 100, 78, 32, 32, "sunflower", "the middle"),
      pc("soil", "grass", 100, 190, 190, 22, "cocoa", "the soil"),
    ],
  },
  {
    id: "tree",
    title: "A tree with a hollow",
    childTitle: t3("A tree", "A tree with a hollow", "A tree, with something living in it"),
    theme: "nature",
    tiers: ALL,
    invitation: t3("Colour the leaves.", "What season is your tree in?", "Autumn, spring or high summer — the colour is the season."),
    pieces: [
      pc("sky", "rounded", 100, 100, 200, 200, "ice", "the sky"),
      pc("trunk", "trunk", 100, 148, 34, 96, "bark", "the trunk"),
      pc("branch-left", "stripe", 76, 118, 6, 40, "bark", "a branch", { rot: 54 }),
      pc("branch-right", "stripe", 124, 112, 6, 40, "bark", "the other branch", { rot: -54 }),
      pc("canopy-mid", "bush", 100, 78, 116, 88, "leaf", "the big leaves"),
      pc("canopy-left", "bush", 58, 100, 64, 56, "moss", "more leaves"),
      pc("canopy-right", "bush", 142, 100, 64, 56, "moss", "more leaves"),
      pc("hollow", "oval", 100, 150, 22, 26, "cocoa", "the hollow"),
      pc("apple-a", "circle", 74, 76, 16, 16, "tomato", "a fruit"),
      pc("apple-b", "circle", 126, 64, 16, 16, "tomato", "another fruit"),
      pc("grass", "grass", 100, 190, 196, 22, "meadow", "the grass"),
    ],
  },

  /* ====================================================================== weather */
  {
    id: "rainbow",
    title: "After the rain",
    childTitle: t3("A rainbow", "After the rain", "A rainbow, in order"),
    theme: "weather",
    tiers: ALL,
    invitation: t3("Colour the stripes.", "Seven stripes. Use a different one for each.", "Red on the outside, violet on the inside — always, because of how light bends."),
    pieces: [
      pc("sky", "rounded", 100, 100, 200, 200, "ice", "the sky"),
      pc("band-1", "arch", 100, 168, 178, 160, "tomato", "the outside stripe"),
      pc("band-2", "arch", 100, 168, 152, 136, "honey", "the next stripe"),
      pc("band-3", "arch", 100, 168, 126, 114, "sunflower", "the middle stripe"),
      pc("band-4", "arch", 100, 168, 100, 92, "leaf", "the green stripe"),
      pc("band-5", "arch", 100, 168, 74, 68, "sea", "the blue stripe"),
      pc("band-6", "arch", 100, 168, 48, 46, "grape", "the inside stripe"),
      pc("cloud-left", "cloudPuff", 38, 148, 66, 40, "paper", "a cloud"),
      pc("cloud-right", "cloudPuff", 162, 148, 66, 40, "paper", "the other cloud"),
      pc("ground", "grass", 100, 190, 200, 24, "meadow", "the ground"),
    ],
  },
  {
    id: "sunny-day",
    title: "A sunny day",
    childTitle: t3("The sun", "A sunny day", "A sun with a whole sky around it"),
    theme: "weather",
    tiers: ALL,
    invitation: t3("Colour the sun.", "Colour every ray a different colour if you like.", "The sun is white. It only looks yellow from under an atmosphere."),
    pieces: [
      pc("sky", "rounded", 100, 100, 200, 200, "sky", "the whole sky"),
      ...Array.from({ length: 8 }, (_, index) =>
        pc(
          `ray-${index}`,
          "ray",
          88 + Math.round(Math.cos((index * Math.PI) / 4) * 52),
          80 + Math.round(Math.sin((index * Math.PI) / 4) * 52),
          22,
          34,
          "sunflower",
          `a sunbeam`,
          { rot: (index * 45 + 90) % 360 },
        ),
      ),
      pc("sun", "sun", 88, 80, 68, 68, "honey", "the sun"),
      pc("cloud-a", "cloudPuff", 152, 62, 72, 42, "paper", "a cloud"),
      pc("cloud-b", "cloudPuff", 44, 140, 62, 36, "ice", "another cloud"),
      pc("hill", "arch", 100, 202, 210, 78, "meadow", "the hill"),
    ],
  },
  {
    id: "snowman",
    title: "A snowy friend",
    childTitle: t3("A snowman", "A snowy friend", "A snowman, before it thaws"),
    theme: "weather",
    tiers: ALL,
    invitation: t3("Colour the scarf.", "The snow can stay white. The scarf cannot.", "The only warm thing in this picture is the scarf. Make it look it."),
    pieces: [
      pc("sky", "rounded", 100, 100, 200, 200, "midnight", "the night sky"),
      pc("snow", "arch", 100, 210, 220, 60, "paper", "the snowy ground"),
      pc("base", "circle", 100, 156, 84, 84, "paper", "the big snowball"),
      pc("middle", "circle", 100, 106, 62, 62, "paper", "the middle snowball"),
      pc("arm-left", "stripe", 58, 104, 5, 46, "bark", "a stick arm", { rot: 66 }),
      pc("arm-right", "stripe", 142, 104, 5, 46, "bark", "the other stick arm", { rot: -66 }),
      pc("scarf", "stripe", 100, 78, 56, 14, "tomato", "the scarf"),
      pc("scarf-tail", "stripe", 128, 96, 12, 34, "tomato", "the end of the scarf", { rot: 14 }),
      pc("head", "circle", 100, 54, 46, 46, "paper", "the head"),
      pc("hat", "rounded", 100, 26, 44, 26, "ink", "the hat"),
      pc("brim", "stripe", 100, 38, 60, 8, "ink", "the hat brim"),
      pc("carrot", "triangle", 100, 56, 26, 12, "honey", "the carrot nose", { rot: 90 }),
      pc("eye-left", "pupil", 91, 48, 7, 7, "ink", "an eye", dt()),
      pc("eye-right", "pupil", 109, 48, 7, 7, "ink", "the other eye", dt()),
      pc("button-a", "pupil", 100, 98, 8, 8, "ink", "a button", dt()),
      pc("button-b", "pupil", 100, 116, 8, 8, "ink", "another button", dt()),
      pc("flake-a", "snowCrystal", 34, 46, 18, 18, "ice", "a snowflake"),
      pc("flake-b", "snowCrystal", 168, 84, 14, 14, "ice", "another snowflake"),
    ],
  },

  /* ======================================================================== ocean */
  {
    id: "fish",
    title: "A rainbow fish",
    childTitle: t3("A fish", "A rainbow fish", "A fish, scale by scale"),
    theme: "ocean",
    tiers: ALL,
    invitation: t3("Colour each scale.", "Every scale can be a different colour.", "Scales overlap like roof tiles, which is why a fish can bend and still be covered."),
    pieces: [
      pc("water", "rounded", 100, 100, 200, 200, "sky", "the water"),
      pc("tail", "triangle", 158, 104, 54, 66, "coral", "the tail", { rot: 90 }),
      pc("body", "oval", 96, 104, 112, 74, "sunflower", "the body"),
      pc("fin-top", "fin", 92, 66, 44, 26, "coral", "the top fin"),
      pc("fin-low", "fin", 92, 142, 34, 20, "coral", "the bottom fin", { rot: 180 }),
      pc("scale-a", "crescent", 84, 92, 26, 26, "honey", "a scale", { rot: 90 }),
      pc("scale-b", "crescent", 84, 116, 26, 26, "tomato", "another scale", { rot: 90 }),
      pc("scale-c", "crescent", 110, 92, 26, 26, "tomato", "another scale", { rot: 90 }),
      pc("scale-d", "crescent", 110, 116, 26, 26, "honey", "the last scale", { rot: 90 }),
      pc("eye", "eye", 56, 96, 16, 17, "paper", "the eye"),
      pc("pupil", "pupil", 55, 97, 7, 7, "ink", "the eye", dt()),
      pc("bubble-a", "bubble", 34, 60, 16, 16, "ice", "a bubble"),
      pc("bubble-b", "bubble", 22, 38, 10, 10, "ice", "a little bubble"),
      pc("weed", "grass", 168, 184, 60, 36, "forest", "the seaweed"),
    ],
  },
  {
    id: "whale",
    title: "An ocean giant",
    childTitle: t3("A whale", "An ocean giant", "A whale, coming up to breathe"),
    theme: "ocean",
    tiers: ALL,
    invitation: t3("Colour the big body.", "This is the biggest animal there has ever been.", "Blue whales are larger than any dinosaur, and they eat some of the smallest things in the sea."),
    pieces: [
      pc("sky", "rounded", 100, 60, 200, 120, "ice", "the sky"),
      pc("sea", "rounded", 100, 160, 200, 80, "sea", "the sea"),
      pc("spout", "teardrop", 62, 44, 20, 34, "ice", "the spout"),
      pc("tail", "fin", 162, 108, 62, 56, "deepsea", "the tail", { rot: -34 }),
      pc("body", "blob", 92, 132, 132, 66, "deepsea", "the body"),
      pc("tummy", "arch", 92, 156, 104, 32, "paper", "the pale tummy", { rot: 180 }),
      pc("fin", "fin", 88, 156, 40, 24, "midnight", "the flipper", { rot: 24 }),
      pc("eye", "eye", 46, 124, 13, 13, "paper", "the eye"),
      pc("pupil", "pupil", 45, 125, 6, 6, "ink", "the eye", dt()),
      pc("wave-a", "wave", 40, 178, 80, 16, "ice", "a wave", dt()),
      pc("wave-b", "wave", 150, 190, 70, 14, "ice", "another wave", dt()),
    ],
  },
  {
    id: "under-the-sea",
    title: "Under the sea",
    childTitle: t3("The sea", "Under the sea", "A reef, from the bottom up"),
    theme: "ocean",
    tiers: OLDER,
    invitation: t3("Colour the sea.", "There is a lot going on down here.", "A reef is an animal, a plant and a rock all at once — colour it like something alive."),
    pieces: [
      pc("water", "rounded", 100, 100, 200, 200, "sea", "the water"),
      pc("light", "triangle", 70, 60, 90, 120, "sky", "sunlight coming down", { rot: 180 }),
      pc("sand", "arch", 100, 208, 220, 70, "sand", "the sandy bottom"),
      pc("coral-a", "bush", 40, 158, 56, 54, "coral", "a coral"),
      pc("coral-b", "bush", 164, 166, 50, 46, "rose", "another coral"),
      pc("weed-a", "grass", 96, 178, 54, 50, "forest", "the seaweed"),
      pc("rock", "blob", 132, 186, 52, 26, "stone", "a rock"),
      pc("fish-body", "oval", 100, 104, 56, 38, "sunflower", "a fish"),
      pc("fish-tail", "triangle", 132, 104, 26, 32, "honey", "the fish tail", { rot: 90 }),
      pc("fish-eye", "pupil", 84, 98, 7, 7, "ink", "the fish eye", dt()),
      pc("fish2-body", "oval", 48, 74, 40, 26, "coral", "a smaller fish"),
      pc("fish2-tail", "triangle", 70, 74, 18, 22, "tomato", "its tail", { rot: 90 }),
      pc("star", "star", 158, 194, 26, 26, "honey", "a starfish"),
      pc("bubble-a", "bubble", 120, 60, 14, 14, "ice", "a bubble"),
      pc("bubble-b", "bubble", 134, 42, 9, 9, "ice", "a little bubble"),
    ],
  },

  /* ======================================================================== space */
  {
    id: "rocket",
    title: "A moon rocket",
    childTitle: t3("A rocket", "A moon rocket", "A rocket, at the moment of launch"),
    theme: "space",
    tiers: ALL,
    invitation: t3("Colour the rocket.", "Where is your rocket going?", "Real rockets are mostly white, to keep the fuel inside them cold. Yours need not be."),
    pieces: [
      pc("sky", "rounded", 100, 100, 200, 200, "midnight", "the night sky"),
      pc("star-a", "star", 34, 40, 18, 18, "sunflower", "a star"),
      pc("star-b", "star", 168, 64, 14, 14, "sunflower", "another star"),
      pc("star-c", "star", 44, 150, 12, 12, "sunflower", "a far star"),
      pc("moon", "crescent", 160, 36, 34, 34, "ice", "the moon"),
      pc("flame", "flame", 100, 176, 40, 48, "tomato", "the flame"),
      pc("flame-inner", "flame", 100, 172, 22, 32, "sunflower", "the hot middle of the flame"),
      pc("fin-left", "triangle", 70, 148, 32, 42, "tomato", "a fin", { rot: -28 }),
      pc("fin-right", "triangle", 130, 148, 32, 42, "tomato", "the other fin", { rot: 28 }),
      pc("body", "rounded", 100, 116, 58, 104, "paper", "the rocket body"),
      pc("nose", "triangle", 100, 56, 58, 46, "tomato", "the nose cone"),
      pc("window", "circle", 100, 104, 32, 32, "sky", "the window"),
      pc("window-rim", "circle", 100, 104, 38, 38, "stone", "around the window"),
      pc("stripe", "stripe", 100, 148, 58, 10, "tomato", "a stripe"),
    ],
  },
  {
    id: "planet",
    title: "A planet with rings",
    childTitle: t3("A planet", "A planet with rings", "A ringed planet and its moons"),
    theme: "space",
    tiers: OLDER,
    invitation: t3("Colour the big planet.", "The rings are made of ice and rock.", "Saturn's rings are mostly water ice, and they are only about ten metres thick."),
    pieces: [
      pc("sky", "rounded", 100, 100, 200, 200, "midnight", "space"),
      pc("star-a", "star", 30, 38, 14, 14, "paper", "a star"),
      pc("star-b", "star", 174, 44, 10, 10, "paper", "another star"),
      pc("star-c", "star", 156, 172, 12, 12, "paper", "a far star"),
      pc("ring-back", "oval", 100, 104, 160, 34, "lavender", "the back of the rings", { rot: -16 }),
      pc("planet", "circle", 100, 100, 96, 96, "honey", "the planet"),
      pc("band-a", "stripe", 100, 82, 88, 12, "apricot", "a cloud band", { rot: -4 }),
      pc("band-b", "stripe", 100, 116, 80, 10, "tomato", "another cloud band", { rot: -4 }),
      pc("ring-front", "crescent", 100, 118, 160, 40, "grape", "the front of the rings", { rot: -16 }),
      pc("moon-a", "circle", 42, 150, 22, 22, "stone", "a moon"),
      pc("moon-b", "circle", 170, 128, 14, 14, "stone", "a smaller moon"),
    ],
  },

  /* ===================================================================== machines */
  {
    id: "car",
    title: "An adventure car",
    childTitle: t3("A car", "An adventure car", "A car, packed for somewhere"),
    theme: "machines",
    tiers: ALL,
    invitation: t3("Colour the car.", "Where is this car going?", "Choose a colour you would actually want to be seen in."),
    pieces: [
      pc("sky", "rounded", 100, 76, 200, 152, "ice", "the sky"),
      pc("road", "rounded", 100, 180, 200, 44, "stone", "the road"),
      pc("body", "rounded", 100, 124, 136, 46, "tomato", "the car body"),
      pc("cabin", "arch", 100, 104, 86, 44, "tomato", "the roof"),
      pc("window-front", "window", 78, 96, 32, 26, "sky", "a window"),
      pc("window-back", "window", 118, 96, 32, 26, "sky", "the other window"),
      pc("wheel-left", "wheel", 66, 152, 36, 36, "ink", "a wheel"),
      pc("wheel-right", "wheel", 134, 152, 36, 36, "ink", "the other wheel"),
      pc("hub-left", "circle", 66, 152, 14, 14, "stone", "the middle of a wheel"),
      pc("hub-right", "circle", 134, 152, 14, 14, "stone", "the middle of the other wheel"),
      pc("light", "circle", 164, 124, 14, 14, "sunflower", "a headlight"),
      pc("bumper", "stripe", 100, 144, 140, 8, "stone", "the bumper"),
    ],
  },
  {
    id: "train",
    title: "A discovery train",
    childTitle: t3("A train", "A discovery train", "A steam train, under way"),
    theme: "machines",
    tiers: ALL,
    invitation: t3("Colour the engine.", "Colour the engine, then the smoke.", "Steam is water. It comes out white and the smoke above it does not."),
    pieces: [
      pc("sky", "rounded", 100, 80, 200, 160, "ice", "the sky"),
      pc("smoke-a", "cloudPuff", 62, 42, 44, 28, "paper", "a puff of steam"),
      pc("smoke-b", "cloudPuff", 96, 26, 34, 22, "stone", "another puff"),
      pc("track", "stripe", 100, 176, 200, 8, "bark", "the track"),
      pc("body", "rounded", 92, 130, 108, 46, "sea", "the engine"),
      pc("cab", "rounded", 148, 112, 54, 60, "sea", "the driver's cab"),
      pc("cab-window", "window", 148, 104, 30, 26, "sky", "the cab window"),
      pc("funnel", "stripe", 56, 100, 22, 40, "ink", "the funnel"),
      pc("funnel-top", "stripe", 56, 82, 32, 10, "ink", "the top of the funnel"),
      pc("boiler-band", "stripe", 100, 130, 108, 8, "honey", "a gold band"),
      pc("wheel-a", "wheel", 66, 160, 30, 30, "ink", "a wheel"),
      pc("wheel-b", "wheel", 110, 160, 30, 30, "ink", "another wheel"),
      pc("wheel-c", "wheel", 156, 162, 24, 24, "ink", "a little wheel"),
      pc("lamp", "circle", 40, 128, 18, 18, "sunflower", "the lamp"),
      pc("ground", "grass", 100, 192, 200, 20, "meadow", "the grass"),
    ],
  },
  {
    id: "robot",
    title: "A robot friend",
    childTitle: t3("A robot", "A robot friend", "A robot, built for one job"),
    theme: "machines",
    tiers: ALL,
    invitation: t3("Colour the robot.", "What is your robot for?", "Give it a colour that says what it does. Rescue robots are orange for a reason."),
    pieces: [
      pc("backdrop", "rounded", 100, 100, 200, 200, "ice", "the wall behind"),
      pc("antenna", "stripe", 100, 34, 5, 24, "stone", "the aerial"),
      pc("antenna-tip", "circle", 100, 24, 16, 16, "tomato", "the light on top"),
      pc("head", "rounded", 100, 62, 72, 52, "stone", "the head"),
      pc("screen", "window", 100, 60, 52, 32, "sky", "the face screen"),
      pc("eye-left", "circle", 88, 58, 12, 12, "ink", "an eye", dt()),
      pc("eye-right", "circle", 112, 58, 12, 12, "ink", "the other eye", dt()),
      pc("mouth", "stripe", 100, 74, 26, 5, "ink", "the mouth", dt()),
      pc("neck", "stripe", 100, 92, 18, 12, "stone", "the neck"),
      pc("body", "rounded", 100, 130, 84, 64, "sea", "the body"),
      pc("panel", "window", 100, 128, 44, 34, "midnight", "the control panel"),
      pc("button-a", "circle", 88, 122, 10, 10, "sunflower", "a button"),
      pc("button-b", "circle", 108, 122, 10, 10, "tomato", "another button"),
      pc("dial", "circle", 100, 138, 14, 14, "leaf", "a dial"),
      pc("arm-left", "rounded", 46, 128, 18, 54, "stone", "an arm"),
      pc("arm-right", "rounded", 154, 128, 18, 54, "stone", "the other arm"),
      pc("hand-left", "circle", 46, 160, 20, 20, "sea", "a hand"),
      pc("hand-right", "circle", 154, 160, 20, 20, "sea", "the other hand"),
      pc("leg-left", "rounded", 84, 180, 20, 36, "stone", "a leg"),
      pc("leg-right", "rounded", 116, 180, 20, 36, "stone", "the other leg"),
    ],
  },
  {
    id: "boat",
    title: "A sailing day",
    childTitle: t3("A boat", "A sailing day", "A boat with the wind behind it"),
    theme: "machines",
    tiers: ALL,
    invitation: t3("Colour the sail.", "The wind is behind the sail. Colour it.", "A sail works like a wing: the wind goes round it, not just into it."),
    pieces: [
      pc("sky", "rounded", 100, 66, 200, 132, "sky", "the sky"),
      pc("sun", "sun", 164, 36, 40, 40, "sunflower", "the sun"),
      pc("sea", "rounded", 100, 168, 200, 64, "sea", "the sea"),
      pc("mast", "stripe", 100, 92, 6, 96, "bark", "the mast"),
      pc("sail-big", "sail", 118, 96, 54, 88, "paper", "the big sail"),
      pc("sail-small", "sail", 80, 104, 34, 70, "coral", "the little sail", { flip: true }),
      pc("hull", "arch", 100, 168, 130, 44, "brick", "the hull", { rot: 180 }),
      pc("flag", "flag", 112, 46, 24, 16, "tomato", "the flag"),
      pc("wave-a", "wave", 46, 184, 70, 16, "ice", "a wave", dt()),
      pc("wave-b", "wave", 152, 192, 66, 14, "ice", "another wave", dt()),
    ],
  },

  /* ========================================================================= home */
  {
    id: "house",
    title: "A dream home",
    childTitle: t3("A house", "A dream home", "A house you would want to live in"),
    theme: "home",
    tiers: ALL,
    invitation: t3("Colour the door.", "Colour the door the colour you would want.", "Front doors are the one part of a house people choose a colour for on purpose."),
    pieces: [
      pc("sky", "rounded", 100, 80, 200, 160, "sky", "the sky"),
      pc("ground", "grass", 100, 186, 200, 32, "meadow", "the garden"),
      pc("walls", "square", 100, 136, 112, 78, "apricot", "the walls"),
      pc("roof", "roof", 100, 82, 148, 54, "brick", "the roof"),
      pc("chimney", "chimney", 142, 62, 20, 34, "brick", "the chimney"),
      pc("smoke", "cloudPuff", 148, 38, 34, 22, "stone", "the smoke"),
      pc("door", "door", 100, 156, 34, 44, "sea", "the front door"),
      pc("knob", "circle", 112, 158, 7, 7, "honey", "the door knob", dt()),
      pc("window-left", "window", 66, 124, 32, 28, "ice", "a window"),
      pc("window-right", "window", 134, 124, 32, 28, "ice", "the other window"),
      pc("path", "stripe", 100, 184, 26, 26, "sand", "the path"),
      pc("bush", "bush", 44, 168, 40, 34, "moss", "a bush"),
      pc("flower", "petal", 156, 172, 16, 20, "rose", "a flower"),
    ],
  },
  {
    id: "castle",
    title: "A wonder castle",
    childTitle: t3("A castle", "A wonder castle", "A castle, built to be defended"),
    theme: "home",
    tiers: ALL,
    invitation: t3("Colour the flags.", "Give each tower its own flag.", "Every tower flew its own colours so you knew from a distance who was inside."),
    pieces: [
      pc("sky", "rounded", 100, 86, 200, 172, "lavender", "the evening sky"),
      pc("hill", "arch", 100, 206, 220, 70, "moss", "the hill"),
      pc("tower-left", "square", 46, 132, 42, 96, "stone", "the left tower"),
      pc("tower-right", "square", 154, 132, 42, 96, "stone", "the right tower"),
      pc("keep", "square", 100, 146, 84, 76, "stone", "the great hall"),
      pc("roof-left", "triangle", 46, 74, 50, 40, "grape", "the left roof"),
      pc("roof-right", "triangle", 154, 74, 50, 40, "grape", "the right roof"),
      pc("roof-keep", "triangle", 100, 98, 92, 40, "grape", "the middle roof"),
      pc("flag-left", "flag", 56, 46, 22, 14, "tomato", "the left flag"),
      pc("flag-right", "flag", 164, 46, 22, 14, "sea", "the right flag"),
      pc("gate", "arch", 100, 184, 40, 48, "cocoa", "the gate"),
      pc("window-a", "window", 46, 120, 16, 22, "sunflower", "a lit window"),
      pc("window-b", "window", 154, 120, 16, 22, "sunflower", "another lit window"),
      pc("window-c", "window", 100, 134, 18, 24, "sunflower", "the big window"),
      pc("moon", "crescent", 172, 34, 26, 26, "ice", "the moon"),
    ],
  },

  /* ================================================================== celebration */
  {
    id: "cupcake",
    title: "A little celebration",
    childTitle: t3("A cake", "A little celebration", "A cupcake, iced and lit"),
    theme: "celebration",
    tiers: ALL,
    invitation: t3("Colour the icing.", "Icing first, then the sprinkles.", "Sprinkles are the only part of this you get to place wherever you want."),
    pieces: [
      pc("backdrop", "rounded", 100, 100, 200, 200, "candyfloss", "the wall behind"),
      pc("case", "arch", 100, 160, 96, 76, "sea", "the paper case", { rot: 180 }),
      pc("case-line-a", "stripe", 78, 160, 6, 68, "deepsea", "a fold in the case", dt()),
      pc("case-line-b", "stripe", 100, 160, 6, 72, "deepsea", "another fold", dt()),
      pc("case-line-c", "stripe", 122, 160, 6, 68, "deepsea", "another fold", dt()),
      pc("icing", "cloudPuff", 100, 100, 124, 56, "rose", "the icing"),
      pc("icing-top", "cloudPuff", 100, 78, 78, 40, "coral", "the top of the icing"),
      pc("cherry", "circle", 100, 56, 24, 24, "tomato", "the cherry"),
      pc("candle", "stripe", 100, 34, 8, 28, "paper", "the candle"),
      pc("flame", "flame", 100, 16, 14, 18, "sunflower", "the flame"),
      pc("sprinkle-a", "stripe", 74, 92, 12, 5, "sunflower", "a sprinkle", dt({ rot: 30 })),
      pc("sprinkle-b", "stripe", 126, 96, 12, 5, "leaf", "a sprinkle", dt({ rot: -20 })),
      pc("sprinkle-c", "stripe", 100, 108, 12, 5, "sky", "a sprinkle", dt({ rot: 60 })),
      pc("sprinkle-d", "stripe", 112, 84, 12, 5, "grape", "a sprinkle", dt({ rot: -50 })),
    ],
  },
  {
    id: "party",
    title: "Balloons and bunting",
    childTitle: t3("Balloons", "Balloons and bunting", "A party, ready before anyone arrives"),
    theme: "celebration",
    tiers: ALL,
    invitation: t3("Colour the balloons.", "Give every balloon its own colour.", "Bunting was invented for ships. Nobody minds that it ended up here."),
    pieces: [
      pc("wall", "rounded", 100, 100, 200, 200, "ice", "the wall"),
      pc("string-a", "stripe", 60, 122, 3, 76, "stone", "a string", dt({ rot: 6 })),
      pc("string-b", "stripe", 100, 130, 3, 84, "stone", "another string", dt()),
      pc("string-c", "stripe", 142, 126, 3, 78, "stone", "another string", dt({ rot: -6 })),
      pc("balloon-a", "egg", 60, 84, 50, 62, "tomato", "a balloon"),
      pc("balloon-b", "egg", 100, 88, 54, 66, "sunflower", "the middle balloon"),
      pc("balloon-c", "egg", 142, 86, 50, 62, "grape", "the last balloon"),
      pc("shine-a", "oval", 50, 70, 12, 16, "paper", "a shine", dt({ rot: -20 })),
      pc("shine-b", "oval", 90, 74, 12, 16, "paper", "a shine", dt({ rot: -20 })),
      pc("shine-c", "oval", 132, 72, 12, 16, "paper", "a shine", dt({ rot: -20 })),
      pc("bunting-line", "wave", 100, 34, 190, 18, "stone", "the bunting string", dt()),
      pc("flag-a", "triangle", 38, 44, 24, 26, "leaf", "a bunting flag", { rot: 180 }),
      pc("flag-b", "triangle", 74, 38, 24, 26, "coral", "another flag", { rot: 180 }),
      pc("flag-c", "triangle", 110, 38, 24, 26, "sea", "another flag", { rot: 180 }),
      pc("flag-d", "triangle", 146, 44, 24, 26, "honey", "the last flag", { rot: 180 }),
      pc("table", "stripe", 100, 176, 190, 14, "timber", "the table"),
      pc("cake", "rounded", 100, 160, 44, 24, "candyfloss", "a cake"),
    ],
  },
];

export const pageById = new Map(colouringPages.map((page) => [page.id, page]));

/** The pages a child of this tier is offered, in shelf order. */
export function pagesForTier(tier: StudioTier): ColouringPage[] {
  return colouringPages.filter((page) => page.tiers.includes(tier));
}

/** A page's fillable regions — everything that is not a detail line. */
export function fillablePieces(page: ColouringPage): Piece[] {
  return page.pieces.filter((piece) => !piece.detail);
}
