'use client';
import {useEffect,useRef,useState,useCallback} from 'react';
import {ArrowLeft,ArrowRight,RefreshCw} from 'lucide-react';
import type {ReadingView,ReadingActivity} from '@/lib/reading/types';
import {AudioButton} from './AudioButton';
import {LetterCatch} from './LetterCatch';
import {BlendTrain} from './BlendTrain';
import {SoundBoxes} from './SoundBoxes';
import {DecodableReader} from './DecodableReader';
import {celebrate} from '@/lib/audio';
async function fetchReading(profileId:string,signal?:AbortSignal):Promise<ReadingView>{const r=await fetch(`/api/reading?profile=${encodeURIComponent(profileId)}`,{signal:signal?AbortSignal.any([signal,AbortSignal.timeout(20000)]):AbortSignal.timeout(20000)});const d=await r.json() as ReadingView;if(!r.ok)throw Error(d.error);return d;}
export function ReadingAdventure({profileId,name,paused,offline,onStars}:{profileId:string;name:string;paused:boolean;offline:boolean;onStars:(stars:number)=>void}){
  const [data,setData]=useState<ReadingView|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[playing,setPlaying]=useState(false),[success,setSuccess]=useState<{activity:ReadingActivity;text:string}|null>(null);
  const lock=useRef(false),stage=useRef<HTMLDivElement>(null);
  const refresh=useCallback(async()=>{try{setData(await fetchReading(profileId));setError('');}catch(e){setError(e instanceof Error?e.message:'Try again.');}},[profileId]);
  useEffect(()=>{const controller=new AbortController();fetchReading(profileId,controller.signal).then(d=>{if(!controller.signal.aborted){setData(d);setError('');}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>{controller.abort();window.speechSynthesis?.cancel();};},[profileId]);
  async function act(action:string,response?:string){if(!data||lock.current)return;lock.current=true;setBusy(true);setError('');const previous=data.session?.activity;
    try{const r=await fetch('/api/reading',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(20000),body:JSON.stringify({action,profile:profileId,revision:data.revision,session:data.session?.id,activity:previous?.id,response})});const next=await r.json() as ReadingView;if(!r.ok)throw Error(next.error);setData(next);onStars(next.stars);if(action==='start'){setPlaying(true);setSuccess(null);requestAnimationFrame(()=>stage.current?.scrollIntoView({block:'start',behavior:'instant'}));}if(action==='answer'&&next.correct&&previous){setSuccess({activity:previous,text:next.feedback??'A new discovery!'});celebrate(!!next.session?.completedAt&&next.session.kind==='quest');}if(action==='skip')setSuccess(null);
    }catch(e){setError(e instanceof Error?e.message:'Try again.');}finally{lock.current=false;setBusy(false);}}
  const session=data?.session,activity=session?.activity;
  const skill=data?.catalog.skills.find(s=>s.id===activity?.skillId),word=data?.catalog.words.find(w=>w.id===activity?.target),story=data?.catalog.stories.find(s=>s.id===activity?.target);
  const help=session?.helpLevel??0;
  const prompt=activity?.kind==='letter-catch'?`Listen to ${skill?.example}. Find the letter for its first sound.`:activity?.kind==='blend-train'?'Say the sounds and slide the train cars together. Then read the word.':activity?.kind==='sound-boxes'?'Listen to the word and put one letter in each sound box.':'Try reading each little word. Then tell us about the story.';
  function helpedText(){if(!activity)return '';if(activity.kind==='letter-catch')return `${skill?.cue} The letter is ${activity.target}.`;if(activity.kind==='story')return help>=4?story?.pages[session?.storyPage??0]??story?.pages.join(' ')??'':'Look at every letter. Say each sound and slide the sounds together.';if(help>=4)return word?.word??'';return help>=3?`Say the sounds slowly, without a gap: ${word?.word}.`:`${word?.graphemes.map(l=>data?.catalog.skills.find(s=>s.letter===l)?.cue).join(' ')}`;}
  return <section className="reading-adventure" ref={stage}>
    {error&&<div className="error" role="alert">{error}<button className="secondary" disabled={busy} onClick={()=>{setSuccess(null);void refresh();}}><RefreshCw size={18}/>Refresh my saved place</button></div>}
    {!data&&!error&&<p className="loading" role="status">Nova is opening your reading map…</p>}
    {data&&(!playing?<><header className="reading-hero"><div><span className="eyebrow">NOVA’S READING ADVENTURE</span><h1>A sound.<br/>A word.<br/>A whole new world.</h1><p>{name}, let’s discover what letters can do.</p><button className="primary" disabled={busy||paused} onClick={()=>act('start')}>{!data.profile.placementDone?'Find my reading trail':session&&!session.completedAt?'Continue my reading quest':'Start my reading quest'}<ArrowRight size={21}/></button><small>{!data.profile.placementDone?'A few playful clues. Help is always welcome.':'A short adventure · save your place at any time'}</small></div><div className="reading-hero-world" aria-hidden="true"><span className="reading-moon">✦</span><span className="reading-tree">🌲</span><span className="reading-fox">🦊</span><span className="reading-book">📖</span><i>m</i><i>a</i><i>t</i></div></header>
      <div className="reading-map" aria-label="Your reading trail">{[['👂','Listen','Hear a word’s first sound'],['🏡','Letter Village','Meet m · s · a · t · p · i · n'],['🚂','Sound Bridge','Bring sounds together'],['🧩','Word Workshop','Build the word you hear'],['📖','Story Trail','Read a tiny book']].map(([emoji,title,detail],i)=><div key={title} className={i<2||data.readyWords.length?'reading-map-stop ready':'reading-map-stop'}><span>{emoji}</span><h2>{title}</h2><p>{detail}</p></div>)}</div>
      <section className="reading-shelf"><h2>My little reading shelf</h2><p>Words appear as their sounds become ready for practice. Pictures help explain meaning after the word—not guess it.</p><div className="reading-word-shelf">{data.readyWords.length?data.readyWords.map(w=><details key={w.id}><summary>{w.word}</summary><span aria-hidden="true">{w.emoji}</span><p>{w.meaning}</p><AudioButton text={w.word} src={w.audioSrc}/></details>):<p>Your first word is waiting on the trail. Begin with a little sound.</p>}</div>{data.profile.books.length>0&&<p className="success">📖 You explored {data.profile.books.length} tiny book. It can return in another reading quest.</p>}</section>
    </>:<div className="reading-session"><header><button className="text-button" disabled={busy} onClick={()=>{setPlaying(false);setSuccess(null);window.speechSynthesis?.cancel();}}><ArrowLeft size={19}/>Save & take a break</button><span>{session?.kind==='placement'?'Nova’s Reading Map Adventure':'Your reading quest'}</span></header>
      <div className="reading-progress" aria-label={`${session?.index??0} of ${session?.total??0} discoveries explored`}>{Array.from({length:session?.total??0},(_,i)=><span key={i} className={i<(session?.index??0)?'visited':''}>{i<(session?.index??0)?'✦':'○'}</span>)}</div>
      {success?<div className="reading-success"><span className="eyebrow">YOU MADE A DISCOVERY</span><h2>{success.activity.kind==='letter-catch'?success.activity.target:success.activity.kind==='story'?'A little story, understood.':data.catalog.words.find(w=>w.id===success.activity.target)?.word}</h2>{['blend-train','sound-boxes'].includes(success.activity.kind)&&<div className="word-meaning"><span aria-hidden="true">{data.catalog.words.find(w=>w.id===success.activity.target)?.emoji}</span><p>{data.catalog.words.find(w=>w.id===success.activity.target)?.meaning}</p></div>}<p>{success.text}</p><button className="primary" onClick={()=>{setSuccess(null);requestAnimationFrame(()=>stage.current?.scrollIntoView({block:'start',behavior:'instant'}));}}>Keep my trail going<ArrowRight size={20}/></button></div>:session?.completedAt?<div className="reading-complete"><span aria-hidden="true">🦊 📖</span><h2>{session.kind==='placement'?'Your next adventure begins here.':'Look what you explored!'}</h2><p>{session.kind==='placement'?'Nova found a gentle starting place. Let’s meet a sound together.':'You listened, connected sounds, and tried ideas. Your reading place is saved.'}</p>{session.kind==='quest'&&<><strong>3 explorer stars earned</strong>{offline&&<p className="reading-offline">With a grown-up, find something that begins with the first sound in “moon.” Stretch that sound together.</p>}</>}<button className="primary" disabled={busy||paused} onClick={()=>session.kind==='placement'?act('start'):setPlaying(false)}>{session.kind==='placement'?'Meet my first sound':'Back to my reading map'}<ArrowRight size={20}/></button></div>:activity&&<>
        <AudioButton text={prompt} label="Hear my mission"/>
        {activity.kind==='letter-catch'&&skill&&<LetterCatch key={session!.id+activity.id} activity={activity} skill={skill} needsTeaching={activity.taught&&!data.profile.introduced.includes(activity.target)} busy={busy||paused} onTeach={()=>act('teach')} onAnswer={answer=>act('answer',answer)}/>}
        {activity.kind==='blend-train'&&word&&<BlendTrain key={session!.id+activity.id} activity={activity} word={word} busy={busy||paused} onAnswer={answer=>act('answer',answer)}/>}
        {activity.kind==='sound-boxes'&&word&&<SoundBoxes key={session!.id+activity.id} activity={activity} word={word} busy={busy||paused} onAnswer={answer=>act('answer',answer)}/>}
        {activity.kind==='story'&&story&&<DecodableReader story={story} page={session?.storyPage??0} busy={busy||paused} onPage={()=>act('story-page')} onAnswer={answer=>act('answer',answer)} onHelp={()=>act('help')}/>}
        {data.feedback&&<p className="reading-feedback" role="status">🦊 {data.feedback}</p>}
        {help>0&&<aside className={`reading-help help-${help}`}><strong>{['','Look at the letters','Try each sound','Slide the sounds','Try it together'][help]}</strong>{help===1?<p className="scaffold-letters">{activity.kind==='story'?story?.pages[session?.storyPage??0]??'':activity.target.split('').join(' · ')}</p>:<><p>{helpedText()}</p><AudioButton text={helpedText()} label="Hear this help" slow/></>}</aside>}
        <div className="reading-support"><button className="secondary" disabled={busy||paused||help===4} onClick={()=>act('help')}>A little help</button><button className="text-button" disabled={busy||paused||(activity.taught&&!data.profile.introduced.includes(activity.target))} onClick={()=>act('skip')}>{session?.kind==='placement'?'I’m still learning this':'Save this for another day'}</button></div>
      </>}
    </div>)}
  </section>;
}
